//! The exported arena, read through the closed view, against direct `Air::eval`
//! and the pinned upstream debug checker on honest and invalid traces.

mod common;

use common::*;
use p3_commit::PolynomialSpace;
use p3_field::PrimeCharacteristicRing;
use p3_field::coset::TwoAdicMultiplicativeCoset;
use p3_matrix::Matrix;
use p3_matrix::dense::RowMajorMatrix;
use zkc_plonky3_air::capture::{reconstruct, same_expression, upstream_constraints};
use zkc_plonky3_air::field::{Ext8, F, generator};
use zkc_plonky3_air::reference::{
    lagrange_selectors_at, open_table, point_residuals, row_residuals,
    two_adic_selectors_on_domain, upstream_accepts, upstream_failures,
};
use zkc_plonky3_air::view::{SelectorLaw, violations};
use zkc_plonky3_air::{Export, SelectorKind};
use zkc_plonky3_air_client::{CounterAir, RecurrenceAir};
use zkc_plonky3_air_driver::{files, fixtures, import_violations};

fn recurrence(log_height: usize) -> (RecurrenceAir, Export, RowMajorMatrix<F>, Vec<F>) {
    let air = RecurrenceAir { log_height };
    let export = zkc_plonky3_air::export(&air, "recurrence").unwrap();
    let (trace, publics) = air.generate(F::from_u32(2), F::from_u32(5));
    (air, export, trace, publics)
}

/// Honest trace, every single-cell perturbation of three rows, and each
/// public value changed.
fn cases(trace: &RowMajorMatrix<F>, publics: &[F]) -> Vec<(String, RowMajorMatrix<F>, Vec<F>)> {
    let mut cases = vec![("honest".to_string(), trace.clone(), publics.to_vec())];
    for (name, t) in perturbations(trace) {
        cases.push((name, t, publics.to_vec()));
    }
    for i in 0..publics.len() {
        let mut p = publics.to_vec();
        p[i] += F::ONE;
        cases.push((format!("public {i}"), trace.clone(), p));
    }
    cases
}

#[test]
fn fixtures_regenerate_exactly_and_import_to_upstream_failures() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../fixtures");
    for fixture in fixtures().unwrap() {
        let directory = root.join(fixture.name);
        for (file, text) in files(&fixture) {
            let committed = std::fs::read_to_string(directory.join(file)).unwrap();
            assert_eq!(
                committed, text,
                "{}/{file} must be regenerated by the fixture driver",
                fixture.name
            );
        }
        let read = |f: &str| std::fs::read_to_string(directory.join(f)).unwrap();
        let imported = import_violations(
            &read("export.json"),
            &read("instance.json"),
            &read("witness.json"),
        )
        .unwrap();
        assert_eq!(imported, fixture.upstream_failures, "{}", fixture.name);
    }
}

#[test]
fn capture_round_trips_through_the_artifact_and_back_to_upstream_expressions() {
    for log_height in [0, 3] {
        let (air, export, _, _) = recurrence(log_height);
        assert_eq!(Export::parse(&export.to_text()).unwrap(), export);
        let upstream = upstream_constraints(&air).unwrap();
        let rebuilt = reconstruct(&export);
        assert_eq!(upstream.len(), 9);
        assert_eq!(rebuilt.len(), upstream.len());
        for (i, (a, b)) in upstream.iter().zip(&rebuilt).enumerate() {
            assert!(same_expression(a, b), "constraint {i} differs after export");
        }
    }
    for guarded in [false, true] {
        let air = CounterAir { guarded };
        let export = zkc_plonky3_air::export(&air, "counter").unwrap();
        let upstream = upstream_constraints(&air).unwrap();
        assert!(same_expression(&upstream[0], &reconstruct(&export)[0]));
    }
    // A mutated reconstruction is not equal: the comparison is not vacuous.
    let (air, export, _, _) = recurrence(3);
    let upstream = upstream_constraints(&air).unwrap();
    let rebuilt = reconstruct(&export);
    assert!(!same_expression(&upstream[4], &rebuilt[5]));
}

#[test]
fn constants_are_canonical_representatives_not_internal_residues() {
    let (_, export, _, _) = recurrence(3);
    let constants: Vec<u32> = export
        .arena
        .nodes()
        .iter()
        .filter_map(|n| match n {
            zkc_plonky3_air::arena::Node::Constant(c) => Some(*c),
            _ => None,
        })
        .collect();
    assert_eq!(constants, [zkc_plonky3_air_client::STEP_CONSTANT]);
    assert!(export.arena_text().contains("\"123456789\""));
}

#[test]
fn row_indicator_law_matches_direct_evaluation_and_the_upstream_debug_checker() {
    for log_height in 0..=6 {
        let (air, export, trace, publics) = recurrence(log_height);
        let height = trace.height();
        for (name, trace, publics) in cases(&trace, &publics) {
            let view = bind(&export, height, &publics);
            let adapter =
                view.residuals(&view.row_inputs(&trace, SelectorLaw::RowIndicator).unwrap());
            let direct = row_residuals(&air, &trace, &publics, SelectorLaw::RowIndicator).unwrap();
            assert_eq!(adapter, direct, "height {height}, {name}: residual values");
            let failures = upstream_failures(&air, &trace, &publics);
            assert_eq!(
                violations(&adapter, 9),
                failures,
                "height {height}, {name}: zero locus"
            );
            assert_eq!(
                upstream_accepts(&air, &trace, &publics),
                failures.is_empty(),
                "height {height}, {name}"
            );
            // Every column and public value is constrained, so every change is caught.
            assert_eq!(
                failures.is_empty(),
                name == "honest",
                "height {height}, {name}"
            );
        }
    }
}

#[test]
fn two_adic_law_has_the_row_law_zero_locus_with_different_values() {
    let mut differing_values = 0;
    for log_height in 0..=6 {
        let (air, export, trace, publics) = recurrence(log_height);
        let height = trace.height();
        for (name, trace, publics) in cases(&trace, &publics) {
            let view = bind(&export, height, &publics);
            let point_law = view.residuals(
                &view
                    .row_inputs(&trace, SelectorLaw::TwoAdicLagrange)
                    .unwrap(),
            );
            let direct =
                row_residuals(&air, &trace, &publics, SelectorLaw::TwoAdicLagrange).unwrap();
            assert_eq!(
                point_law, direct,
                "height {height}, {name}: two-adic residual values"
            );
            let row_law =
                view.residuals(&view.row_inputs(&trace, SelectorLaw::RowIndicator).unwrap());
            assert_eq!(
                violations(&point_law, 9),
                violations(&row_law, 9),
                "height {height}, {name}: zero locus"
            );
            differing_values += usize::from(point_law != row_law);
        }
    }
    assert!(
        differing_values > 0,
        "the two laws must not be treated as equal residuals"
    );
}

#[test]
fn selector_closed_forms_match_definitions_and_the_upstream_two_adic_domain() {
    for log_height in 0..=8 {
        let height = 1 << log_height;
        let (_, export, _, publics) = recurrence(log_height);
        let view = bind(&export, height, &publics);
        let defined = two_adic_selectors_on_domain(height);
        for (row, values) in defined.iter().enumerate() {
            for (kind, value) in SelectorKind::ALL.into_iter().zip(values) {
                assert_eq!(
                    view.selector_on_row(kind, row, SelectorLaw::TwoAdicLagrange),
                    *value,
                    "{kind:?} row {row}"
                );
            }
        }
        let domain = TwoAdicMultiplicativeCoset::new(F::ONE, log_height).unwrap();
        assert_eq!(domain.subgroup_generator(), generator(log_height));
        for point in points() {
            let upstream = domain.selectors_at_point(point);
            let product = lagrange_selectors_at(point, height).unwrap();
            assert_eq!(
                [
                    upstream.is_first_row,
                    upstream.is_last_row,
                    upstream.is_transition
                ],
                product
            );
        }
        let on_domain = Ext8::from(generator(log_height).exp_u64(height as u64 / 2));
        assert_eq!(
            lagrange_selectors_at(on_domain, height).unwrap_err().id,
            "plonky3-point-on-domain"
        );
    }
}

#[test]
fn out_of_domain_values_match_direct_evaluation_and_slot_polynomials() {
    for log_height in 0..=5 {
        let (air, export, trace, publics) = recurrence(log_height);
        let height = trace.height();
        let fixed = export.layout.preprocessed.as_ref().unwrap();
        for (name, trace, publics) in cases(&trace, &publics) {
            let view = bind(&export, height, &publics);
            let (polynomials, width) = view.coefficient_inputs(&trace).unwrap();
            let on_domain = view
                .row_inputs(&trace, SelectorLaw::TwoAdicLagrange)
                .unwrap();
            let g = generator(log_height);
            for row in 0..height {
                for slot in 0..export.slots.len() {
                    let value = horner(
                        &polynomials[slot * width..(slot + 1) * width],
                        Ext8::from(g.exp_u64(row as u64)),
                    );
                    assert_eq!(
                        value,
                        Ext8::from(on_domain[row * export.slots.len() + slot]),
                        "{name} row {row} slot {slot}"
                    );
                }
            }
            for point in points() {
                let (main_current, main_next) =
                    open_table(&trace.values, trace.width(), point).unwrap();
                let (preprocessed_current, preprocessed_next) =
                    open_table(&fixed.values, fixed.width, point).unwrap();
                let openings = zkc_plonky3_air::Openings {
                    main_current,
                    main_next,
                    preprocessed_current,
                    preprocessed_next,
                };
                let inputs = view.point_inputs(point, &openings).unwrap();
                for (slot, value) in inputs.iter().enumerate() {
                    assert_eq!(
                        horner(&polynomials[slot * width..(slot + 1) * width], point),
                        *value,
                        "{name} slot {slot}"
                    );
                }
                let adapter = export.arena.evaluate(|s| inputs[s]);
                let direct = point_residuals(&air, &trace, &publics, point).unwrap();
                assert_eq!(
                    adapter, direct,
                    "height {height}, {name}: out-of-domain residuals"
                );
            }
            let inside = Ext8::from(g);
            assert_eq!(
                point_residuals(&air, &trace, &publics, inside)
                    .unwrap_err()
                    .id,
                "plonky3-point-on-domain"
            );
            let empty = zkc_plonky3_air::Openings {
                main_current: vec![Ext8::ZERO; 4],
                main_next: vec![Ext8::ZERO; 4],
                preprocessed_current: vec![Ext8::ZERO],
                preprocessed_next: vec![Ext8::ZERO],
            };
            assert_eq!(
                view.point_inputs(inside, &empty).unwrap_err().id,
                "plonky3-point-on-domain"
            );
        }
    }
}

#[test]
fn cyclic_reads_wrap_and_a_finite_reading_would_accept_a_rejected_trace() {
    let unguarded = CounterAir { guarded: false };
    let guarded = CounterAir { guarded: true };
    for height in [1, 2, 8, 32] {
        let trace = CounterAir::generate(height);
        for (air, expected) in [(&unguarded, vec![(height - 1, 0)]), (&guarded, vec![])] {
            let export = zkc_plonky3_air::export(air, "counter").unwrap();
            let view = bind(&export, height, &[]);
            let residuals =
                view.residuals(&view.row_inputs(&trace, SelectorLaw::RowIndicator).unwrap());
            assert_eq!(upstream_failures(air, &trace, &[]), expected);
            assert_eq!(violations(&residuals, 1), expected);
            // Without wraparound, only rows with a successor are checked.
            assert!(residuals[..height - 1].iter().all(|r| *r == F::ZERO));
        }
    }
    // The recurrence's last-row constraint reads row zero through the wrap.
    let (air, export, trace, publics) = recurrence(3);
    let mutated = perturb(&trace, 0, 0);
    let view = bind(&export, 8, &publics);
    let residuals = view.residuals(
        &view
            .row_inputs(&mutated, SelectorLaw::RowIndicator)
            .unwrap(),
    );
    assert!(violations(&residuals, 9).contains(&(7, 8)));
    assert_eq!(
        violations(&residuals, 9),
        upstream_failures(&air, &mutated, &publics)
    );
}

#[test]
fn guard_products_negations_and_bare_selectors_are_admitted() {
    use p3_air::{Air, AirBuilder, BaseAir, WindowAccess};
    struct Guards;
    impl<T> BaseAir<T> for Guards {
        fn width(&self) -> usize {
            1
        }
    }
    impl<AB: AirBuilder> Air<AB> for Guards {
        fn eval(&self, builder: &mut AB) {
            let x: AB::Expr = builder.main().current_slice()[0].into();
            let (first, last, transition) = (
                builder.is_first_row(),
                builder.is_last_row(),
                builder.is_transition(),
            );
            builder.assert_zero(first.clone() * last.clone() * (x.clone() - AB::Expr::TWO));
            builder.assert_zero(-(transition.clone() * x.clone()));
            builder.assert_zero(transition.clone() * transition * (x.clone() + AB::Expr::NEG_ONE));
            builder.assert_zero(last * x);
        }
    }
    let export = zkc_plonky3_air::export(&Guards, "guards").unwrap();
    assert_eq!(
        export.assertions[0].selectors,
        [SelectorKind::FirstRow, SelectorKind::LastRow]
    );
    for height in [1, 2, 4, 8] {
        for trace in [
            RowMajorMatrix::new(vec![F::ZERO; height], 1),
            RowMajorMatrix::new(vec![F::TWO; height], 1),
            RowMajorMatrix::new((0..height as u32).map(F::from_u32).collect(), 1),
        ] {
            let view = bind(&export, height, &[]);
            let row_law =
                view.residuals(&view.row_inputs(&trace, SelectorLaw::RowIndicator).unwrap());
            let point_law = view.residuals(
                &view
                    .row_inputs(&trace, SelectorLaw::TwoAdicLagrange)
                    .unwrap(),
            );
            assert_eq!(
                violations(&row_law, 4),
                upstream_failures(&Guards, &trace, &[])
            );
            assert_eq!(violations(&row_law, 4), violations(&point_law, 4));
            assert_eq!(
                point_law,
                row_residuals(&Guards, &trace, &[], SelectorLaw::TwoAdicLagrange).unwrap()
            );
        }
    }
}

#[test]
fn a_selector_outside_guard_position_has_different_zero_loci_under_the_two_laws() {
    use zkc_plonky3_air_client::refused::{SelectorMisuse, SelectorMisuseAir};
    let air = SelectorMisuseAir(SelectorMisuse::AddedFirstRow);
    assert_eq!(
        zkc_plonky3_air::export(&air, "misuse").unwrap_err().id,
        "plonky3-selector-not-guard"
    );
    let height = 8;
    let mut debug_valid = vec![F::ZERO; height];
    debug_valid[0] = F::NEG_ONE;
    let mut stark_valid = vec![F::ZERO; height];
    stark_valid[0] = -F::from_u32(height as u32);
    let debug_valid = RowMajorMatrix::new(debug_valid, 1);
    let stark_valid = RowMajorMatrix::new(stark_valid, 1);
    assert!(upstream_accepts(&air, &debug_valid, &[]));
    assert!(!upstream_accepts(&air, &stark_valid, &[]));
    let point_law =
        |t: &RowMajorMatrix<F>| row_residuals(&air, t, &[], SelectorLaw::TwoAdicLagrange).unwrap();
    assert_eq!(violations(&point_law(&debug_valid), 1), [(0, 0)]);
    assert!(violations(&point_law(&stark_valid), 1).is_empty());
}

#[test]
fn a_large_trace_agrees_with_direct_evaluation_and_upstream() {
    let (air, export, trace, publics) = recurrence(16);
    let height = trace.height();
    let view = bind(&export, height, &publics);
    for (name, trace) in [
        ("honest", trace.clone()),
        ("middle", perturb(&trace, height / 2, 1)),
    ] {
        let adapter = view.residuals(&view.row_inputs(&trace, SelectorLaw::RowIndicator).unwrap());
        assert_eq!(
            adapter,
            row_residuals(&air, &trace, &publics, SelectorLaw::RowIndicator).unwrap(),
            "{name}"
        );
        assert_eq!(
            violations(&adapter, 9),
            upstream_failures(&air, &trace, &publics),
            "{name}"
        );
    }
}
