cmake_minimum_required(VERSION 3.21)
# Each request starts in a fresh configure process, independent of the parent
# consumer's imported targets. LLVM-only clients also compile, link and run.
set(body)
set(options)
set(refusal)
set(llvm_components Support Contracts Program Relation Language)
if(MODE STREQUAL "required")
  set(body "add_library(Zkc::MissingComponent INTERFACE IMPORTED)\nfind_package(ZkcCompiler REQUIRED CONFIG COMPONENTS MissingComponent)\n")
  list(APPEND options -DCMAKE_DISABLE_FIND_PACKAGE_LLVM=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_MLIR=TRUE)
  set(refusal "Unknown ZkcCompiler component: MissingComponent")
elseif(MODE STREQUAL "optional" OR MODE STREQUAL "optional-native")
  set(optional MissingComponent)
  if(MODE STREQUAL "optional-native")
    set(optional IR)
  endif()
  list(APPEND options -DCMAKE_DISABLE_FIND_PACKAGE_MLIR=TRUE)
  set(body "find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS Program OPTIONAL_COMPONENTS ${optional})\nif(NOT ZkcCompiler_Program_FOUND OR ZkcCompiler_${optional}_FOUND OR TARGET Zkc::IR)\nmessage(FATAL_ERROR \"optional component affected Program\")\nendif()\n")
elseif(MODE IN_LIST llvm_components)
  string(TOLOWER "${MODE}" name)
  list(APPEND options -DCMAKE_DISABLE_FIND_PACKAGE_MLIR=TRUE)
  set(body "find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS ${MODE})\nif(NOT ZkcCompiler_${MODE}_FOUND OR TARGET Zkc::IR OR TARGET MLIR OR TARGET Zkc::Compiler OR TARGET Zkc::zkc-opt)\nmessage(FATAL_ERROR \"LLVM-only closure crossed a boundary\")\nendif()\nadd_executable(client \"${CONSUMER_SOURCE}/${name}.cpp\")\ntarget_link_libraries(client PRIVATE Zkc::${MODE})\n")
elseif(MODE STREQUAL "repeated")
  set(body [=[
set(CMAKE_DISABLE_FIND_PACKAGE_MLIR TRUE)
find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS Program)
get_target_property(before Zkc::Support INTERFACE_INCLUDE_DIRECTORIES)
find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS Program)
get_target_property(after Zkc::Support INTERFACE_INCLUDE_DIRECTORIES)
if(NOT before STREQUAL after OR TARGET Zkc::IR)
  message(FATAL_ERROR "repeat changed Program closure")
endif()
set(CMAKE_DISABLE_FIND_PACKAGE_MLIR FALSE)
find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS Compiler)
if(NOT TARGET Zkc::Compiler OR TARGET Zkc::Driver)
  message(FATAL_ERROR "expanding discovery changed Compiler ownership")
endif()
get_target_property(before Zkc::IR INTERFACE_INCLUDE_DIRECTORIES)
find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS Compiler)
get_target_property(after Zkc::IR INTERFACE_INCLUDE_DIRECTORIES)
if(NOT before STREQUAL after)
  message(FATAL_ERROR "repeat appended MLIR headers")
endif()
]=])
elseif(MODE STREQUAL "default" OR MODE STREQUAL "tools")
  set(request)
  if(MODE STREQUAL "tools")
    set(request "COMPONENTS Tools")
  endif()
  set(body "find_package(ZkcCompiler REQUIRED CONFIG ${request})\nforeach(tool zkc-compile zkc-opt zkc-tblgen)\nif(NOT TARGET Zkc::\${tool})\nmessage(FATAL_ERROR \"installed tool missing\")\nendif()\nendforeach()\n")
elseif(MODE STREQUAL "compiler")
  set(body [=[
find_package(ZkcCompiler REQUIRED CONFIG COMPONENTS Compiler)
if(NOT ZkcCompiler_Compiler_FOUND OR TARGET Zkc::Driver OR TARGET Zkc::zkc-opt)
  message(FATAL_ERROR "Compiler discovery imported CLI targets")
endif()
]=])
else()
  message(FATAL_ERROR "Unknown package test mode: ${MODE}")
endif()
if(MODE MATCHES "^(repeated|default|tools|compiler)$")
  # Standalone MLIR exports LLVM_VERSION; MLIR_VERSION is not universal.
  string(APPEND body [=[
foreach(variable MLIR_CMAKE_DIR MLIR_INCLUDE_DIRS MLIR_TABLEGEN_EXE
    MLIR_PDLL_TABLEGEN_EXE LLVM_CMAKE_DIR LLVM_INCLUDE_DIRS LLVM_DEFINITIONS
    LLVM_VERSION LLVM_PACKAGE_VERSION)
  if(NOT DEFINED ${variable})
    message(FATAL_ERROR "native discovery hid upstream variable: ${variable}")
  endif()
endforeach()
list(APPEND CMAKE_MODULE_PATH "${LLVM_CMAKE_DIR}" "${MLIR_CMAKE_DIR}")
include(TableGen)
include(AddLLVM)
include(AddMLIR)
if(NOT COMMAND mlir_tablegen OR NOT TARGET ${MLIR_TABLEGEN_EXE})
  message(FATAL_ERROR "native discovery did not expose upstream dialect build tools")
endif()
]=])
endif()
file(MAKE_DIRECTORY "${TEST_ROOT}")
file(WRITE "${TEST_ROOT}/CMakeLists.txt"
  "cmake_minimum_required(VERSION 3.21)\nproject(ComponentControl LANGUAGES C CXX)\n${body}")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_ROOT}" -B "${TEST_ROOT}/build"
  "-DZkcCompiler_DIR=${PACKAGE_DIR}" "-DMLIR_DIR=${MLIR_DIR}" "-DLLVM_DIR=${LLVM_DIR}"
  "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}" ${options}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(refusal)
  if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${refusal}")
    message(FATAL_ERROR "required refusal missing: ${output} ${error}")
  endif()
elseif(NOT result EQUAL 0)
  message(FATAL_ERROR "${MODE} discovery refused: ${output} ${error}")
endif()
if(MODE IN_LIST llvm_components)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_ROOT}/build" --parallel 4
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${MODE} failed to compile/link: ${output} ${error}")
  endif()
  execute_process(COMMAND "${TEST_ROOT}/build/client"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${MODE} client failed: ${output} ${error}")
  endif()
endif()
