// Arithmetic trace: N=8, packed width=32, MSB arity=5.
// Generated by evaluation/composable-libraries/source/build.py; edit that builder.
use zkc::algebra::{
  Field,
  Vector
};
use zkc::algebra;
use zkc::core;
use zkc::pcs::{
  Commitment,
  MultilinearOpening,
  OpeningState,
  Proof,
  ProverKey,
  VerifierKey
};
use zkc::pcs;
use zkc::poly::{
  Point,
  Polynomial,
  Round,
  Table
};
use zkc::poly;
use zkc::random::{
  Rng
};
use zkc::random;
fn DrawChallengeAlgorithm<F: domain Field>(coins: Rng<F>) -> (F::Element, Rng<F>) requires (
  Field(F)
) {
  [draw] let (value, after) = zkc::random::draw::<F>(coins);
  return (value, after);
}
fn EmptyPointAlgorithm<F: domain Field>() -> (Point<F>) requires (Field(F)) {
  let p = zkc::poly::empty_point::<F>();
  return (p);
}
fn AppendPointAlgorithm<F: domain Field>(p: Point<F>, r: F::Element) -> (Point<F>) requires (
  Field(F)
) {
  let next = zkc::poly::append_point::<F>(p, r);
  return (next);
}
fn CheckPublicMatricesAlgorithm<F: domain Field>(
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>,
  initial: F::Element,
  final: F::Element
) -> () requires (Field(F)) {
  // The application pins all entries to its intended relation. These checks
  // connect the two boundary coefficients to explicit statement scalars.
  let a_shape = zkc::algebra::vector_length_check::<F>(a) attributes ("1024");
  zkc::core::require(a_shape);
  let b_shape = zkc::algebra::vector_length_check::<F>(b) attributes ("1024");
  zkc::core::require(b_shape);
  let c_shape = zkc::algebra::vector_length_check::<F>(c) attributes ("1024");
  zkc::core::require(c_shape);
  let negative_initial = zkc::algebra::neg::<F>(initial);
  let negative_final = zkc::algebra::neg::<F>(final);
  let entry_initial = zkc::algebra::vector_at::<F>(a) attributes ("281");
  let entry_final = zkc::algebra::vector_at::<F>(a) attributes ("313");
  let initial_ok = zkc::algebra::equal::<F>(entry_initial, negative_initial);
  zkc::core::require(initial_ok);
  let final_ok = zkc::algebra::equal::<F>(entry_final, negative_final);
  zkc::core::require(final_ok);
  return ();
}
fn TraceProductsAlgorithm<F: domain Field>(
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>,
  z: Vector<F::Element>
) -> (Vector<F::Element>, Vector<F::Element>, Vector<F::Element>, Table<F>) requires (Field(F)) {
  let az = zkc::algebra::vector_matvec::<F>(a, z) attributes ("32", "32", "0");
  let bz = zkc::algebra::vector_matvec::<F>(b, z) attributes ("32", "32", "0");
  let cz = zkc::algebra::vector_matvec::<F>(c, z) attributes ("32", "32", "0");
  let original = zkc::algebra::vector_to_table::<F>(z);
  return (az, bz, cz, original);
}
fn CommitOriginalAlgorithm<C: domain Commitment>(
  key: ProverKey<C>,
  z: Table<C::ValueField>
) -> (Commitment<C>, OpeningState<C>) requires (MultilinearOpening(C)) {
  let (root, original) = zkc::pcs::commit::<C>(key, z);
  return (root, original);
}
fn CheckRootAlgorithm<C: domain Commitment>(root: Commitment<C>, expected: Commitment<C>) -> () requires (
  MultilinearOpening(C)
) {
  let ok = zkc::pcs::equal::<C>(root, expected);
  zkc::core::require(ok);
  return ();
}
fn OnePointAlgorithm<F: domain Field>() -> (Point<F>) requires (Field(F)) {
  let zero = zkc::algebra::constant::<F>() attributes ("0");
  let one = zkc::algebra::constant::<F>() attributes ("1");
  let p0 = zkc::poly::empty_point::<F>();
  let p1 = zkc::poly::append_point::<F>(p0, one);
  let p2 = zkc::poly::append_point::<F>(p1, one);
  let p3 = zkc::poly::append_point::<F>(p2, zero);
  let p4 = zkc::poly::append_point::<F>(p3, zero);
  let p5 = zkc::poly::append_point::<F>(p4, one);
  return (p5);
}
fn CheckOneAlgorithm<F: domain Field>(value: F::Element) -> () requires (Field(F)) {
  let one = zkc::algebra::constant::<F>() attributes ("1");
  let ok = zkc::algebra::equal::<F>(value, one);
  zkc::core::require(ok);
  return ();
}
fn OpenOriginalAlgorithm<C: domain Commitment>(
  original: OpeningState<C>,
  point: Point<C::PointField>
) -> (C::EvaluationField::Element, Proof<C>) requires (MultilinearOpening(C)) {
  // pcs.open borrows immutable original custody; it never opens fold scratch.
  let (value, proof) = zkc::pcs::open::<C>(original, point);
  return (value, proof);
}
fn CheckOpeningAlgorithm<C: domain Commitment>(
  key: VerifierKey<C>,
  root: Commitment<C>,
  point: Point<C::PointField>,
  value: C::EvaluationField::Element,
  proof: Proof<C>
) -> (C::EvaluationField::Element) requires (MultilinearOpening(C)) {
  let ok = zkc::pcs::check::<C>(key, root, point, value, proof);
  zkc::core::require(ok);
  return (value);
}
fn OuterEqualityAlgorithm<F: domain Field>(tau: Point<F>) -> (Vector<F::Element>) requires (
  Field(F)
) {
  let equality = zkc::poly::equality_weights::<F>(tau);
  return (equality);
}
fn ZeroClaimAlgorithm<F: domain Field>() -> (F::Element) requires (Field(F)) {
  let zero = zkc::algebra::constant::<F>() attributes ("0");
  return (zero);
}
fn CubicRoundAlgorithm<F: domain Field>(
  e: Vector<F::Element>,
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>
) -> (Polynomial<F>) requires (Field(F)) {
  // Sum the coefficients of (eL+X*de)*((aL+X*da)*(bL+X*db)-(cL+X*dc)).
  let (el, er) = zkc::algebra::vector_split::<F>(e);
  let (al, ar) = zkc::algebra::vector_split::<F>(a);
  let (bl, br) = zkc::algebra::vector_split::<F>(b);
  let (cl, cr) = zkc::algebra::vector_split::<F>(c);
  let de = zkc::algebra::vector_sub::<F>(er, el);
  let da = zkc::algebra::vector_sub::<F>(ar, al);
  let db = zkc::algebra::vector_sub::<F>(br, bl);
  let dc = zkc::algebra::vector_sub::<F>(cr, cl);
  let ab = zkc::algebra::vector_mul::<F>(al, bl);
  let p0 = zkc::algebra::vector_sub::<F>(ab, cl);
  let adb = zkc::algebra::vector_mul::<F>(al, db);
  let dab = zkc::algebra::vector_mul::<F>(da, bl);
  let cross = zkc::algebra::vector_add::<F>(adb, dab);
  let p1 = zkc::algebra::vector_sub::<F>(cross, dc);
  let q0 = zkc::algebra::vector_dot::<F>(el, p0);
  let q1_left = zkc::algebra::vector_dot::<F>(el, p1);
  let q1_right = zkc::algebra::vector_dot::<F>(de, p0);
  let q1 = zkc::algebra::add::<F>(q1_left, q1_right);
  // Reuse the quadratic product in both highest coefficients.
  let dadb = zkc::algebra::vector_mul::<F>(da, db);
  let q2_left = zkc::algebra::vector_dot::<F>(el, dadb);
  let q2_right = zkc::algebra::vector_dot::<F>(de, p1);
  let q2 = zkc::algebra::add::<F>(q2_left, q2_right);
  let q3 = zkc::algebra::vector_dot::<F>(de, dadb);
  let coefficients_empty = zkc::algebra::vector_empty::<F>();
  let coefficients_0 = zkc::algebra::vector_append::<F>(coefficients_empty, q0);
  let coefficients_1 = zkc::algebra::vector_append::<F>(coefficients_0, q1);
  let coefficients_2 = zkc::algebra::vector_append::<F>(coefficients_1, q2);
  let coefficients = zkc::algebra::vector_append::<F>(coefficients_2, q3);
  let q = zkc::poly::from_coefficients::<F>(coefficients);
  return (q);
}
fn CheckCubicBoundaryAlgorithm<F: domain Field>(q: Polynomial<F>, claim: F::Element) -> () requires (
  Field(F)
) {
  // A received polynomial is not degree bounded by its type. Check before drawing.
  let degree_ok = zkc::poly::degree_check::<F>(q) attributes ("3");
  zkc::core::require(degree_ok);
  let sum = zkc::poly::univariate_boundary::<F>(q);
  let claim_ok = zkc::algebra::equal::<F>(sum, claim);
  zkc::core::require(claim_ok);
  return ();
}
fn EvaluateCubicAlgorithm<F: domain Field>(q: Polynomial<F>, r: F::Element) -> (F::Element) requires (
  Field(F)
) {
  let value = zkc::poly::evaluate::<F>(q, r);
  return (value);
}
fn FoldOuterAlgorithm<F: domain Field>(
  e: Vector<F::Element>,
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>,
  r: F::Element
) -> (Vector<F::Element>, Vector<F::Element>, Vector<F::Element>, Vector<F::Element>) requires (
  Field(F)
) {
  let (el, er) = zkc::algebra::vector_split::<F>(e);
  let ed = zkc::algebra::vector_sub::<F>(er, el);
  let escaled = zkc::algebra::vector_scale::<F>(ed, r);
  let enext = zkc::algebra::vector_add::<F>(el, escaled);
  let (al, ar) = zkc::algebra::vector_split::<F>(a);
  let ad = zkc::algebra::vector_sub::<F>(ar, al);
  let ascaled = zkc::algebra::vector_scale::<F>(ad, r);
  let anext = zkc::algebra::vector_add::<F>(al, ascaled);
  let (bl, br) = zkc::algebra::vector_split::<F>(b);
  let bd = zkc::algebra::vector_sub::<F>(br, bl);
  let bscaled = zkc::algebra::vector_scale::<F>(bd, r);
  let bnext = zkc::algebra::vector_add::<F>(bl, bscaled);
  let (cl, cr) = zkc::algebra::vector_split::<F>(c);
  let cd = zkc::algebra::vector_sub::<F>(cr, cl);
  let cscaled = zkc::algebra::vector_scale::<F>(cd, r);
  let cnext = zkc::algebra::vector_add::<F>(cl, cscaled);
  return (enext, anext, bnext, cnext);
}
fn OuterValuesAlgorithm<F: domain Field>(
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>
) -> (F::Element, F::Element, F::Element) requires (Field(F)) {
  let a_shape = zkc::algebra::vector_length_check::<F>(a) attributes ("1");
  zkc::core::require(a_shape);
  let ar = zkc::algebra::vector_at::<F>(a) attributes ("0");
  let b_shape = zkc::algebra::vector_length_check::<F>(b) attributes ("1");
  zkc::core::require(b_shape);
  let br = zkc::algebra::vector_at::<F>(b) attributes ("0");
  let c_shape = zkc::algebra::vector_length_check::<F>(c) attributes ("1");
  zkc::core::require(c_shape);
  let cr = zkc::algebra::vector_at::<F>(c) attributes ("0");
  return (ar, br, cr);
}
fn CheckOuterTerminalAlgorithm<F: domain Field>(
  tau: Point<F>,
  r: Point<F>,
  a: F::Element,
  b: F::Element,
  c: F::Element,
  claim: F::Element
) -> () requires (Field(F)) {
  let tau_weights = zkc::poly::equality_weights::<F>(tau);
  let r_weights = zkc::poly::equality_weights::<F>(r);
  let equality = zkc::algebra::vector_dot::<F>(tau_weights, r_weights);
  let ab = zkc::algebra::mul::<F>(a, b);
  let residual = zkc::algebra::sub::<F>(ab, c);
  let expected = zkc::algebra::mul::<F>(equality, residual);
  let ok = zkc::algebra::equal::<F>(claim, expected);
  zkc::core::require(ok);
  return ();
}
fn MixClaimAlgorithm<F: domain Field>(
  a: F::Element,
  b: F::Element,
  c: F::Element,
  alpha: F::Element,
  beta: F::Element,
  gamma: F::Element
) -> (F::Element) requires (Field(F)) {
  let aa = zkc::algebra::mul::<F>(alpha, a);
  let bb = zkc::algebra::mul::<F>(beta, b);
  let cc = zkc::algebra::mul::<F>(gamma, c);
  let ab = zkc::algebra::add::<F>(aa, bb);
  let claim = zkc::algebra::add::<F>(ab, cc);
  return (claim);
}
fn MatrixContractionAlgorithm<F: domain Field>(
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>,
  r: Point<F>,
  alpha: F::Element,
  beta: F::Element,
  gamma: F::Element
) -> (Table<F>) requires (Field(F)) {
  let weights = zkc::poly::equality_weights::<F>(r);
  let ar = zkc::algebra::vector_matvec::<F>(a, weights) attributes ("32", "32", "1");
  let br = zkc::algebra::vector_matvec::<F>(b, weights) attributes ("32", "32", "1");
  let cr = zkc::algebra::vector_matvec::<F>(c, weights) attributes ("32", "32", "1");
  let aa = zkc::algebra::vector_scale::<F>(ar, alpha);
  let bb = zkc::algebra::vector_scale::<F>(br, beta);
  let cc = zkc::algebra::vector_scale::<F>(cr, gamma);
  let ab = zkc::algebra::vector_add::<F>(aa, bb);
  let mixed = zkc::algebra::vector_add::<F>(ab, cc);
  let table = zkc::algebra::vector_to_table::<F>(mixed);
  return (table);
}
fn ProductRoundAlgorithm<F: domain Field>(a: Table<F>, b: Table<F>) -> (Round<F>) requires (
  Field(F)
) {
  // The existing round type carries the bound two, unlike polynomial.
  let q = zkc::poly::product_round::<F>(a, b);
  return (q);
}
fn CheckQuadraticBoundaryAlgorithm<F: domain Field>(q: Round<F>, claim: F::Element) -> () requires (
  Field(F)
) {
  let sum = zkc::poly::boundary::<F>(q);
  let ok = zkc::algebra::equal::<F>(sum, claim);
  zkc::core::require(ok);
  return ();
}
fn EvaluateQuadraticAlgorithm<F: domain Field>(q: Round<F>, r: F::Element) -> (F::Element) requires (
  Field(F)
) {
  let value = zkc::poly::round_evaluate::<F>(q, r);
  return (value);
}
fn FoldProductAlgorithm<F: domain Field>(
  a: Table<F>,
  b: Table<F>,
  r: F::Element
) -> (Table<F>, Table<F>) requires (Field(F)) {
  // Use the existing table abstraction for logical MSB folding.
  let at = zkc::poly::r#fold::<F>(a, r);
  let bt = zkc::poly::r#fold::<F>(b, r);
  return (at, bt);
}
fn CheckMatrixTerminalAlgorithm<F: domain Field>(
  a: Vector<F::Element>,
  b: Vector<F::Element>,
  c: Vector<F::Element>,
  r: Point<F>,
  s: Point<F>,
  alpha: F::Element,
  beta: F::Element,
  gamma: F::Element,
  value: F::Element,
  claim: F::Element
) -> (bool) requires (Field(F)) {
  // Independently contract the SAME public matrices in the forward direction.
  let rw = zkc::poly::equality_weights::<F>(r);
  let sw = zkc::poly::equality_weights::<F>(s);
  let av = zkc::algebra::vector_matvec::<F>(a, sw) attributes ("32", "32", "0");
  let bv = zkc::algebra::vector_matvec::<F>(b, sw) attributes ("32", "32", "0");
  let cv = zkc::algebra::vector_matvec::<F>(c, sw) attributes ("32", "32", "0");
  let ars = zkc::algebra::vector_dot::<F>(rw, av);
  let brs = zkc::algebra::vector_dot::<F>(rw, bv);
  let crs = zkc::algebra::vector_dot::<F>(rw, cv);
  let aa = zkc::algebra::mul::<F>(alpha, ars);
  let bb = zkc::algebra::mul::<F>(beta, brs);
  let cc = zkc::algebra::mul::<F>(gamma, crs);
  let ab = zkc::algebra::add::<F>(aa, bb);
  let matrix_value = zkc::algebra::add::<F>(ab, cc);
  let expected = zkc::algebra::mul::<F>(matrix_value, value);
  let ok = zkc::algebra::equal::<F>(claim, expected);
  zkc::core::require(ok);
  return (ok);
}
protocol RandomPoint {
  roles (P, V);
  parameters (rounds);
  inputs (V coins: Rng<"bls12-381.fr">);
  outputs (P Point<"bls12-381.fr">, V Point<"bls12-381.fr">, V Rng<"bls12-381.fr">);
  local P: let pp = EmptyPoint();
  local V: let vp = EmptyPoint();
  loop [coordinates] rounds carry (p = pp, v = vp, random = coins) -> (p_end, v_end, after) {
    local V: let (r, next_random) = DrawChallenge(random);
    message coordinate: V(r) -> P(pr);
    local P: let next_p = AppendPoint(p, pr);
    local V: let next_v = AppendPoint(v, r);
    yield (next_p, next_v, next_random);
  }
  return (p_end, v_end, after);
}
protocol OriginalOpening {
  roles (P, V);
  inputs (
    P original: OpeningState<"multilinear.kzg.bls12-381/1">,
    P p_point: Point<"bls12-381.fr">,
    V vk: VerifierKey<"multilinear.kzg.bls12-381/1">,
    V root: Commitment<"multilinear.kzg.bls12-381/1">,
    V v_point: Point<"bls12-381.fr">
  );
  outputs (V "bls12-381.fr"::Element);
  local P: let (value, proof) = OpenOriginal(original, p_point);
  message evaluation: P(value) -> V(received_value);
  message original_opening: P(proof) -> V(received_proof);
  local V: let checked = CheckOpening(vk, root, v_point, received_value, received_proof);
  return (checked);
}
protocol CubicSumcheck {
  roles (P, V);
  parameters (rounds);
  inputs (
    P e: Vector<"bls12-381.fr"::Element>,
    P a: Vector<"bls12-381.fr"::Element>,
    P b: Vector<"bls12-381.fr"::Element>,
    P c: Vector<"bls12-381.fr"::Element>,
    V claim: "bls12-381.fr"::Element,
    V coins: Rng<"bls12-381.fr">
  );
  outputs (
    P Point<"bls12-381.fr">,
    V Point<"bls12-381.fr">,
    P "bls12-381.fr"::Element,
    P "bls12-381.fr"::Element,
    P "bls12-381.fr"::Element,
    V "bls12-381.fr"::Element,
    V Rng<"bls12-381.fr">
  );
  local P: let pp = EmptyPoint();
  local V: let vp = EmptyPoint();
  loop [outer_rounds] rounds carry (
    eq = e,
    av = a,
    bv = b,
    cv = c,
    p = pp,
    v = vp,
    current = claim,
    random = coins
  ) -> (e_end, a_end, b_end, c_end, p_end, v_end, claim_end, coins_end) {
    local P: let q = CubicRound(eq, av, bv, cv);
    message cubic_coefficients: P(q) -> V(received_q);
    local V: CheckCubicBoundary(received_q, current);
    local V: let (r, next_random) = DrawChallenge(random);
    local V: let next_claim = EvaluateCubic(received_q, r);
    message coordinate: V(r) -> P(pr);
    local P: let (next_e, next_a, next_b, next_c) = FoldOuter(eq, av, bv, cv, pr);
    local P: let next_p = AppendPoint(p, pr);
    local V: let next_v = AppendPoint(v, r);
    yield (next_e, next_a, next_b, next_c, next_p, next_v, next_claim, next_random);
  }
  local P: let (ar, br, cr) = OuterValues(a_end, b_end, c_end);
  return (p_end, v_end, ar, br, cr, claim_end, coins_end);
}
protocol ProductSumcheck {
  roles (P, V);
  parameters (rounds);
  inputs (
    P a: Table<"bls12-381.fr">,
    P b: Table<"bls12-381.fr">,
    V claim: "bls12-381.fr"::Element,
    V coins: Rng<"bls12-381.fr">
  );
  outputs (
    P Point<"bls12-381.fr">,
    V Point<"bls12-381.fr">,
    V "bls12-381.fr"::Element,
    V Rng<"bls12-381.fr">
  );
  local P: let pp = EmptyPoint();
  local V: let vp = EmptyPoint();
  loop [inner_rounds] rounds carry (
    av = a,
    bv = b,
    p = pp,
    v = vp,
    current = claim,
    random = coins
  ) -> (a_end, b_end, p_end, v_end, claim_end, coins_end) {
    local P: let q = ProductRound(av, bv);
    message quadratic_coefficients: P(q) -> V(received_q);
    local V: CheckQuadraticBoundary(received_q, current);
    local V: let (r, next_random) = DrawChallenge(random);
    local V: let next_claim = EvaluateQuadratic(received_q, r);
    message coordinate: V(r) -> P(pr);
    local P: let (next_a, next_b) = FoldProduct(av, bv, pr);
    local P: let next_p = AppendPoint(p, pr);
    local V: let next_v = AppendPoint(v, r);
    yield (next_a, next_b, next_p, next_v, next_claim, next_random);
  }
  return (p_end, v_end, claim_end, coins_end);
}
protocol ArithmeticTrace {
  roles (P, V);
  parameters (rounds);
  inputs (
    P pk: ProverKey<"multilinear.kzg.bls12-381/1">,
    P z: Vector<"bls12-381.fr"::Element>,
    P p_a: Vector<"bls12-381.fr"::Element>,
    P p_b: Vector<"bls12-381.fr"::Element>,
    P p_c: Vector<"bls12-381.fr"::Element>,
    P p_initial: "bls12-381.fr"::Element,
    P p_final: "bls12-381.fr"::Element,
    P p_context: Vector<"bls12-381.fr"::Element>,
    V vk: VerifierKey<"multilinear.kzg.bls12-381/1">,
    V expected_root: Commitment<"multilinear.kzg.bls12-381/1">,
    V a: Vector<"bls12-381.fr"::Element>,
    V b: Vector<"bls12-381.fr"::Element>,
    V c: Vector<"bls12-381.fr"::Element>,
    V initial: "bls12-381.fr"::Element,
    V final: "bls12-381.fr"::Element,
    V context: Vector<"bls12-381.fr"::Element>,
    V coins: Rng<"bls12-381.fr">
  );
  outputs (V bool, V Rng<"bls12-381.fr">);
  dependencies (
    tau: RandomPoint(rounds = rounds),
    outer: CubicSumcheck(rounds = rounds),
    inner: ProductSumcheck(rounds = rounds),
    opening: OriginalOpening()
  );
  local P: CheckPublicMatrices(p_a, p_b, p_c, p_initial, p_final);
  local V: CheckPublicMatrices(a, b, c, initial, final);
  local P: let (az, bz, cz, original_table) = TraceProducts(p_a, p_b, p_c, z);
  local P: let (root, original) = CommitOriginal(pk, original_table);
  message original_commitment: P(root) -> V(received_root);
  local V: CheckRoot(received_root, expected_root);
  local P: let one_p = OnePoint();
  local V: let one_v = OnePoint();
  // This opening is required even though the matrix has one*one=one.
  invoke [pin_one] opening(original, one_p, vk, received_root, one_v) -> (one_value);
  local V: CheckOne(one_value);
  invoke [draw_tau] tau(coins) -> (p_tau, v_tau, after_tau);
  local P: let equality = OuterEquality(p_tau);
  local V: let zero = ZeroClaim();
  invoke [outer_sumcheck] outer(
    equality,
    az,
    bz,
    cz,
    zero,
    after_tau
  ) -> (p_r, v_r, ar, br, cr, outer_claim, after_outer);
  message outer_a: P(ar) -> V(received_ar);
  message outer_b: P(br) -> V(received_br);
  message outer_c: P(cr) -> V(received_cr);
  local V: CheckOuterTerminal(v_tau, v_r, received_ar, received_br, received_cr, outer_claim);
  // Three fresh draws AFTER all outer values, never powers of one draw.
  local V: let (alpha, after_alpha) = DrawChallenge(after_outer);
  message batch_alpha: V(alpha) -> P(p_alpha);
  local V: let (beta, after_beta) = DrawChallenge(after_alpha);
  message batch_beta: V(beta) -> P(p_beta);
  local V: let (gamma, after_gamma) = DrawChallenge(after_beta);
  message batch_gamma: V(gamma) -> P(p_gamma);
  local V: let mixed_claim = MixClaim(received_ar, received_br, received_cr, alpha, beta, gamma);
  local P: let matrix_table = MatrixContraction(p_a, p_b, p_c, p_r, p_alpha, p_beta, p_gamma);
  invoke [inner_sumcheck] inner(
    matrix_table,
    original_table,
    mixed_claim,
    after_gamma
  ) -> (p_s, v_s, inner_claim, after_inner);
  invoke [open_original] opening(original, p_s, vk, received_root, v_s) -> (original_value);
  local V: let accepted = CheckMatrixTerminal(
    a,
    b,
    c,
    v_r,
    v_s,
    alpha,
    beta,
    gamma,
    original_value,
    inner_claim
  );
  return (accepted, after_inner);
}
instance tau: RandomPoint {
  parameters (rounds = 5);
  roles (P = P, V = V);
}
instance outer: CubicSumcheck {
  parameters (rounds = 5);
  roles (P = P, V = V);
}
instance inner: ProductSumcheck {
  parameters (rounds = 5);
  roles (P = P, V = V);
}
instance opening: OriginalOpening {
  roles (P = P, V = V);
}
instance trace: ArithmeticTrace {
  parameters (rounds = 5);
  dependencies (tau = tau, outer = outer, inner = inner, opening = opening);
  roles (P = P, V = V);
}
entry main = trace;
configure DrawChallenge = DrawChallengeAlgorithm(F = "bls12-381.fr");
configure EmptyPoint = EmptyPointAlgorithm(F = "bls12-381.fr");
configure AppendPoint = AppendPointAlgorithm(F = "bls12-381.fr");
configure CheckPublicMatrices = CheckPublicMatricesAlgorithm(F = "bls12-381.fr");
configure TraceProducts = TraceProductsAlgorithm(F = "bls12-381.fr");
configure CommitOriginal = CommitOriginalAlgorithm(C = "multilinear.kzg.bls12-381/1");
configure CheckRoot = CheckRootAlgorithm(C = "multilinear.kzg.bls12-381/1");
configure OnePoint = OnePointAlgorithm(F = "bls12-381.fr");
configure CheckOne = CheckOneAlgorithm(F = "bls12-381.fr");
configure OpenOriginal = OpenOriginalAlgorithm(C = "multilinear.kzg.bls12-381/1");
configure CheckOpening = CheckOpeningAlgorithm(C = "multilinear.kzg.bls12-381/1");
configure OuterEquality = OuterEqualityAlgorithm(F = "bls12-381.fr");
configure ZeroClaim = ZeroClaimAlgorithm(F = "bls12-381.fr");
configure CubicRound = CubicRoundAlgorithm(F = "bls12-381.fr");
configure CheckCubicBoundary = CheckCubicBoundaryAlgorithm(F = "bls12-381.fr");
configure EvaluateCubic = EvaluateCubicAlgorithm(F = "bls12-381.fr");
configure FoldOuter = FoldOuterAlgorithm(F = "bls12-381.fr");
configure OuterValues = OuterValuesAlgorithm(F = "bls12-381.fr");
configure CheckOuterTerminal = CheckOuterTerminalAlgorithm(F = "bls12-381.fr");
configure MixClaim = MixClaimAlgorithm(F = "bls12-381.fr");
configure MatrixContraction = MatrixContractionAlgorithm(F = "bls12-381.fr");
configure ProductRound = ProductRoundAlgorithm(F = "bls12-381.fr");
configure CheckQuadraticBoundary = CheckQuadraticBoundaryAlgorithm(F = "bls12-381.fr");
configure EvaluateQuadratic = EvaluateQuadraticAlgorithm(F = "bls12-381.fr");
configure FoldProduct = FoldProductAlgorithm(F = "bls12-381.fr");
configure CheckMatrixTerminal = CheckMatrixTerminalAlgorithm(F = "bls12-381.fr");
