// Transaction generated by evaluation/application-composition/transaction/build.py.
// Aggregated range: n=8 bits, m=2 values, IPA dimension=16, rounds=4.
// Generated by evaluation/composable-libraries/source/build.py; edit that builder.
use zkc::curve::{
  ScalarAction
};
use zkc::algebra::{
  Field,
  Vector
};
use zkc::algebra;
use zkc::core;
use zkc::curve;
use zkc::random::{
  Rng
};
use zkc::random;
fn DrawChallengeAlgorithm<F: domain Field>(coins: Rng<F>) -> (F::Element, Rng<F>) requires (
  Field(F)
) {
  [draw] let (value, after) = zkc::random::draw::<F>(coins);
  // field.inverse rejects zero at this source position; there is no retry.
  let inverse = zkc::algebra::inverse::<F>(value);
  return (value, after);
}
fn BothAlgorithm<>(a: bool, b: bool) -> (bool) {
  let ok = zkc::core::and(a, b);
  return (ok);
}
fn InverseNonzeroAlgorithm<F: domain Field>(x: F::Element) -> (F::Element) requires (Field(F)) {
  // Rejection is at this operation, without hidden resampling.
  let inverse = zkc::algebra::inverse::<F>(x);
  return (inverse);
}
fn CheckProofPointsAlgorithm<G: domain Group>(a: G::Element, b: G::Element) -> () requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let a_ok = zkc::curve::nonidentity::<G>(a);
  zkc::core::require(a_ok);
  let b_ok = zkc::curve::nonidentity::<G>(b);
  zkc::core::require(b_ok);
  return ();
}
fn ValueCommitmentsAlgorithm<G: domain Group>(
  values: Vector<G::Scalar::Element>,
  blinding: Vector<G::Scalar::Element>,
  base: G::Element,
  blind: G::Element
) -> (Vector<G::Element>) requires (ScalarAction(G), Field(G::Scalar)) {
  let values_shape = zkc::algebra::vector_length_check::<G::Scalar>(values) attributes ("2");
  zkc::core::require(values_shape);
  let blinding_shape = zkc::algebra::vector_length_check::<G::Scalar>(blinding) attributes ("2");
  zkc::core::require(blinding_shape);
  let empty = zkc::curve::empty::<G>();
  let v0 = zkc::algebra::vector_at::<G::Scalar>(values) attributes ("0");
  let gamma0 = zkc::algebra::vector_at::<G::Scalar>(blinding) attributes ("0");
  let value_point0 = zkc::curve::scale::<G>(base, v0);
  let blind_point0 = zkc::curve::scale::<G>(blind, gamma0);
  let commitment0 = zkc::curve::add::<G>(value_point0, blind_point0);
  let ordered0 = zkc::curve::append::<G>(empty, commitment0);
  let v1 = zkc::algebra::vector_at::<G::Scalar>(values) attributes ("1");
  let gamma1 = zkc::algebra::vector_at::<G::Scalar>(blinding) attributes ("1");
  let value_point1 = zkc::curve::scale::<G>(base, v1);
  let blind_point1 = zkc::curve::scale::<G>(blind, gamma1);
  let commitment1 = zkc::curve::add::<G>(value_point1, blind_point1);
  let ordered1 = zkc::curve::append::<G>(ordered0, commitment1);
  return (ordered1);
}
fn CheckCommitmentsAlgorithm<G: domain Group>(
  actual: Vector<G::Element>,
  expected: Vector<G::Element>
) -> () requires (ScalarAction(G), Field(G::Scalar)) {
  let one = zkc::algebra::constant::<G::Scalar>() attributes ("1");
  let weights = zkc::algebra::vector_splat::<G::Scalar>(one) attributes ("2");
  // MSM checks exact group-vector length; curve.at alone would miss a suffix.
  let actual_sum = zkc::curve::msm::<G>(weights, actual);
  let expected_sum = zkc::curve::msm::<G>(weights, expected);
  let sum_ok = zkc::curve::equal::<G>(actual_sum, expected_sum);
  zkc::core::require(sum_ok);
  let actual0 = zkc::curve::at::<G>(actual) attributes ("0");
  let expected0 = zkc::curve::at::<G>(expected) attributes ("0");
  let ok0 = zkc::curve::equal::<G>(actual0, expected0);
  zkc::core::require(ok0);
  let actual1 = zkc::curve::at::<G>(actual) attributes ("1");
  let expected1 = zkc::curve::at::<G>(expected) attributes ("1");
  let ok1 = zkc::curve::equal::<G>(actual1, expected1);
  zkc::core::require(ok1);
  return ();
}
fn DrawVectorMasksAlgorithm<F: domain Field>(
  coins: Rng<F>
) -> (F::Element, F::Element, Vector<F::Element>, Vector<F::Element>, Rng<F>) requires (Field(F)) {
  // Global advancing tape: alpha, rho, sL[0..N), sR[0..N).
  let (alpha, after_alpha) = zkc::random::draw::<F>(coins);
  let (rho, after_rho) = zkc::random::draw::<F>(after_alpha);
  let (sl, after_sl) = zkc::random::vector::<F>(after_rho) attributes ("16");
  let (sr, after_sr) = zkc::random::vector::<F>(after_sl) attributes ("16");
  return (alpha, rho, sl, sr, after_sr);
}
fn DrawPolynomialMasksAlgorithm<F: domain Field>(coins: Rng<F>) -> (F::Element, F::Element, Rng<F>) requires (
  Field(F)
) {
  let (tau1, after_tau1) = zkc::random::draw::<F>(coins);
  let (tau2, after_tau2) = zkc::random::draw::<F>(after_tau1);
  return (tau1, tau2, after_tau2);
}
fn RangeCommitmentsAlgorithm<G: domain Group>(
  al: Vector<G::Scalar::Element>,
  sl: Vector<G::Scalar::Element>,
  sr: Vector<G::Scalar::Element>,
  alpha: G::Scalar::Element,
  rho: G::Scalar::Element,
  g: Vector<G::Element>,
  h: Vector<G::Element>,
  blind: G::Element
) -> (Vector<G::Scalar::Element>, G::Element, G::Element) requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let one = zkc::algebra::constant::<G::Scalar>() attributes ("1");
  let ones = zkc::algebra::vector_splat::<G::Scalar>(one) attributes ("16");
  let ar = zkc::algebra::vector_sub::<G::Scalar>(al, ones);
  let alg = zkc::curve::msm::<G>(al, g);
  let arh = zkc::curve::msm::<G>(ar, h);
  let ab = zkc::curve::scale::<G>(blind, alpha);
  let a_vectors = zkc::curve::add::<G>(alg, arh);
  let a = zkc::curve::add::<G>(a_vectors, ab);
  let slg = zkc::curve::msm::<G>(sl, g);
  let srh = zkc::curve::msm::<G>(sr, h);
  let rb = zkc::curve::scale::<G>(blind, rho);
  let s_vectors = zkc::curve::add::<G>(slg, srh);
  let s = zkc::curve::add::<G>(s_vectors, rb);
  return (ar, a, s);
}
fn RangePolynomialsAlgorithm<F: domain Field>(
  al: Vector<F::Element>,
  ar: Vector<F::Element>,
  sl: Vector<F::Element>,
  sr: Vector<F::Element>,
  y: F::Element,
  z: F::Element
) -> (
  Vector<F::Element>,
  Vector<F::Element>,
  Vector<F::Element>,
  Vector<F::Element>,
  F::Element,
  F::Element
) requires (Field(F)) {
  let two = zkc::algebra::constant::<F>() attributes ("2");
  let ys = zkc::algebra::vector_powers::<F>(y) attributes ("16");
  let zs = zkc::algebra::vector_powers::<F>(z) attributes ("4");
  let z_weights = zkc::algebra::vector_gather::<F>(zs) attributes ("2", "3");
  let twos = zkc::algebra::vector_powers::<F>(two) attributes ("8");
  // Party-major i=j*n+b: d_i = z^(j+2)*2^b.
  let d = zkc::algebra::vector_kronecker::<F>(z_weights, twos);
  let z_vector = zkc::algebra::vector_splat::<F>(z) attributes ("16");
  let l0 = zkc::algebra::vector_sub::<F>(al, z_vector);
  let ar_z = zkc::algebra::vector_add::<F>(ar, z_vector);
  let y_ar_z = zkc::algebra::vector_mul::<F>(ys, ar_z);
  let r0 = zkc::algebra::vector_add::<F>(y_ar_z, d);
  let r1 = zkc::algebra::vector_mul::<F>(ys, sr);
  let t1a = zkc::algebra::vector_dot::<F>(sl, r0);
  let t1b = zkc::algebra::vector_dot::<F>(l0, r1);
  let t1 = zkc::algebra::add::<F>(t1a, t1b);
  let t2 = zkc::algebra::vector_dot::<F>(sl, r1);
  return (l0, r0, r1, z_weights, t1, t2);
}
fn PolynomialCommitmentsAlgorithm<G: domain Group>(
  t1: G::Scalar::Element,
  t2: G::Scalar::Element,
  tau1: G::Scalar::Element,
  tau2: G::Scalar::Element,
  base: G::Element,
  blind: G::Element
) -> (G::Element, G::Element) requires (ScalarAction(G), Field(G::Scalar)) {
  let t1b = zkc::curve::scale::<G>(base, t1);
  let tau1b = zkc::curve::scale::<G>(blind, tau1);
  let first = zkc::curve::add::<G>(t1b, tau1b);
  let t2b = zkc::curve::scale::<G>(base, t2);
  let tau2b = zkc::curve::scale::<G>(blind, tau2);
  let second = zkc::curve::add::<G>(t2b, tau2b);
  return (first, second);
}
fn RangeResponsesAlgorithm<F: domain Field>(
  l0: Vector<F::Element>,
  sl: Vector<F::Element>,
  r0: Vector<F::Element>,
  r1: Vector<F::Element>,
  z_weights: Vector<F::Element>,
  blinding: Vector<F::Element>,
  alpha: F::Element,
  rho: F::Element,
  tau1: F::Element,
  tau2: F::Element,
  x: F::Element
) -> (Vector<F::Element>, Vector<F::Element>, F::Element, F::Element, F::Element) requires (
  Field(F)
) {
  let xsl = zkc::algebra::vector_scale::<F>(sl, x);
  let xr1 = zkc::algebra::vector_scale::<F>(r1, x);
  let l = zkc::algebra::vector_add::<F>(l0, xsl);
  let r = zkc::algebra::vector_add::<F>(r0, xr1);
  let tx = zkc::algebra::vector_dot::<F>(l, r);
  let x2 = zkc::algebra::mul::<F>(x, x);
  let xtau1 = zkc::algebra::mul::<F>(x, tau1);
  let x2tau2 = zkc::algebra::mul::<F>(x2, tau2);
  let value_blindings = zkc::algebra::vector_dot::<F>(z_weights, blinding);
  let poly_blindings = zkc::algebra::add::<F>(xtau1, x2tau2);
  let tau = zkc::algebra::add::<F>(poly_blindings, value_blindings);
  let xrho = zkc::algebra::mul::<F>(x, rho);
  let mu = zkc::algebra::add::<F>(alpha, xrho);
  return (l, r, tx, tau, mu);
}
fn CheckRangeEquationAlgorithm<G: domain Group>(
  commitments: Vector<G::Element>,
  base: G::Element,
  blind: G::Element,
  t1: G::Element,
  t2: G::Element,
  y: G::Scalar::Element,
  z: G::Scalar::Element,
  x: G::Scalar::Element,
  tx: G::Scalar::Element,
  tau: G::Scalar::Element
) -> (bool) requires (ScalarAction(G), Field(G::Scalar)) {
  let two = zkc::algebra::constant::<G::Scalar>() attributes ("2");
  let ys = zkc::algebra::vector_powers::<G::Scalar>(y) attributes ("16");
  let sum_y = zkc::algebra::vector_sum::<G::Scalar>(ys);
  let twos = zkc::algebra::vector_powers::<G::Scalar>(two) attributes ("8");
  let sum_two = zkc::algebra::vector_sum::<G::Scalar>(twos);
  let zs = zkc::algebra::vector_powers::<G::Scalar>(z) attributes ("5");
  let delta_zs = zkc::algebra::vector_gather::<G::Scalar>(zs) attributes ("3", "4");
  let sum_z = zkc::algebra::vector_sum::<G::Scalar>(delta_zs);
  let z_weights = zkc::algebra::vector_gather::<G::Scalar>(zs) attributes ("2", "3");
  let z2 = zkc::algebra::mul::<G::Scalar>(z, z);
  let z_minus_z2 = zkc::algebra::sub::<G::Scalar>(z, z2);
  let delta_left = zkc::algebra::mul::<G::Scalar>(z_minus_z2, sum_y);
  let delta_right = zkc::algebra::mul::<G::Scalar>(sum_z, sum_two);
  // Finite power sums: y=1 remains valid, with no inverse of y-1.
  let delta = zkc::algebra::sub::<G::Scalar>(delta_left, delta_right);
  let values = zkc::curve::msm::<G>(z_weights, commitments);
  let delta_b = zkc::curve::scale::<G>(base, delta);
  let xt1 = zkc::curve::scale::<G>(t1, x);
  let x2 = zkc::algebra::mul::<G::Scalar>(x, x);
  let x2t2 = zkc::curve::scale::<G>(t2, x2);
  let rhs0 = zkc::curve::add::<G>(values, delta_b);
  let rhs1 = zkc::curve::add::<G>(rhs0, xt1);
  let rhs = zkc::curve::add::<G>(rhs1, x2t2);
  let txb = zkc::curve::scale::<G>(base, tx);
  let taub = zkc::curve::scale::<G>(blind, tau);
  let lhs = zkc::curve::add::<G>(txb, taub);
  let range_ok = zkc::curve::equal::<G>(lhs, rhs);
  zkc::core::require(range_ok);
  return (range_ok);
}
fn RangeParentAlgorithm<G: domain Group>(
  a: G::Element,
  s: G::Element,
  g: Vector<G::Element>,
  h: Vector<G::Element>,
  base: G::Element,
  blind: G::Element,
  y: G::Scalar::Element,
  z: G::Scalar::Element,
  x: G::Scalar::Element,
  w: G::Scalar::Element,
  tx: G::Scalar::Element,
  mu: G::Scalar::Element
) -> (G::Element, G::Element, Vector<G::Scalar::Element>) requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let two = zkc::algebra::constant::<G::Scalar>() attributes ("2");
  let inverse_y = zkc::algebra::inverse::<G::Scalar>(y);
  let factors = zkc::algebra::vector_powers::<G::Scalar>(inverse_y) attributes ("16");
  let ys = zkc::algebra::vector_powers::<G::Scalar>(y) attributes ("16");
  let zs = zkc::algebra::vector_powers::<G::Scalar>(z) attributes ("4");
  let z_weights = zkc::algebra::vector_gather::<G::Scalar>(zs) attributes ("2", "3");
  let twos = zkc::algebra::vector_powers::<G::Scalar>(two) attributes ("8");
  let d = zkc::algebra::vector_kronecker::<G::Scalar>(z_weights, twos);
  let zy = zkc::algebra::vector_scale::<G::Scalar>(ys, z);
  let h_weights = zkc::algebra::vector_add::<G::Scalar>(zy, d);
  // This parent contraction is an actual single-use scale_each -> msm pair.
  let h_prime = zkc::curve::scale_each::<G>(factors, h);
  let h_term = zkc::curve::msm::<G>(h_weights, h_prime);
  let negative_z = zkc::algebra::neg::<G::Scalar>(z);
  let g_weights = zkc::algebra::vector_splat::<G::Scalar>(negative_z) attributes ("16");
  let g_term = zkc::curve::msm::<G>(g_weights, g);
  let xs = zkc::curve::scale::<G>(s, x);
  let negative_mu = zkc::algebra::neg::<G::Scalar>(mu);
  let mu_term = zkc::curve::scale::<G>(blind, negative_mu);
  let q = zkc::curve::scale::<G>(base, w);
  let txq = zkc::curve::scale::<G>(q, tx);
  let p0 = zkc::curve::add::<G>(a, xs);
  let p1 = zkc::curve::add::<G>(p0, g_term);
  let p2 = zkc::curve::add::<G>(p1, h_term);
  let p3 = zkc::curve::add::<G>(p2, mu_term);
  let parent = zkc::curve::add::<G>(p3, txq);
  return (parent, q, factors);
}
fn PrepareIPAAlgorithm<G: domain Group>(
  a: Vector<G::Scalar::Element>,
  b: Vector<G::Scalar::Element>,
  g: Vector<G::Element>,
  h: Vector<G::Element>,
  factors: Vector<G::Scalar::Element>,
  q: G::Element,
  parent: G::Element
) -> (Vector<G::Element>) requires (ScalarAction(G), Field(G::Scalar)) {
  // Materialize actual prover bases. This result escapes to recursive folds.
  let h_prime = zkc::curve::scale_each::<G>(factors, h);
  let a_g = zkc::curve::msm::<G>(a, g);
  let b_h = zkc::curve::msm::<G>(b, h_prime);
  let ab = zkc::algebra::vector_dot::<G::Scalar>(a, b);
  let ab_q = zkc::curve::scale::<G>(q, ab);
  let vectors = zkc::curve::add::<G>(a_g, b_h);
  let expected = zkc::curve::add::<G>(vectors, ab_q);
  let ok = zkc::curve::equal::<G>(parent, expected);
  zkc::core::require(ok);
  return (h_prime);
}
fn IPACrossTermsAlgorithm<G: domain Group>(
  a: Vector<G::Scalar::Element>,
  b: Vector<G::Scalar::Element>,
  g: Vector<G::Element>,
  h: Vector<G::Element>,
  q: G::Element
) -> (G::Element, G::Element) requires (ScalarAction(G), Field(G::Scalar)) {
  let (al, ar) = zkc::algebra::vector_split::<G::Scalar>(a);
  let (bl, br) = zkc::algebra::vector_split::<G::Scalar>(b);
  let (gl, gr) = zkc::curve::split::<G>(g);
  let (hl, hr) = zkc::curve::split::<G>(h);
  let al_gr = zkc::curve::msm::<G>(al, gr);
  let br_hl = zkc::curve::msm::<G>(br, hl);
  let al_br = zkc::algebra::vector_dot::<G::Scalar>(al, br);
  let lq = zkc::curve::scale::<G>(q, al_br);
  let lv = zkc::curve::add::<G>(al_gr, br_hl);
  let left = zkc::curve::add::<G>(lv, lq);
  let ar_gl = zkc::curve::msm::<G>(ar, gl);
  let bl_hr = zkc::curve::msm::<G>(bl, hr);
  let ar_bl = zkc::algebra::vector_dot::<G::Scalar>(ar, bl);
  let rq = zkc::curve::scale::<G>(q, ar_bl);
  let rv = zkc::curve::add::<G>(ar_gl, bl_hr);
  let right = zkc::curve::add::<G>(rv, rq);
  return (left, right);
}
fn FoldIPAAlgorithm<G: domain Group>(
  a: Vector<G::Scalar::Element>,
  b: Vector<G::Scalar::Element>,
  g: Vector<G::Element>,
  h: Vector<G::Element>,
  u: G::Scalar::Element
) -> (
  Vector<G::Scalar::Element>,
  Vector<G::Scalar::Element>,
  Vector<G::Element>,
  Vector<G::Element>
) requires (ScalarAction(G), Field(G::Scalar)) {
  let inverse = zkc::algebra::inverse::<G::Scalar>(u);
  let (al, ar) = zkc::algebra::vector_split::<G::Scalar>(a);
  let (bl, br) = zkc::algebra::vector_split::<G::Scalar>(b);
  let (gl, gr) = zkc::curve::split::<G>(g);
  let (hl, hr) = zkc::curve::split::<G>(h);
  let ual = zkc::algebra::vector_scale::<G::Scalar>(al, u);
  let iar = zkc::algebra::vector_scale::<G::Scalar>(ar, inverse);
  let next_a = zkc::algebra::vector_add::<G::Scalar>(ual, iar);
  let ibl = zkc::algebra::vector_scale::<G::Scalar>(bl, inverse);
  let ubr = zkc::algebra::vector_scale::<G::Scalar>(br, u);
  let next_b = zkc::algebra::vector_add::<G::Scalar>(ibl, ubr);
  let igl = zkc::curve::vector_scale::<G>(gl, inverse);
  let ugr = zkc::curve::vector_scale::<G>(gr, u);
  let next_g = zkc::curve::vector_add::<G>(igl, ugr);
  let uhl = zkc::curve::vector_scale::<G>(hl, u);
  let ihr = zkc::curve::vector_scale::<G>(hr, inverse);
  let next_h = zkc::curve::vector_add::<G>(uhl, ihr);
  return (next_a, next_b, next_g, next_h);
}
fn IPAWeightSeedAlgorithm<F: domain Field>() -> (Vector<F::Element>) requires (Field(F)) {
  let one = zkc::algebra::constant::<F>() attributes ("1");
  let seed = zkc::algebra::vector_splat::<F>(one) attributes ("1");
  return (seed);
}
fn FoldPublicIPAAlgorithm<G: domain Group>(
  parent: G::Element,
  left: G::Element,
  right: G::Element,
  u: G::Scalar::Element,
  g_weights: Vector<G::Scalar::Element>,
  h_weights: Vector<G::Scalar::Element>
) -> (G::Element, Vector<G::Scalar::Element>, Vector<G::Scalar::Element>) requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let inverse = zkc::algebra::inverse::<G::Scalar>(u);
  let u2 = zkc::algebra::mul::<G::Scalar>(u, u);
  let i2 = zkc::algebra::mul::<G::Scalar>(inverse, inverse);
  let u2l = zkc::curve::scale::<G>(left, u2);
  let i2r = zkc::curve::scale::<G>(right, i2);
  let p_left = zkc::curve::add::<G>(parent, u2l);
  let next_parent = zkc::curve::add::<G>(p_left, i2r);
  let g_pair_empty = zkc::algebra::vector_empty::<G::Scalar>();
  let g_pair_0 = zkc::algebra::vector_append::<G::Scalar>(g_pair_empty, inverse);
  let g_pair = zkc::algebra::vector_append::<G::Scalar>(g_pair_0, u);
  let h_pair_empty = zkc::algebra::vector_empty::<G::Scalar>();
  let h_pair_0 = zkc::algebra::vector_append::<G::Scalar>(h_pair_empty, u);
  let h_pair = zkc::algebra::vector_append::<G::Scalar>(h_pair_0, inverse);
  // Kronecker expands MSB-to-LSB weights in challenge order.
  let next_g = zkc::algebra::vector_kronecker::<G::Scalar>(g_weights, g_pair);
  let next_h = zkc::algebra::vector_kronecker::<G::Scalar>(h_weights, h_pair);
  return (next_parent, next_g, next_h);
}
fn IPATerminalScalarsAlgorithm<F: domain Field>(
  a: Vector<F::Element>,
  b: Vector<F::Element>
) -> (F::Element, F::Element) requires (Field(F)) {
  let a_shape = zkc::algebra::vector_length_check::<F>(a) attributes ("1");
  zkc::core::require(a_shape);
  let b_shape = zkc::algebra::vector_length_check::<F>(b) attributes ("1");
  zkc::core::require(b_shape);
  let a_final = zkc::algebra::vector_at::<F>(a) attributes ("0");
  let b_final = zkc::algebra::vector_at::<F>(b) attributes ("0");
  return (a_final, b_final);
}
fn CheckIPATerminalAlgorithm<G: domain Group>(
  parent: G::Element,
  q: G::Element,
  g: Vector<G::Element>,
  h: Vector<G::Element>,
  factors: Vector<G::Scalar::Element>,
  g_weights: Vector<G::Scalar::Element>,
  h_weights: Vector<G::Scalar::Element>,
  a: G::Scalar::Element,
  b: G::Scalar::Element
) -> (bool) requires (ScalarAction(G), Field(G::Scalar)) {
  let g_shape = zkc::algebra::vector_length_check::<G::Scalar>(g_weights) attributes ("16");
  zkc::core::require(g_shape);
  let h_shape = zkc::algebra::vector_length_check::<G::Scalar>(h_weights) attributes ("16");
  zkc::core::require(h_shape);
  let a_weights = zkc::algebra::vector_scale::<G::Scalar>(g_weights, a);
  let b_weights = zkc::algebra::vector_scale::<G::Scalar>(h_weights, b);
  let a_g = zkc::curve::msm::<G>(a_weights, g);
  // The SECOND actual verification contraction uses original H and y^-i.
  let h_prime = zkc::curve::scale_each::<G>(factors, h);
  let b_h = zkc::curve::msm::<G>(b_weights, h_prime);
  let ab = zkc::algebra::mul::<G::Scalar>(a, b);
  let ab_q = zkc::curve::scale::<G>(q, ab);
  let vectors = zkc::curve::add::<G>(a_g, b_h);
  let rhs = zkc::curve::add::<G>(vectors, ab_q);
  // parent already includes every u^2*L + u^-2*R. Never check tx=a*b.
  let ipa_ok = zkc::curve::equal::<G>(parent, rhs);
  zkc::core::require(ipa_ok);
  return (ipa_ok);
}
protocol InnerProductArgument {
  // This concrete profile requires nonidentity cross commitments, as in
  // the selected upstream range profile. Valid zero/sparse IPA relations
  // can be outside this profile; the compiler itself permits identity.
  roles (P, V);
  parameters (rounds);
  inputs (
    P a: Vector<"ristretto255.scalar"::Element>,
    P b: Vector<"ristretto255.scalar"::Element>,
    P p_g: Vector<"ristretto255.group"::Element>,
    P p_h: Vector<"ristretto255.group"::Element>,
    P p_factors: Vector<"ristretto255.scalar"::Element>,
    P p_q: "ristretto255.group"::Element,
    P p_parent: "ristretto255.group"::Element,
    V g: Vector<"ristretto255.group"::Element>,
    V h: Vector<"ristretto255.group"::Element>,
    V factors: Vector<"ristretto255.scalar"::Element>,
    V q: "ristretto255.group"::Element,
    V parent: "ristretto255.group"::Element,
    V coins: Rng<"ristretto255.scalar">
  );
  outputs (V bool, V Rng<"ristretto255.scalar">);
  local P: let h_prime = PrepareIPA(a, b, p_g, p_h, p_factors, p_q, p_parent);
  local V: let seed = IPAWeightSeed();
  loop [ipa_rounds] rounds carry (
    av = a,
    bv = b,
    gv = p_g,
    hv = h_prime,
    current_parent = parent,
    gw = seed,
    hw = seed,
    random = coins
  ) capture (p_q) -> (a_end, b_end, g_end, h_end, parent_end, gw_end, hw_end, after) {
    local P: let (left, right) = IPACrossTerms(av, bv, gv, hv, p_q);
    local P: CheckProofPoints(left, right);
    message ipa_left: P(left) -> V(received_left);
    message ipa_right: P(right) -> V(received_right);
    local V: CheckProofPoints(received_left, received_right);
    local V: let (u, next_random) = DrawChallenge(random);
    message ipa_challenge: V(u) -> P(p_u);
    local P: let (next_a, next_b, next_g, next_h) = FoldIPA(av, bv, gv, hv, p_u);
    local V: let (next_parent, next_gw, next_hw) = FoldPublicIPA(
      current_parent,
      received_left,
      received_right,
      u,
      gw,
      hw
    );
    yield (next_a, next_b, next_g, next_h, next_parent, next_gw, next_hw, next_random);
  }
  local P: let (a_final, b_final) = IPATerminalScalars(a_end, b_end);
  message ipa_terminal_a: P(a_final) -> V(received_a);
  message ipa_terminal_b: P(b_final) -> V(received_b);
  local V: let accepted = CheckIPATerminal(
    parent_end,
    q,
    g,
    h,
    factors,
    gw_end,
    hw_end,
    received_a,
    received_b
  );
  return (accepted, after);
}
protocol AggregatedRange {
  roles (P, V);
  parameters (rounds);
  inputs (
    P values: Vector<"ristretto255.scalar"::Element>,
    P blinding: Vector<"ristretto255.scalar"::Element>,
    P bits: Vector<"ristretto255.scalar"::Element>,
    P entropy: Rng<"ristretto255.scalar">,
    P p_g: Vector<"ristretto255.group"::Element>,
    P p_h: Vector<"ristretto255.group"::Element>,
    P p_base: "ristretto255.group"::Element,
    P p_blind: "ristretto255.group"::Element,
    P p_commitments: Vector<"ristretto255.group"::Element>,
    P p_context: Vector<"ristretto255.scalar"::Element>,
    V g: Vector<"ristretto255.group"::Element>,
    V h: Vector<"ristretto255.group"::Element>,
    V base: "ristretto255.group"::Element,
    V blind: "ristretto255.group"::Element,
    V commitments: Vector<"ristretto255.group"::Element>,
    V context: Vector<"ristretto255.scalar"::Element>,
    V coins: Rng<"ristretto255.scalar">
  );
  outputs (V bool, V Rng<"ristretto255.scalar">, P Rng<"ristretto255.scalar">);
  dependencies (ipa: InnerProductArgument(rounds = rounds));
  // Commitment identity is pinned point-by-point in the given public order.
  local P: CheckProofPoints(p_base, p_blind);
  local V: CheckProofPoints(base, blind);
  local P: let value_commitments = ValueCommitments(values, blinding, p_base, p_blind);
  local P: CheckCommitments(value_commitments, p_commitments);
  message ordered_commitments: P(value_commitments) -> V(received_commitments);
  local V: CheckCommitments(received_commitments, commitments);
  local P: let (alpha, rho, sl, sr, after_vectors) = DrawVectorMasks(entropy);
  local P: let (ar, a, s) = RangeCommitments(bits, sl, sr, alpha, rho, p_g, p_h, p_blind);
  local P: CheckProofPoints(a, s);
  message range_a: P(a) -> V(received_a);
  message range_s: P(s) -> V(received_s);
  local V: CheckProofPoints(received_a, received_s);
  local V: let (y, after_y) = DrawChallenge(coins);
  message range_y: V(y) -> P(p_y);
  local P: let inverse_y = InverseNonzero(p_y);
  local V: let (z, after_z) = DrawChallenge(after_y);
  message range_z: V(z) -> P(p_z);
  local P: let inverse_z = InverseNonzero(p_z);
  local P: let (l0, r0, r1, z_weights, t1, t2) = RangePolynomials(bits, ar, sl, sr, p_y, p_z);
  local P: let (tau1, tau2, after_masks) = DrawPolynomialMasks(after_vectors);
  local P: let (first, second) = PolynomialCommitments(t1, t2, tau1, tau2, p_base, p_blind);
  local P: CheckProofPoints(first, second);
  message range_t1: P(first) -> V(received_first);
  message range_t2: P(second) -> V(received_second);
  local V: CheckProofPoints(received_first, received_second);
  local V: let (x, after_x) = DrawChallenge(after_z);
  message range_x: V(x) -> P(p_x);
  local P: let inverse_x = InverseNonzero(p_x);
  local P: let (l, r, tx, tau, mu) = RangeResponses(
    l0,
    sl,
    r0,
    r1,
    z_weights,
    blinding,
    alpha,
    rho,
    tau1,
    tau2,
    p_x
  );
  message range_tx: P(tx) -> V(received_tx);
  message range_tau: P(tau) -> V(received_tau);
  message range_mu: P(mu) -> V(received_mu);
  local V: let (w, after_w) = DrawChallenge(after_x);
  message range_w: V(w) -> P(p_w);
  local P: let inverse_w = InverseNonzero(p_w);
  // The range equation and the IPA equation are separate required checks.
  local V: let range_ok = CheckRangeEquation(
    received_commitments,
    base,
    blind,
    received_first,
    received_second,
    y,
    z,
    x,
    received_tx,
    received_tau
  );
  local P: let (p_parent, p_q, p_factors) = RangeParent(
    a,
    s,
    p_g,
    p_h,
    p_base,
    p_blind,
    p_y,
    p_z,
    p_x,
    p_w,
    tx,
    mu
  );
  local V: let (parent, q, factors) = RangeParent(
    received_a,
    received_s,
    g,
    h,
    base,
    blind,
    y,
    z,
    x,
    w,
    received_tx,
    received_mu
  );
  // No message or entry port can replace the computed validator parent.
  invoke [range_ipa] ipa(
    l,
    r,
    p_g,
    p_h,
    p_factors,
    p_q,
    p_parent,
    g,
    h,
    factors,
    q,
    parent,
    after_w
  ) -> (ipa_ok, after_ipa);
  local V: let accepted = Both(range_ok, ipa_ok);
  return (accepted, after_ipa, after_masks);
}
instance ipa: InnerProductArgument {
  parameters (rounds = 4);
  roles (P = P, V = V);
}
instance range: AggregatedRange {
  parameters (rounds = 4);
  dependencies (ipa = ipa);
  roles (P = P, V = V);
}
configure DrawChallenge = DrawChallengeAlgorithm(F = "ristretto255.scalar");
configure Both = BothAlgorithm();
configure InverseNonzero = InverseNonzeroAlgorithm(F = "ristretto255.scalar");
configure CheckProofPoints = CheckProofPointsAlgorithm(G = "ristretto255.group");
configure ValueCommitments = ValueCommitmentsAlgorithm(G = "ristretto255.group");
configure CheckCommitments = CheckCommitmentsAlgorithm(G = "ristretto255.group");
configure DrawVectorMasks = DrawVectorMasksAlgorithm(F = "ristretto255.scalar");
configure DrawPolynomialMasks = DrawPolynomialMasksAlgorithm(F = "ristretto255.scalar");
configure RangeCommitments = RangeCommitmentsAlgorithm(G = "ristretto255.group");
configure RangePolynomials = RangePolynomialsAlgorithm(F = "ristretto255.scalar");
configure PolynomialCommitments = PolynomialCommitmentsAlgorithm(G = "ristretto255.group");
configure RangeResponses = RangeResponsesAlgorithm(F = "ristretto255.scalar");
configure CheckRangeEquation = CheckRangeEquationAlgorithm(G = "ristretto255.group");
configure RangeParent = RangeParentAlgorithm(G = "ristretto255.group");
configure PrepareIPA = PrepareIPAAlgorithm(G = "ristretto255.group");
configure IPACrossTerms = IPACrossTermsAlgorithm(G = "ristretto255.group");
configure FoldIPA = FoldIPAAlgorithm(G = "ristretto255.group");
configure IPAWeightSeed = IPAWeightSeedAlgorithm(F = "ristretto255.scalar");
configure FoldPublicIPA = FoldPublicIPAAlgorithm(G = "ristretto255.group");
configure IPATerminalScalars = IPATerminalScalarsAlgorithm(F = "ristretto255.scalar");
configure CheckIPATerminal = CheckIPATerminalAlgorithm(G = "ristretto255.group");
fn BalanceSubjectAlgorithm<G: domain Group>(
  inputs: Vector<G::Element>,
  outputs: Vector<G::Element>,
  base: G::Element,
  fee: G::Scalar::Element
) -> (G::Element) requires (ScalarAction(G), Field(G::Scalar)) {
  let one = zkc::algebra::constant::<G::Scalar>() attributes ("1");
  let input_weights = zkc::algebra::vector_splat::<G::Scalar>(one) attributes ("2");
  let output_weights = zkc::algebra::vector_splat::<G::Scalar>(one) attributes ("2");
  let incoming = zkc::curve::msm::<G>(input_weights, inputs);
  let outgoing = zkc::curve::msm::<G>(output_weights, outputs);
  let fee_point = zkc::curve::scale::<G>(base, fee);
  let negative_one = zkc::algebra::neg::<G::Scalar>(one);
  let negative_outputs = zkc::curve::scale::<G>(outgoing, negative_one);
  let negative_fee = zkc::curve::scale::<G>(fee_point, negative_one);
  let difference = zkc::curve::add::<G>(incoming, negative_outputs);
  let excess = zkc::curve::add::<G>(difference, negative_fee);
  return (excess);
}
fn ExcessBlindingAlgorithm<F: domain Field>(
  inputs: Vector<F::Element>,
  outputs: Vector<F::Element>
) -> (F::Element) requires (Field(F)) {
  let input_shape = zkc::algebra::vector_length_check::<F>(inputs) attributes ("2");
  zkc::core::require(input_shape);
  let output_shape = zkc::algebra::vector_length_check::<F>(outputs) attributes ("2");
  zkc::core::require(output_shape);
  let incoming = zkc::algebra::vector_sum::<F>(inputs);
  let outgoing = zkc::algebra::vector_sum::<F>(outputs);
  let secret = zkc::algebra::sub::<F>(incoming, outgoing);
  return (secret);
}
fn SchnorrNonceAlgorithm<G: domain Group>(
  base: G::Element,
  entropy: Rng<G::Scalar>
) -> (G::Scalar::Element, G::Element, Rng<G::Scalar>) requires (ScalarAction(G), Field(G::Scalar)) {
  let (nonce, after) = zkc::random::draw::<G::Scalar>(entropy);
  let point = zkc::curve::scale::<G>(base, nonce);
  return (nonce, point, after);
}
fn NonidentityAlgorithm<G: domain Group>(point: G::Element) -> () requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let ok = zkc::curve::nonidentity::<G>(point);
  zkc::core::require(ok);
  return ();
}
fn SchnorrResponseAlgorithm<F: domain Field>(
  nonce: F::Element,
  secret: F::Element,
  challenge: F::Element
) -> (F::Element) requires (Field(F)) {
  let product = zkc::algebra::mul::<F>(challenge, secret);
  let response = zkc::algebra::add::<F>(nonce, product);
  return (response);
}
fn SchnorrEquationAlgorithm<G: domain Group>(
  base: G::Element,
  subject: G::Element,
  nonce: G::Element,
  challenge: G::Scalar::Element,
  response: G::Scalar::Element
) -> (bool) requires (ScalarAction(G), Field(G::Scalar)) {
  let left = zkc::curve::scale::<G>(base, response);
  let weighted = zkc::curve::scale::<G>(subject, challenge);
  let right = zkc::curve::add::<G>(nonce, weighted);
  let ok = zkc::curve::equal::<G>(left, right);
  zkc::core::require(ok);
  return (ok);
}
fn Owner0Algorithm<G: domain Group>(owners: Vector<G::Element>) -> (G::Element) requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let owner = zkc::curve::at::<G>(owners) attributes ("0");
  let ok = zkc::curve::nonidentity::<G>(owner);
  zkc::core::require(ok);
  return (owner);
}
fn Secret0Algorithm<F: domain Field>(secrets: Vector<F::Element>) -> (F::Element) requires (
  Field(F)
) {
  let shape = zkc::algebra::vector_length_check::<F>(secrets) attributes ("2");
  zkc::core::require(shape);
  let secret = zkc::algebra::vector_at::<F>(secrets) attributes ("0");
  return (secret);
}
fn Owner1Algorithm<G: domain Group>(owners: Vector<G::Element>) -> (G::Element) requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  let owner = zkc::curve::at::<G>(owners) attributes ("1");
  let ok = zkc::curve::nonidentity::<G>(owner);
  zkc::core::require(ok);
  return (owner);
}
fn Secret1Algorithm<F: domain Field>(secrets: Vector<F::Element>) -> (F::Element) requires (
  Field(F)
) {
  let shape = zkc::algebra::vector_length_check::<F>(secrets) attributes ("2");
  zkc::core::require(shape);
  let secret = zkc::algebra::vector_at::<F>(secrets) attributes ("1");
  return (secret);
}
protocol SchnorrKnowledge {
  roles (P, V);
  inputs (
    P secret: "ristretto255.scalar"::Element,
    P p_base: "ristretto255.group"::Element,
    P entropy: Rng<"ristretto255.scalar">,
    V base: "ristretto255.group"::Element,
    V subject: "ristretto255.group"::Element,
    V coins: Rng<"ristretto255.scalar">
  );
  outputs (V bool, V Rng<"ristretto255.scalar">, P Rng<"ristretto255.scalar">);
  local P: let (nonce, point, after_entropy) = SchnorrNonce(p_base, entropy);
  local P: Nonidentity(point);
  message schnorr_nonce: P(point) -> V(received_nonce);
  local V: Nonidentity(received_nonce);
  local V: let (challenge, after_coins) = DrawChallenge(coins);
  message schnorr_challenge: V(challenge) -> P(received_challenge);
  local P: let response = SchnorrResponse(nonce, secret, received_challenge);
  message schnorr_response: P(response) -> V(received_response);
  local V: let accepted = SchnorrEquation(
    base,
    subject,
    received_nonce,
    challenge,
    received_response
  );
  return (accepted, after_coins, after_entropy);
}
// Every nested invocation inherits the constructor's complete publicRoot.
// Host admission fixes generators, ledger membership, distinct IDs and integer bounds.
protocol ConfidentialTransaction {
  roles (P, V);
  parameters (rounds);
  inputs (
    P p_g: Vector<"ristretto255.group"::Element>,
    P p_h: Vector<"ristretto255.group"::Element>,
    P p_base: "ristretto255.group"::Element,
    P p_blind: "ristretto255.group"::Element,
    P p_commitments: Vector<"ristretto255.group"::Element>,
    P p_context: Vector<"ristretto255.scalar"::Element>,
    P p_input_commitments: Vector<"ristretto255.group"::Element>,
    P p_owners: Vector<"ristretto255.group"::Element>,
    P p_input_ids: Vector<"ristretto255.scalar"::Element>,
    P p_fee: "ristretto255.scalar"::Element,
    V g: Vector<"ristretto255.group"::Element>,
    V h: Vector<"ristretto255.group"::Element>,
    V base: "ristretto255.group"::Element,
    V blind: "ristretto255.group"::Element,
    V commitments: Vector<"ristretto255.group"::Element>,
    V context: Vector<"ristretto255.scalar"::Element>,
    V input_commitments: Vector<"ristretto255.group"::Element>,
    V owners: Vector<"ristretto255.group"::Element>,
    V input_ids: Vector<"ristretto255.scalar"::Element>,
    V fee: "ristretto255.scalar"::Element,
    P values: Vector<"ristretto255.scalar"::Element>,
    P blinding: Vector<"ristretto255.scalar"::Element>,
    P bits: Vector<"ristretto255.scalar"::Element>,
    P input_blinding: Vector<"ristretto255.scalar"::Element>,
    P secrets: Vector<"ristretto255.scalar"::Element>,
    P entropy: Rng<"ristretto255.scalar">,
    V coins: Rng<"ristretto255.scalar">
  );
  outputs (V bool, V Rng<"ristretto255.scalar">, P Rng<"ristretto255.scalar">);
  dependencies (
    range: AggregatedRange(rounds = rounds),
    balance: SchnorrKnowledge(),
    auth0: SchnorrKnowledge(),
    auth1: SchnorrKnowledge()
  );
  invoke [output_ranges] range(
    values,
    blinding,
    bits,
    entropy,
    p_g,
    p_h,
    p_base,
    p_blind,
    p_commitments,
    p_context,
    g,
    h,
    base,
    blind,
    commitments,
    context,
    coins
  ) -> (range_ok, after_range_coins, after_range_entropy);
  local P: let excess_secret = ExcessBlinding(input_blinding, blinding);
  local V: let excess_subject = BalanceSubject(input_commitments, commitments, base, fee);
  invoke [balance_knowledge] balance(
    excess_secret,
    p_blind,
    after_range_entropy,
    blind,
    excess_subject,
    after_range_coins
  ) -> (balance_ok, balance_coins, balance_entropy);
  local V: let range_balance_ok = Both(range_ok, balance_ok);
  local P: let secret0 = Secret0(secrets);
  local V: let owner0 = Owner0(owners);
  invoke [authorize_input_0] auth0(
    secret0,
    p_base,
    balance_entropy,
    base,
    owner0,
    balance_coins
  ) -> (auth0_ok, auth0_coins, auth0_entropy);
  local V: let accepted0 = Both(range_balance_ok, auth0_ok);
  local P: let secret1 = Secret1(secrets);
  local V: let owner1 = Owner1(owners);
  invoke [authorize_input_1] auth1(
    secret1,
    p_base,
    auth0_entropy,
    base,
    owner1,
    auth0_coins
  ) -> (auth1_ok, auth1_coins, auth1_entropy);
  local V: let accepted1 = Both(accepted0, auth1_ok);
  return (accepted1, auth1_coins, auth1_entropy);
}
instance balance: SchnorrKnowledge {
  roles (P = P, V = V);
}
instance auth0: SchnorrKnowledge {
  roles (P = P, V = V);
}
instance auth1: SchnorrKnowledge {
  roles (P = P, V = V);
}
instance transaction: ConfidentialTransaction {
  parameters (rounds = 4);
  dependencies (range = range, balance = balance, auth0 = auth0, auth1 = auth1);
  roles (P = P, V = V);
}
entry main = transaction;
configure BalanceSubject = BalanceSubjectAlgorithm(G = "ristretto255.group");
configure ExcessBlinding = ExcessBlindingAlgorithm(F = "ristretto255.scalar");
configure SchnorrNonce = SchnorrNonceAlgorithm(G = "ristretto255.group");
configure Nonidentity = NonidentityAlgorithm(G = "ristretto255.group");
configure SchnorrResponse = SchnorrResponseAlgorithm(F = "ristretto255.scalar");
configure SchnorrEquation = SchnorrEquationAlgorithm(G = "ristretto255.group");
configure Owner0 = Owner0Algorithm(G = "ristretto255.group");
configure Secret0 = Secret0Algorithm(F = "ristretto255.scalar");
configure Owner1 = Owner1Algorithm(G = "ristretto255.group");
configure Secret1 = Secret1Algorithm(F = "ristretto255.scalar");
