// Bounded ExecutionProof. NON-ZK development PCS; no production ISA claim.
// Generated by evaluation/application-composition/execution/build.py.
// Layout: word_bits=8, RAM=2, transitions=8.
// Program is verifier-owned sparse matrix configuration; see execution/README.md.
module {
  fn DrawChallengeAlgorithm<F: domain Field>(coins: Rng<F>) -> (F::Element, Rng<F>) requires (
    Field(F)
  ) {
    [draw] let (value, after) = random::draw::<F>(coins);
    return (value, after);
  }

  fn EmptyPointAlgorithm<F: domain Field>() -> Point<F> requires (Field(F)) {
    [__site_0] let p = poly::empty_point::<F>();
    return p;
  }

  fn AppendPointAlgorithm<F: domain Field>(p: Point<F>, r: F::Element) -> Point<F> requires (
    Field(F)
  ) {
    [__site_0] let next = poly::append_point::<F>(p, r);
    return next;
  }

  fn CommitOriginalAlgorithm<C: domain Commitment>(
    key: ProverKey<C>,
    z: Table<C::ValueField>
  ) -> (Commitment<C>, OpeningState<C>) requires (MultilinearOpening(C)) {
    [__site_0] let (root, original) = pcs::commit::<C>(key, z);
    return (root, original);
  }

  fn OpenOriginalAlgorithm<C: domain Commitment>(
    original: OpeningState<C>,
    point: Point<C::PointField>
  ) -> (C::EvaluationField::Element, Proof<C>) requires (MultilinearOpening(C)) {
    // pcs.open borrows immutable original custody; it never opens fold scratch.
    [__site_0] let (value, proof) = pcs::open::<C>(original, point);
    return (value, proof);
  }

  fn CheckOpeningAlgorithm<C: domain Commitment>(
    key: VerifierKey<C>,
    root: Commitment<C>,
    point: Point<C::PointField>,
    value: C::EvaluationField::Element,
    proof: Proof<C>
  ) -> C::EvaluationField::Element requires (MultilinearOpening(C)) {
    [__site_0] let ok = pcs::check::<C>(key, root, point, value, proof);
    [__site_1] control::require(ok);
    return value;
  }

  fn OuterEqualityAlgorithm<F: domain Field>(tau: Point<F>) -> Vector<F::Element> requires (
    Field(F)
  ) {
    [__site_0] let equality = poly::equality_weights::<F>(tau);
    return equality;
  }

  fn ZeroClaimAlgorithm<F: domain Field>() -> F::Element requires (Field(F)) {
    [__site_0] let zero = field::constant::<F>() attributes ("0");
    return zero;
  }

  fn CubicRoundAlgorithm<F: domain Field>(
    e: Vector<F::Element>,
    a: Vector<F::Element>,
    b: Vector<F::Element>,
    c: Vector<F::Element>
  ) -> Polynomial<F> requires (Field(F)) {
    // Sum the coefficients of (eL+X*de)*((aL+X*da)*(bL+X*db)-(cL+X*dc)).
    [__site_0] let (el, er) = vector::split::<F>(e);
    [__site_1] let (al, ar) = vector::split::<F>(a);
    [__site_2] let (bl, br) = vector::split::<F>(b);
    [__site_3] let (cl, cr) = vector::split::<F>(c);
    [__site_4] let de = vector::sub::<F>(er, el);
    [__site_5] let da = vector::sub::<F>(ar, al);
    [__site_6] let db = vector::sub::<F>(br, bl);
    [__site_7] let dc = vector::sub::<F>(cr, cl);
    [__site_8] let ab = vector::mul::<F>(al, bl);
    [__site_9] let p0 = vector::sub::<F>(ab, cl);
    [__site_10] let adb = vector::mul::<F>(al, db);
    [__site_11] let dab = vector::mul::<F>(da, bl);
    [__site_12] let cross = vector::add::<F>(adb, dab);
    [__site_13] let p1 = vector::sub::<F>(cross, dc);
    [__site_14] let q0 = vector::dot::<F>(el, p0);
    [__site_15] let q1_left = vector::dot::<F>(el, p1);
    [__site_16] let q1_right = vector::dot::<F>(de, p0);
    [__site_17] let q1 = field::add::<F>(q1_left, q1_right);
    // Reuse the quadratic product in both highest coefficients.
    [__site_18] let dadb = vector::mul::<F>(da, db);
    [__site_19] let q2_left = vector::dot::<F>(el, dadb);
    [__site_20] let q2_right = vector::dot::<F>(de, p1);
    [__site_21] let q2 = field::add::<F>(q2_left, q2_right);
    [__site_22] let q3 = vector::dot::<F>(de, dadb);
    [__site_23] let coefficients_empty = vector::empty::<F>();
    [__site_24] let coefficients_0 = vector::append::<F>(coefficients_empty, q0);
    [__site_25] let coefficients_1 = vector::append::<F>(coefficients_0, q1);
    [__site_26] let coefficients_2 = vector::append::<F>(coefficients_1, q2);
    [__site_27] let coefficients = vector::append::<F>(coefficients_2, q3);
    [__site_28] let q = poly::from_coefficients::<F>(coefficients);
    return q;
  }

  fn CheckCubicBoundaryAlgorithm<F: domain Field>(q: Polynomial<F>, claim: F::Element) -> () requires (
    Field(F)
  ) {
    // A received polynomial is not degree bounded by its type. Check before drawing.
    [__site_0] let degree_ok = poly::degree_check::<F>(q) attributes ("3");
    [__site_1] control::require(degree_ok);
    [__site_2] let sum = poly::univariate_boundary::<F>(q);
    [__site_3] let claim_ok = field::equal::<F>(sum, claim);
    [__site_4] control::require(claim_ok);
    return;
  }

  fn EvaluateCubicAlgorithm<F: domain Field>(q: Polynomial<F>, r: F::Element) -> F::Element requires (
    Field(F)
  ) {
    [__site_0] let value = poly::univariate_evaluate::<F>(q, r);
    return value;
  }

  fn FoldOuterAlgorithm<F: domain Field>(
    e: Vector<F::Element>,
    a: Vector<F::Element>,
    b: Vector<F::Element>,
    c: Vector<F::Element>,
    r: F::Element
  ) -> (Vector<F::Element>, Vector<F::Element>, Vector<F::Element>, Vector<F::Element>) requires (
    Field(F)
  ) {
    [__site_0] let (el, er) = vector::split::<F>(e);
    [__site_1] let ed = vector::sub::<F>(er, el);
    [__site_2] let escaled = vector::scale::<F>(ed, r);
    [__site_3] let enext = vector::add::<F>(el, escaled);
    [__site_4] let (al, ar) = vector::split::<F>(a);
    [__site_5] let ad = vector::sub::<F>(ar, al);
    [__site_6] let ascaled = vector::scale::<F>(ad, r);
    [__site_7] let anext = vector::add::<F>(al, ascaled);
    [__site_8] let (bl, br) = vector::split::<F>(b);
    [__site_9] let bd = vector::sub::<F>(br, bl);
    [__site_10] let bscaled = vector::scale::<F>(bd, r);
    [__site_11] let bnext = vector::add::<F>(bl, bscaled);
    [__site_12] let (cl, cr) = vector::split::<F>(c);
    [__site_13] let cd = vector::sub::<F>(cr, cl);
    [__site_14] let cscaled = vector::scale::<F>(cd, r);
    [__site_15] let cnext = vector::add::<F>(cl, cscaled);
    return (enext, anext, bnext, cnext);
  }

  fn OuterValuesAlgorithm<F: domain Field>(
    a: Vector<F::Element>,
    b: Vector<F::Element>,
    c: Vector<F::Element>
  ) -> (F::Element, F::Element, F::Element) requires (Field(F)) {
    [__site_0] let a_shape = vector::length_check::<F>(a) attributes ("1");
    [__site_1] control::require(a_shape);
    [__site_2] let ar = vector::at::<F>(a) attributes ("0");
    [__site_3] let b_shape = vector::length_check::<F>(b) attributes ("1");
    [__site_4] control::require(b_shape);
    [__site_5] let br = vector::at::<F>(b) attributes ("0");
    [__site_6] let c_shape = vector::length_check::<F>(c) attributes ("1");
    [__site_7] control::require(c_shape);
    [__site_8] let cr = vector::at::<F>(c) attributes ("0");
    return (ar, br, cr);
  }

  fn CheckOuterTerminalAlgorithm<F: domain Field>(
    tau: Point<F>,
    r: Point<F>,
    a: F::Element,
    b: F::Element,
    c: F::Element,
    claim: F::Element
  ) -> () requires (Field(F)) {
    [__site_0] let tau_weights = poly::equality_weights::<F>(tau);
    [__site_1] let r_weights = poly::equality_weights::<F>(r);
    [__site_2] let equality = vector::dot::<F>(tau_weights, r_weights);
    [__site_3] let ab = field::mul::<F>(a, b);
    [__site_4] let residual = field::sub::<F>(ab, c);
    [__site_5] let expected = field::mul::<F>(equality, residual);
    [__site_6] let ok = field::equal::<F>(claim, expected);
    [__site_7] control::require(ok);
    return;
  }

  fn MixClaimAlgorithm<F: domain Field>(
    a: F::Element,
    b: F::Element,
    c: F::Element,
    alpha: F::Element,
    beta: F::Element,
    gamma: F::Element
  ) -> F::Element requires (Field(F)) {
    [__site_0] let aa = field::mul::<F>(alpha, a);
    [__site_1] let bb = field::mul::<F>(beta, b);
    [__site_2] let cc = field::mul::<F>(gamma, c);
    [__site_3] let ab = field::add::<F>(aa, bb);
    [__site_4] let claim = field::add::<F>(ab, cc);
    return claim;
  }

  fn ProductRoundAlgorithm<F: domain Field>(a: Table<F>, b: Table<F>) -> Round<F> requires (
    Field(F)
  ) {
    // The existing round type carries the bound two, unlike polynomial.
    [__site_0] let q = poly::product_round::<F>(a, b);
    return q;
  }

  fn CheckQuadraticBoundaryAlgorithm<F: domain Field>(q: Round<F>, claim: F::Element) -> () requires (
    Field(F)
  ) {
    [__site_0] let sum = poly::boundary::<F>(q);
    [__site_1] let ok = field::equal::<F>(sum, claim);
    [__site_2] control::require(ok);
    return;
  }

  fn EvaluateQuadraticAlgorithm<F: domain Field>(q: Round<F>, r: F::Element) -> F::Element requires (
    Field(F)
  ) {
    [__site_0] let value = poly::round_evaluate::<F>(q, r);
    return value;
  }

  fn FoldProductAlgorithm<F: domain Field>(
    a: Table<F>,
    b: Table<F>,
    r: F::Element
  ) -> (Table<F>, Table<F>) requires (Field(F)) {
    // Use the existing table abstraction for logical MSB folding.
    [__site_0] let at = poly::fold::<F>(a, r);
    [__site_1] let bt = poly::fold::<F>(b, r);
    return (at, bt);
  }

  fn PackOriginalAlgorithm<F: domain Field>(z: Vector<F::Element>) -> Table<F> requires (Field(F)) {
    [__site_0] let shape = vector::length_check::<F>(z) attributes ("863");
    [__site_1] control::require(shape);
    [__site_2] let zero = field::constant::<F>() attributes ("0");
    [__site_3] let zeros = vector::splat::<F>(zero) attributes ("161");
    [__site_4] let padded = vector::concat::<F>(z, zeros);
    [__site_5] let table = vector::to_table::<F>(padded);
    return table;
  }

  fn GatherDomainClaimsAlgorithm<F: domain Field>(
    cpu_point: Point<F>,
    cpu_claim: F::Element,
    cpu_matrix: F::Element,
    memory_point: Point<F>,
    memory_claim: F::Element,
    memory_matrix: F::Element,
    link_point: Point<F>,
    link_claim: F::Element,
    link_matrix: F::Element
  ) -> (
    Point<F>,
    F::Element,
    F::Element,
    Point<F>,
    F::Element,
    F::Element,
    Point<F>,
    F::Element,
    F::Element
  ) requires (Field(F)) {
    return (
      cpu_point,
      cpu_claim,
      cpu_matrix,
      memory_point,
      memory_claim,
      memory_matrix,
      link_point,
      link_claim,
      link_matrix
    );
  }

  fn CheckExecutionConnectionsAlgorithm<F: domain Field>(
    cpu_matrix: F::Element,
    cpu_value: F::Element,
    cpu_claim: F::Element,
    memory_matrix: F::Element,
    memory_value: F::Element,
    memory_claim: F::Element,
    link_matrix: F::Element,
    link_value: F::Element,
    link_claim: F::Element
  ) -> bool requires (Field(F)) {
    [__site_0] let cpu_expected = field::mul::<F>(cpu_matrix, cpu_value);
    [__site_1] let cpu_ok = field::equal::<F>(cpu_expected, cpu_claim);
    [guard_cpu_connection] control::require(cpu_ok);
    [__site_2] let memory_expected = field::mul::<F>(memory_matrix, memory_value);
    [__site_3] let memory_ok = field::equal::<F>(memory_expected, memory_claim);
    [guard_memory_connection] control::require(memory_ok);
    [__site_4] let link_expected = field::mul::<F>(link_matrix, link_value);
    [__site_5] let link_ok = field::equal::<F>(link_expected, link_claim);
    [guard_link_connection] control::require(link_ok);
    return link_ok;
  }

  // A residual is (actual inner point s, scalar claim, verifier K(r,s)).
  // No PCS opening and no Boolean relation certificate is returned here.
  // Independent challenges after the three terminal values have been fixed.
  // One application-specific packed subject; all three views use its columns.
  // Gather actual residuals before opening; retain component occurrence.
  configure DrawChallenge = DrawChallengeAlgorithm(F = bls12-381.fr);
  configure EmptyPoint = EmptyPointAlgorithm(F = bls12-381.fr);
  configure AppendPoint = AppendPointAlgorithm(F = bls12-381.fr);
  configure CommitOriginal = CommitOriginalAlgorithm(C = "multilinear.kzg.bls12-381/1");
  configure OpenOriginal = OpenOriginalAlgorithm(C = "multilinear.kzg.bls12-381/1");
  configure CheckOpening = CheckOpeningAlgorithm(C = "multilinear.kzg.bls12-381/1");
  configure OuterEquality = OuterEqualityAlgorithm(F = bls12-381.fr);
  configure ZeroClaim = ZeroClaimAlgorithm(F = bls12-381.fr);
  configure CubicRound = CubicRoundAlgorithm(F = bls12-381.fr);
  configure CheckCubicBoundary = CheckCubicBoundaryAlgorithm(F = bls12-381.fr);
  configure EvaluateCubic = EvaluateCubicAlgorithm(F = bls12-381.fr);
  configure FoldOuter = FoldOuterAlgorithm(F = bls12-381.fr);
  configure OuterValues = OuterValuesAlgorithm(F = bls12-381.fr);
  configure CheckOuterTerminal = CheckOuterTerminalAlgorithm(F = bls12-381.fr);
  configure MixClaim = MixClaimAlgorithm(F = bls12-381.fr);
  configure ProductRound = ProductRoundAlgorithm(F = bls12-381.fr);
  configure CheckQuadraticBoundary = CheckQuadraticBoundaryAlgorithm(F = bls12-381.fr);
  configure EvaluateQuadratic = EvaluateQuadraticAlgorithm(F = bls12-381.fr);
  configure FoldProduct = FoldProductAlgorithm(F = bls12-381.fr);
  configure PackOriginal = PackOriginalAlgorithm(F = bls12-381.fr);
  configure GatherDomainClaims = GatherDomainClaimsAlgorithm(F = bls12-381.fr);
  configure CheckExecutionConnections = CheckExecutionConnectionsAlgorithm(F = bls12-381.fr);
  bind R_op_0 = vector::length_check(bls12-381.fr);
  bind R_op_1 = control::require();
  bind R_op_2 = vector::constant(bls12-381.fr);
  bind R_op_3 = vector::concat(bls12-381.fr);
  bind R_op_4 = matrix::shape_check(bls12-381.fr);
  bind R_op_5 = field::constant(bls12-381.fr);
  bind R_op_6 = vector::splat(bls12-381.fr);
  bind R_op_7 = matrix::mul_vector(bls12-381.fr);
  bind R_op_8 = vector::to_table(bls12-381.fr);
  bind R_op_9 = vector::from_point(bls12-381.fr);
  bind R_op_10 = poly::equality_weights(bls12-381.fr);
  bind R_op_11 = matrix::transpose_mul_vector(bls12-381.fr);
  bind R_op_12 = vector::scale(bls12-381.fr);
  bind R_op_13 = vector::add(bls12-381.fr);
  bind R_op_14 = matrix::bilinear(bls12-381.fr);
  bind R_op_15 = vector::to_point(bls12-381.fr);
  bind R_op_16 = field::equal(bls12-381.fr);
  bind R_op_17 = vector::at(bls12-381.fr);
  fn R_Assemble(
    statement: Vector<"bls12-381.fr"::Element>,
    witness: Vector<"bls12-381.fr"::Element>
  ) -> Vector<"bls12-381.fr"::Element> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_0(statement) attributes ("4");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_0(witness) attributes ("858");
    [step_5] R_op_1(value_4);
    [step_6] let value_7 = R_op_2() attributes ("1");
    [step_8] let value_9 = R_op_3(value_7, statement);
    [step_10] let value_11 = R_op_3(value_9, witness);
    return value_11;
  }

  fn R_Products(
    a: Matrix<"bls12-381.fr"::Element>,
    b: Matrix<"bls12-381.fr"::Element>,
    c: Matrix<"bls12-381.fr"::Element>,
    assignment: Vector<"bls12-381.fr"::Element>
  ) -> (
    Vector<"bls12-381.fr"::Element>,
    Vector<"bls12-381.fr"::Element>,
    Vector<"bls12-381.fr"::Element>,
    Table<"bls12-381.fr">
  ) origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_4(a) attributes ("1024", "1024");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_4(b) attributes ("1024", "1024");
    [step_5] R_op_1(value_4);
    [step_6] let value_7 = R_op_4(c) attributes ("1024", "1024");
    [step_8] R_op_1(value_7);
    [step_9] let value_10 = R_op_0(assignment) attributes ("863");
    [step_11] R_op_1(value_10);
    [step_12] let value_13 = R_op_5() attributes ("0");
    [step_14] let value_15 = R_op_6(value_13) attributes ("161");
    [step_16] let value_17 = R_op_3(assignment, value_15);
    [step_18] let value_19 = R_op_7(a, value_17);
    [step_20] let value_21 = R_op_7(b, value_17);
    [step_22] let value_23 = R_op_7(c, value_17);
    [step_24] let value_25 = R_op_8(value_17);
    return (value_19, value_21, value_23, value_25);
  }

  fn R_Contract(
    a: Matrix<"bls12-381.fr"::Element>,
    b: Matrix<"bls12-381.fr"::Element>,
    c: Matrix<"bls12-381.fr"::Element>,
    r: Point<"bls12-381.fr">,
    alpha: "bls12-381.fr"::Element,
    beta: "bls12-381.fr"::Element,
    gamma: "bls12-381.fr"::Element
  ) -> Table<"bls12-381.fr"> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_4(a) attributes ("1024", "1024");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_4(b) attributes ("1024", "1024");
    [step_5] R_op_1(value_4);
    [step_6] let value_7 = R_op_4(c) attributes ("1024", "1024");
    [step_8] R_op_1(value_7);
    [step_9] let value_10 = R_op_9(r);
    [step_11] let value_12 = R_op_0(value_10) attributes ("10");
    [step_13] R_op_1(value_12);
    [step_14] let value_15 = R_op_10(r);
    [step_16] let value_17 = R_op_11(a, value_15);
    [step_18] let value_19 = R_op_12(value_17, alpha);
    [step_20] let value_21 = R_op_11(b, value_15);
    [step_22] let value_23 = R_op_12(value_21, beta);
    [step_24] let value_25 = R_op_11(c, value_15);
    [step_26] let value_27 = R_op_12(value_25, gamma);
    [step_28] let value_29 = R_op_13(value_19, value_23);
    [step_30] let value_31 = R_op_13(value_29, value_27);
    [step_32] let value_33 = R_op_8(value_31);
    return value_33;
  }

  fn R_Evaluate(
    a: Matrix<"bls12-381.fr"::Element>,
    b: Matrix<"bls12-381.fr"::Element>,
    c: Matrix<"bls12-381.fr"::Element>,
    r: Point<"bls12-381.fr">,
    s: Point<"bls12-381.fr">
  ) -> ("bls12-381.fr"::Element, "bls12-381.fr"::Element, "bls12-381.fr"::Element) origin Relation_Layout_1024_863_1_3(
  ) {
    [step_0] let value_1 = R_op_4(a) attributes ("1024", "1024");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_4(b) attributes ("1024", "1024");
    [step_5] R_op_1(value_4);
    [step_6] let value_7 = R_op_4(c) attributes ("1024", "1024");
    [step_8] R_op_1(value_7);
    [step_9] let value_10 = R_op_9(r);
    [step_11] let value_12 = R_op_0(value_10) attributes ("10");
    [step_13] R_op_1(value_12);
    [step_14] let value_15 = R_op_10(r);
    [step_16] let value_17 = R_op_9(s);
    [step_18] let value_19 = R_op_0(value_17) attributes ("10");
    [step_20] R_op_1(value_19);
    [step_21] let value_22 = R_op_10(s);
    [step_23] let value_24 = R_op_14(a, value_15, value_22);
    [step_25] let value_26 = R_op_14(b, value_15, value_22);
    [step_27] let value_28 = R_op_14(c, value_15, value_22);
    return (value_24, value_26, value_28);
  }

  fn R_BindingPoint0() -> Point<"bls12-381.fr"> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_2() attributes ("0", "0", "0", "0", "0", "0", "0", "0", "0", "0");
    [step_2] let value_3 = R_op_15(value_1);
    return value_3;
  }

  fn R_CheckBinding0(value: "bls12-381.fr"::Element) -> () origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_5() attributes ("1");
    [step_2] let value_3 = R_op_16(value, value_1);
    [step_4] R_op_1(value_3);
    return;
  }

  fn R_BindingPoint1() -> Point<"bls12-381.fr"> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_2() attributes ("0", "0", "0", "0", "0", "0", "0", "0", "0", "1");
    [step_2] let value_3 = R_op_15(value_1);
    return value_3;
  }

  fn R_CheckBinding1(
    value: "bls12-381.fr"::Element,
    statement: Vector<"bls12-381.fr"::Element>
  ) -> () origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_0(statement) attributes ("4");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_17(statement) attributes ("0");
    [step_5] let value_6 = R_op_16(value, value_4);
    [step_7] R_op_1(value_6);
    return;
  }

  fn R_BindingPoint2() -> Point<"bls12-381.fr"> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_2() attributes ("0", "0", "0", "0", "0", "0", "0", "0", "1", "0");
    [step_2] let value_3 = R_op_15(value_1);
    return value_3;
  }

  fn R_CheckBinding2(
    value: "bls12-381.fr"::Element,
    statement: Vector<"bls12-381.fr"::Element>
  ) -> () origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_0(statement) attributes ("4");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_17(statement) attributes ("1");
    [step_5] let value_6 = R_op_16(value, value_4);
    [step_7] R_op_1(value_6);
    return;
  }

  fn R_BindingPoint3() -> Point<"bls12-381.fr"> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_2() attributes ("0", "0", "0", "0", "0", "0", "0", "0", "1", "1");
    [step_2] let value_3 = R_op_15(value_1);
    return value_3;
  }

  fn R_CheckBinding3(
    value: "bls12-381.fr"::Element,
    statement: Vector<"bls12-381.fr"::Element>
  ) -> () origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_0(statement) attributes ("4");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_17(statement) attributes ("2");
    [step_5] let value_6 = R_op_16(value, value_4);
    [step_7] R_op_1(value_6);
    return;
  }

  fn R_BindingPoint4() -> Point<"bls12-381.fr"> origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_2() attributes ("0", "0", "0", "0", "0", "0", "0", "1", "0", "0");
    [step_2] let value_3 = R_op_15(value_1);
    return value_3;
  }

  fn R_CheckBinding4(
    value: "bls12-381.fr"::Element,
    statement: Vector<"bls12-381.fr"::Element>
  ) -> () origin Relation_Layout_1024_863_1_3() {
    [step_0] let value_1 = R_op_0(statement) attributes ("4");
    [step_2] R_op_1(value_1);
    [step_3] let value_4 = R_op_17(statement) attributes ("3");
    [step_5] let value_6 = R_op_16(value, value_4);
    [step_7] R_op_1(value_6);
    return;
  }

  protocol RandomPoint {
    roles (P, V);
    parameters (rounds);
    inputs (V coins: Rng<"bls12-381.fr">);
    outputs (P Point<"bls12-381.fr">, V Point<"bls12-381.fr">, V Rng<"bls12-381.fr">);
    local [__site_0] P: let pp = EmptyPoint();
    local [__site_1] V: let vp = EmptyPoint();
    loop [coordinates] rounds carry (p = pp, v = vp, random = coins) -> (p_end, v_end, after) {
      local [__site_2] V: let (r, next_random) = DrawChallenge(random);
      message [__site_3] coordinate: V(r) -> P(pr);
      local [__site_4] P: let next_p = AppendPoint(p, pr);
      local [__site_5] V: let next_v = AppendPoint(v, r);
      yield (next_p, next_v, next_random);
    }
    return (p_end, v_end, after);
  }

  protocol OriginalOpening {
    roles (P, V);
    inputs (
      P original: OpeningState<"multilinear.kzg.bls12-381/1">,
      P p_point: Point<"bls12-381.fr">,
      V vk: VerifierKey<"multilinear.kzg.bls12-381/1">,
      V root: Commitment<"multilinear.kzg.bls12-381/1">,
      V v_point: Point<"bls12-381.fr">
    );
    outputs (V "bls12-381.fr"::Element);
    local [__site_0] P: let (value, proof) = OpenOriginal(original, p_point);
    message [__site_1] evaluation: P(value) -> V(received_value);
    message [__site_2] original_opening: P(proof) -> V(received_proof);
    local [__site_3] V: let checked = CheckOpening(
      vk,
      root,
      v_point,
      received_value,
      received_proof
    );
    return checked;
  }

  protocol CubicSumcheck {
    roles (P, V);
    parameters (rounds);
    inputs (
      P e: Vector<"bls12-381.fr"::Element>,
      P a: Vector<"bls12-381.fr"::Element>,
      P b: Vector<"bls12-381.fr"::Element>,
      P c: Vector<"bls12-381.fr"::Element>,
      V claim: "bls12-381.fr"::Element,
      V coins: Rng<"bls12-381.fr">
    );
    outputs (
      P Point<"bls12-381.fr">,
      V Point<"bls12-381.fr">,
      P "bls12-381.fr"::Element,
      P "bls12-381.fr"::Element,
      P "bls12-381.fr"::Element,
      V "bls12-381.fr"::Element,
      V Rng<"bls12-381.fr">
    );
    local [__site_0] P: let pp = EmptyPoint();
    local [__site_1] V: let vp = EmptyPoint();
    loop [outer_rounds] rounds carry (
      eq = e,
      av = a,
      bv = b,
      cv = c,
      p = pp,
      v = vp,
      current = claim,
      random = coins
    ) -> (e_end, a_end, b_end, c_end, p_end, v_end, claim_end, coins_end) {
      local [__site_2] P: let q = CubicRound(eq, av, bv, cv);
      message [__site_3] cubic_coefficients: P(q) -> V(received_q);
      local [__site_4] V: CheckCubicBoundary(received_q, current);
      local [__site_5] V: let (r, next_random) = DrawChallenge(random);
      local [__site_6] V: let next_claim = EvaluateCubic(received_q, r);
      message [__site_7] coordinate: V(r) -> P(pr);
      local [__site_8] P: let (next_e, next_a, next_b, next_c) = FoldOuter(eq, av, bv, cv, pr);
      local [__site_9] P: let next_p = AppendPoint(p, pr);
      local [__site_10] V: let next_v = AppendPoint(v, r);
      yield (next_e, next_a, next_b, next_c, next_p, next_v, next_claim, next_random);
    }
    local [__site_11] P: let (ar, br, cr) = OuterValues(a_end, b_end, c_end);
    return (p_end, v_end, ar, br, cr, claim_end, coins_end);
  }

  protocol ProductSumcheck {
    roles (P, V);
    parameters (rounds);
    inputs (
      P a: Table<"bls12-381.fr">,
      P b: Table<"bls12-381.fr">,
      V claim: "bls12-381.fr"::Element,
      V coins: Rng<"bls12-381.fr">
    );
    outputs (
      P Point<"bls12-381.fr">,
      V Point<"bls12-381.fr">,
      V "bls12-381.fr"::Element,
      V Rng<"bls12-381.fr">
    );
    local [__site_0] P: let pp = EmptyPoint();
    local [__site_1] V: let vp = EmptyPoint();
    loop [inner_rounds] rounds carry (
      av = a,
      bv = b,
      p = pp,
      v = vp,
      current = claim,
      random = coins
    ) -> (a_end, b_end, p_end, v_end, claim_end, coins_end) {
      local [__site_2] P: let q = ProductRound(av, bv);
      message [__site_3] quadratic_coefficients: P(q) -> V(received_q);
      local [__site_4] V: CheckQuadraticBoundary(received_q, current);
      local [__site_5] V: let (r, next_random) = DrawChallenge(random);
      local [__site_6] V: let next_claim = EvaluateQuadratic(received_q, r);
      message [__site_7] coordinate: V(r) -> P(pr);
      local [__site_8] P: let (next_a, next_b) = FoldProduct(av, bv, pr);
      local [__site_9] P: let next_p = AppendPoint(p, pr);
      local [__site_10] V: let next_v = AppendPoint(v, r);
      yield (next_a, next_b, next_p, next_v, next_claim, next_random);
    }
    return (p_end, v_end, claim_end, coins_end);
  }

  protocol R1CSReduction {
    roles (P, V);
    parameters (row_rounds, column_rounds);
    inputs (
      P z: Vector<"bls12-381.fr"::Element>,
      P original_table: Table<"bls12-381.fr">,
      P p_a: Matrix<"bls12-381.fr"::Element>,
      P p_b: Matrix<"bls12-381.fr"::Element>,
      P p_c: Matrix<"bls12-381.fr"::Element>,
      V a: Matrix<"bls12-381.fr"::Element>,
      V b: Matrix<"bls12-381.fr"::Element>,
      V c: Matrix<"bls12-381.fr"::Element>,
      V coins: Rng<"bls12-381.fr">
    );
    outputs (
      P Point<"bls12-381.fr">,
      V Point<"bls12-381.fr">,
      V "bls12-381.fr"::Element,
      V "bls12-381.fr"::Element,
      V Rng<"bls12-381.fr">
    );
    dependencies (
      tau: RandomPoint(rounds = row_rounds),
      outer: CubicSumcheck(rounds = row_rounds),
      inner: ProductSumcheck(rounds = column_rounds)
    );
    local [__site_0] P: let (az, bz, cz, unused_table) = R_Products(p_a, p_b, p_c, z);
    invoke [draw_tau] tau(coins) -> (p_tau, v_tau, after_tau);
    local [__site_1] P: let equality = OuterEquality(p_tau);
    local [__site_2] V: let zero = ZeroClaim();
    invoke [outer_sumcheck] outer(
      equality,
      az,
      bz,
      cz,
      zero,
      after_tau
    ) -> (p_r, v_r, ar, br, cr, outer_claim, after_outer);
    message [__site_3] outer_a: P(ar) -> V(received_ar);
    message [__site_4] outer_b: P(br) -> V(received_br);
    message [__site_5] outer_c: P(cr) -> V(received_cr);
    local [__site_6] V: CheckOuterTerminal(
      v_tau,
      v_r,
      received_ar,
      received_br,
      received_cr,
      outer_claim
    );
    local [__site_7] V: let (alpha, after_alpha) = DrawChallenge(after_outer);
    message [__site_8] batch_alpha: V(alpha) -> P(p_alpha);
    local [__site_9] V: let (beta, after_beta) = DrawChallenge(after_alpha);
    message [__site_10] batch_beta: V(beta) -> P(p_beta);
    local [__site_11] V: let (gamma, after_gamma) = DrawChallenge(after_beta);
    message [__site_12] batch_gamma: V(gamma) -> P(p_gamma);
    local [__site_13] V: let mixed_claim = MixClaim(
      received_ar,
      received_br,
      received_cr,
      alpha,
      beta,
      gamma
    );
    local [__site_14] P: let matrix_table = R_Contract(p_a, p_b, p_c, p_r, p_alpha, p_beta, p_gamma);
    invoke [inner_sumcheck] inner(
      matrix_table,
      original_table,
      mixed_claim,
      after_gamma
    ) -> (p_s, v_s, inner_claim, after_inner);
    local [__site_15] V: let (ars, brs, crs) = R_Evaluate(a, b, c, v_r, v_s);
    local [__site_16] V: let matrix_value = MixClaim(ars, brs, crs, alpha, beta, gamma);
    return (p_s, v_s, inner_claim, matrix_value, after_inner);
  }

  protocol ExecutionProof {
    roles (P, V);
    parameters (row_rounds, column_rounds);
    inputs (
      P pk: ProverKey<"multilinear.kzg.bls12-381/1">,
      P z: Vector<"bls12-381.fr"::Element>,
      P p_cpu_a: Matrix<"bls12-381.fr"::Element>,
      P p_cpu_b: Matrix<"bls12-381.fr"::Element>,
      P p_cpu_c: Matrix<"bls12-381.fr"::Element>,
      P p_memory_a: Matrix<"bls12-381.fr"::Element>,
      P p_memory_b: Matrix<"bls12-381.fr"::Element>,
      P p_memory_c: Matrix<"bls12-381.fr"::Element>,
      P p_link_a: Matrix<"bls12-381.fr"::Element>,
      P p_link_b: Matrix<"bls12-381.fr"::Element>,
      P p_link_c: Matrix<"bls12-381.fr"::Element>,
      P p_statement: Vector<"bls12-381.fr"::Element>,
      P p_context: Vector<"bls12-381.fr"::Element>,
      V vk: VerifierKey<"multilinear.kzg.bls12-381/1">,
      V cpu_a: Matrix<"bls12-381.fr"::Element>,
      V cpu_b: Matrix<"bls12-381.fr"::Element>,
      V cpu_c: Matrix<"bls12-381.fr"::Element>,
      V memory_a: Matrix<"bls12-381.fr"::Element>,
      V memory_b: Matrix<"bls12-381.fr"::Element>,
      V memory_c: Matrix<"bls12-381.fr"::Element>,
      V link_a: Matrix<"bls12-381.fr"::Element>,
      V link_b: Matrix<"bls12-381.fr"::Element>,
      V link_c: Matrix<"bls12-381.fr"::Element>,
      V statement: Vector<"bls12-381.fr"::Element>,
      V context: Vector<"bls12-381.fr"::Element>,
      V coins: Rng<"bls12-381.fr">
    );
    outputs (V bool, V Rng<"bls12-381.fr">);
    dependencies (
      reduce: R1CSReduction(row_rounds = row_rounds, column_rounds = column_rounds),
      opening: OriginalOpening()
    );
    local [__site_0] P: let original_table = PackOriginal(z);
    local [__site_1] P: let (root, original) = CommitOriginal(pk, original_table);
    message [__site_2] original_commitment: P(root) -> V(received_root);
    local [__site_3] P: let pp0 = R_BindingPoint0();
    local [__site_4] V: let vp0 = R_BindingPoint0();
    invoke [bind_0] opening(original, pp0, vk, received_root, vp0) -> (bound0);
    local [__site_5] V: R_CheckBinding0(bound0);
    local [__site_6] P: let pp1 = R_BindingPoint1();
    local [__site_7] V: let vp1 = R_BindingPoint1();
    invoke [bind_1] opening(original, pp1, vk, received_root, vp1) -> (bound1);
    local [__site_8] V: R_CheckBinding1(bound1, statement);
    local [__site_9] P: let pp2 = R_BindingPoint2();
    local [__site_10] V: let vp2 = R_BindingPoint2();
    invoke [bind_2] opening(original, pp2, vk, received_root, vp2) -> (bound2);
    local [__site_11] V: R_CheckBinding2(bound2, statement);
    local [__site_12] P: let pp3 = R_BindingPoint3();
    local [__site_13] V: let vp3 = R_BindingPoint3();
    invoke [bind_3] opening(original, pp3, vk, received_root, vp3) -> (bound3);
    local [__site_14] V: R_CheckBinding3(bound3, statement);
    local [__site_15] P: let pp4 = R_BindingPoint4();
    local [__site_16] V: let vp4 = R_BindingPoint4();
    invoke [bind_4] opening(original, pp4, vk, received_root, vp4) -> (bound4);
    local [__site_17] V: R_CheckBinding4(bound4, statement);
    invoke [cpu_proof] reduce(
      z,
      original_table,
      p_cpu_a,
      p_cpu_b,
      p_cpu_c,
      cpu_a,
      cpu_b,
      cpu_c,
      coins
    ) -> (p_cpu_point, cpu_point, cpu_claim, cpu_matrix, after_cpu);
    invoke [memory_proof] reduce(
      z,
      original_table,
      p_memory_a,
      p_memory_b,
      p_memory_c,
      memory_a,
      memory_b,
      memory_c,
      after_cpu
    ) -> (p_memory_point, memory_point, memory_claim, memory_matrix, after_memory);
    invoke [link_proof] reduce(
      z,
      original_table,
      p_link_a,
      p_link_b,
      p_link_c,
      link_a,
      link_b,
      link_c,
      after_memory
    ) -> (p_link_point, link_point, link_claim, link_matrix, after_link);
    local [__site_18] V: let (
      g_cpu_point,
      g_cpu_claim,
      g_cpu_matrix,
      g_memory_point,
      g_memory_claim,
      g_memory_matrix,
      g_link_point,
      g_link_claim,
      g_link_matrix
    ) = GatherDomainClaims(
      cpu_point,
      cpu_claim,
      cpu_matrix,
      memory_point,
      memory_claim,
      memory_matrix,
      link_point,
      link_claim,
      link_matrix
    );
    invoke [open_cpu_original] opening(
      original,
      p_cpu_point,
      vk,
      received_root,
      g_cpu_point
    ) -> (cpu_value);
    invoke [open_memory_original] opening(
      original,
      p_memory_point,
      vk,
      received_root,
      g_memory_point
    ) -> (memory_value);
    invoke [open_link_original] opening(
      original,
      p_link_point,
      vk,
      received_root,
      g_link_point
    ) -> (link_value);
    local [__site_19] V: let accepted = CheckExecutionConnections(
      g_cpu_matrix,
      cpu_value,
      g_cpu_claim,
      g_memory_matrix,
      memory_value,
      g_memory_claim,
      g_link_matrix,
      link_value,
      g_link_claim
    );
    return (accepted, after_link);
  }

  instance tau: RandomPoint {
    parameters (rounds = 10);
    roles (P = P, V = V);
  }

  instance outer: CubicSumcheck {
    parameters (rounds = 10);
    roles (P = P, V = V);
  }

  instance inner: ProductSumcheck {
    parameters (rounds = 10);
    roles (P = P, V = V);
  }

  instance opening: OriginalOpening {
    roles (P = P, V = V);
  }

  instance reduce: R1CSReduction {
    parameters (row_rounds = 10, column_rounds = 10);
    dependencies (tau = tau, outer = outer, inner = inner);
    roles (P = P, V = V);
  }

  instance execution: ExecutionProof {
    parameters (row_rounds = 10, column_rounds = 10);
    dependencies (reduce = reduce, opening = opening);
    roles (P = P, V = V);
  }

  entry main = execution;
}
