// Committed linear relation: C = MSM(x, G), A*x = b.
// Generated by evaluation/optimization/linear-relation/generate.py.
// Fixed shape: 3 rows, 4 columns. Every coordinate is guarded.
use zkc::curve::{
  ScalarAction
};
use zkc::algebra::{
  Field,
  Matrix,
  Vector
};
use zkc::algebra;
use zkc::core;
use zkc::curve;
use zkc::random::{
  Rng
};
use zkc::random;
fn LinearCommitAlgorithm<G: domain Group>(
  bases: Vector<G::Element>,
  matrix: Matrix<G::Scalar::Element>,
  entropy: Rng<G::Scalar>
) -> (G::Element, Vector<G::Scalar::Element>, Vector<G::Scalar::Element>, Rng<G::Scalar>) requires (
  ScalarAction(G),
  Field(G::Scalar)
) {
  [shape] let shape = zkc::algebra::matrix_shape_check::<G::Scalar>(matrix) attributes ("3", "4");
  [require_shape] zkc::core::require(shape);
  [mask] let (r, after) = zkc::random::vector::<G::Scalar>(entropy) attributes ("4");
  [commitment] let t = zkc::curve::msm::<G>(r, bases);
  [image] let u = zkc::algebra::matrix_mul_vector::<G::Scalar>(matrix, r);
  return (t, u, r, after);
}
fn LinearRespondAlgorithm<F: domain Field>(
  x: Vector<F::Element>,
  r: Vector<F::Element>,
  c: F::Element
) -> (Vector<F::Element>) requires (Field(F)) {
  [shape] let shape = zkc::algebra::vector_length_check::<F>(x) attributes ("4");
  [require_shape] zkc::core::require(shape);
  [scaled] let scaled = zkc::algebra::vector_scale::<F>(x, c);
  [response] let z = zkc::algebra::vector_add::<F>(r, scaled);
  return (z);
}
fn LinearCheckAlgorithm<G: domain Group>(
  bases: Vector<G::Element>,
  matrix: Matrix<G::Scalar::Element>,
  b: Vector<G::Scalar::Element>,
  commitment: G::Element,
  t: G::Element,
  u: Vector<G::Scalar::Element>,
  c: G::Scalar::Element,
  z: Vector<G::Scalar::Element>
) -> (bool) requires (ScalarAction(G), Field(G::Scalar)) {
  [matrix_shape] let matrix_shape = zkc::algebra::matrix_shape_check::<G::Scalar>(matrix) attributes (
    "3",
    "4"
  );
  [require_matrix_shape] zkc::core::require(matrix_shape);
  [b_shape] let b_shape = zkc::algebra::vector_length_check::<G::Scalar>(b) attributes ("3");
  [require_b_shape] zkc::core::require(b_shape);
  [u_shape] let u_shape = zkc::algebra::vector_length_check::<G::Scalar>(u) attributes ("3");
  [require_u_shape] zkc::core::require(u_shape);
  [z_shape] let z_shape = zkc::algebra::vector_length_check::<G::Scalar>(z) attributes ("4");
  [require_z_shape] zkc::core::require(z_shape);
  // MSM itself requires exactly as many bases as response coordinates.
  [group_left] let group_left = zkc::curve::msm::<G>(z, bases);
  [scaled_commitment] let scaled_commitment = zkc::curve::scale::<G>(commitment, c);
  [group_right] let group_right = zkc::curve::add::<G>(t, scaled_commitment);
  [group_equal] let group_equal = zkc::curve::equal::<G>(group_left, group_right);
  [require_commitment] zkc::core::require(group_equal);
  [matrix_left] let az = zkc::algebra::matrix_mul_vector::<G::Scalar>(matrix, z);
  [scaled_b] let scaled_b = zkc::algebra::vector_scale::<G::Scalar>(b, c);
  [matrix_right] let expected = zkc::algebra::vector_add::<G::Scalar>(u, scaled_b);
  [left_0] let left_0 = zkc::algebra::vector_at::<G::Scalar>(az) attributes ("0");
  [right_0] let right_0 = zkc::algebra::vector_at::<G::Scalar>(expected) attributes ("0");
  [equal_0] let equal_0 = zkc::algebra::equal::<G::Scalar>(left_0, right_0);
  [require_coordinate_0] zkc::core::require(equal_0);
  [left_1] let left_1 = zkc::algebra::vector_at::<G::Scalar>(az) attributes ("1");
  [right_1] let right_1 = zkc::algebra::vector_at::<G::Scalar>(expected) attributes ("1");
  [equal_1] let equal_1 = zkc::algebra::equal::<G::Scalar>(left_1, right_1);
  [require_coordinate_1] zkc::core::require(equal_1);
  [left_2] let left_2 = zkc::algebra::vector_at::<G::Scalar>(az) attributes ("2");
  [right_2] let right_2 = zkc::algebra::vector_at::<G::Scalar>(expected) attributes ("2");
  [equal_2] let equal_2 = zkc::algebra::equal::<G::Scalar>(left_2, right_2);
  [require_coordinate_2] zkc::core::require(equal_2);
  return (group_equal);
}
fn LinearChallengeAlgorithm<F: domain Field>(coins: Rng<F>) -> (F::Element, Rng<F>) requires (
  Field(F)
) {
  [draw] let (c, after) = zkc::random::draw::<F>(coins);
  return (c, after);
}
fn BothAlgorithm<>(first: bool, second: bool) -> (bool) {
  let ok = zkc::core::and(first, second);
  return (ok);
}
configure LinearCommit = LinearCommitAlgorithm(G = "bls12-381.g1");
configure LinearRespond = LinearRespondAlgorithm(F = "bls12-381.fr");
configure LinearCheck = LinearCheckAlgorithm(G = "bls12-381.g1");
configure LinearChallenge = LinearChallengeAlgorithm(F = "bls12-381.fr");
configure Both = BothAlgorithm();
protocol LinearRelation {
  roles (P, V);
  inputs (
    P p_bases: Vector<"bls12-381.g1"::Element>,
    P p_matrix: Matrix<"bls12-381.fr"::Element>,
    P x: Vector<"bls12-381.fr"::Element>,
    P entropy: Rng<"bls12-381.fr">,
    V bases: Vector<"bls12-381.g1"::Element>,
    V matrix: Matrix<"bls12-381.fr"::Element>,
    V b: Vector<"bls12-381.fr"::Element>,
    V commitment: "bls12-381.g1"::Element,
    V coins: Rng<"bls12-381.fr">
  );
  outputs (V bool, V Rng<"bls12-381.fr">, P Rng<"bls12-381.fr">);
  local [commit] P: let (t, u, r, after_entropy) = LinearCommit(p_bases, p_matrix, entropy);
  message [mask_commitment] group: P(t) -> V(received_t);
  message [mask_image] vector: P(u) -> V(received_u);
  local [challenge] V: let (c, after_coins) = LinearChallenge(coins);
  message [challenge_message] field: V(c) -> P(received_c);
  local [respond] P: let z = LinearRespond(x, r, received_c);
  message [response_message] vector: P(z) -> V(received_z);
  local [check] V: let ok = LinearCheck(
    bases,
    matrix,
    b,
    commitment,
    received_t,
    received_u,
    c,
    received_z
  );
  return (ok, after_coins, after_entropy);
}
protocol RepeatedLinearRelation {
  roles (P, V);
  inputs (
    P p_bases: Vector<"bls12-381.g1"::Element>,
    P p_matrix: Matrix<"bls12-381.fr"::Element>,
    P x: Vector<"bls12-381.fr"::Element>,
    P entropy_first: Rng<"bls12-381.fr">,
    P entropy_second: Rng<"bls12-381.fr">,
    V bases: Vector<"bls12-381.g1"::Element>,
    V matrix: Matrix<"bls12-381.fr"::Element>,
    V b: Vector<"bls12-381.fr"::Element>,
    V commitment: "bls12-381.g1"::Element,
    V context: Vector<"bls12-381.fr"::Element>,
    V coins: Rng<"bls12-381.fr">
  );
  outputs (V bool, V Rng<"bls12-381.fr">, P Rng<"bls12-381.fr">, P Rng<"bls12-381.fr">);
  dependencies (argument: LinearRelation());
  invoke [first] argument(
    p_bases,
    p_matrix,
    x,
    entropy_first,
    bases,
    matrix,
    b,
    commitment,
    coins
  ) -> (first_ok, after_first, first_entropy);
  invoke [second] argument(
    p_bases,
    p_matrix,
    x,
    entropy_second,
    bases,
    matrix,
    b,
    commitment,
    after_first
  ) -> (second_ok, after_second, second_entropy);
  local [both] V: let ok = Both(first_ok, second_ok);
  return (ok, after_second, first_entropy, second_entropy);
}
instance argument: LinearRelation {
  roles (P = P, V = V);
}
instance repeated: RepeatedLinearRelation {
  dependencies (argument = argument);
  roles (P = P, V = V);
}
entry main = repeated;
