#ifndef ZKC_DIALECT_DIALECTS_TD
#define ZKC_DIALECT_DIALECTS_TD

include "zkc/Dialect/Protocol/IR/ProtocolDialect.td"
include "zkc/Dialect/Algebra/IR/AlgebraDialect.td"
include "zkc/Dialect/Polynomial/IR/PolynomialDialect.td"
include "zkc/Dialect/Local/IR/LocalDialect.td"
include "zkc/Dialect/Crypto/IR/CryptoDialect.td"
include "zkc/Dialect/Table/IR/TableDialect.td"
include "zkc/Dialect/Plan/IR/PlanDialect.td"
include "zkc/Dialect/PCS/IR/PCSDialect.td"
include "zkc/Dialect/Oracle/IR/OracleDialect.td"
include "zkc/Dialect/Relation/IR/RelationDialect.td"
include "zkc/Dialect/Claim/IR/ClaimDialect.td"

include "zkc/Dialect/Data/IR/DataDialect.td"

#endif
