#ifndef ZKC_DIALECT_TYPES_TD
#define ZKC_DIALECT_TYPES_TD

include "zkc/Dialect/Protocol/IR/ProtocolTypes.td"
include "zkc/Dialect/Algebra/IR/AlgebraTypes.td"
include "zkc/Dialect/Polynomial/IR/PolynomialTypes.td"
include "zkc/Dialect/Local/IR/LocalTypes.td"
include "zkc/Dialect/Data/IR/DataTypes.td"
include "zkc/Dialect/Table/IR/TableTypes.td"
include "zkc/Dialect/Plan/IR/PlanTypes.td"
include "zkc/Dialect/PCS/IR/PCSTypes.td"
include "zkc/Dialect/Oracle/IR/OracleTypes.td"
include "zkc/Dialect/Claim/IR/ClaimTypes.td"

#endif
