# One export per public component lets discovery respect the library graph.
# This helper also serves small installed-consumer fixtures without TableGen.
include(CMakePackageConfigHelpers)

function(zkc_install_sdk)
  cmake_parse_arguments(SDK "" "" "COMPONENTS;TOOLS" ${ARGN})
  if(SDK_UNPARSED_ARGUMENTS OR NOT SDK_COMPONENTS)
    message(FATAL_ERROR "zkc_install_sdk requires component targets")
  endif()
  set(ZKC_SDK_COMPONENTS)
  set(ZKC_SDK_DEPENDENCIES "")
  set(ZKC_SDK_UTF8PROC_VERSION "")
  foreach(target IN LISTS SDK_COMPONENTS)
    get_target_property(name ${target} EXPORT_NAME)
    if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9]*$" OR name STREQUAL "Tools"
        OR name IN_LIST ZKC_SDK_COMPONENTS)
      message(FATAL_ERROR "Invalid or duplicate SDK component: ${name}")
    endif()
    list(APPEND ZKC_SDK_COMPONENTS ${name})
    get_target_property(direct_links ${target} LINK_LIBRARIES)
    if("utf8proc::utf8proc" IN_LIST direct_links)
      set(ZKC_SDK_UTF8PROC_VERSION "${ZKC_UTF8PROC_VERSION}")
    endif()
    get_target_property(links ${target} INTERFACE_LINK_LIBRARIES)
    set(dependencies)
    foreach(link IN LISTS links)
      # Static PRIVATE links remain export requirements, without propagating
      # the dependency's compile usage requirements to consumers.
      if(link MATCHES "^\\$<LINK_ONLY:([^<>]+)>$")
        set(link "${CMAKE_MATCH_1}")
      endif()
      if(TARGET "${link}")
        get_target_property(aliased_target "${link}" ALIASED_TARGET)
        if(aliased_target)
          set(link "${aliased_target}")
        endif()
      elseif(link MATCHES "\\$<")
        foreach(component_target IN LISTS SDK_COMPONENTS)
          if(link MATCHES "(^|[^A-Za-z0-9_])${component_target}([^A-Za-z0-9_]|$)")
            message(FATAL_ERROR "Unsupported SDK component link expression: ${link}")
          endif()
        endforeach()
      endif()
      if(link IN_LIST SDK_COMPONENTS)
        get_target_property(dependency ${link} EXPORT_NAME)
        list(APPEND dependencies ${dependency})
      endif()
    endforeach()
    set(dependencies_${name} ${dependencies})
    string(APPEND ZKC_SDK_DEPENDENCIES
      "set(_zkc_dependencies_${name} ${dependencies})\n")
    install(TARGETS ${target} EXPORT Zkc${name}Targets
      ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
    install(EXPORT Zkc${name}Targets NAMESPACE Zkc:: DESTINATION lib/cmake/ZkcCompiler)
  endforeach()
  if(SDK_TOOLS)
    if(NOT "Driver" IN_LIST ZKC_SDK_COMPONENTS)
      message(FATAL_ERROR "The Tools component requires Driver")
    endif()
    list(APPEND ZKC_SDK_COMPONENTS Tools)
    set(dependencies_Tools Driver)
    string(APPEND ZKC_SDK_DEPENDENCIES "set(_zkc_dependencies_Tools Driver)\n")
    install(TARGETS ${SDK_TOOLS} EXPORT ZkcToolsTargets RUNTIME DESTINATION bin)
    install(EXPORT ZkcToolsTargets NAMESPACE Zkc:: DESTINATION lib/cmake/ZkcCompiler)
  endif()
  # Generated export files check that their referenced targets already exist.
  # Derive a dependency-first import order from the actual core link interfaces.
  set(pending ${ZKC_SDK_COMPONENTS})
  set(ZKC_SDK_COMPONENTS)
  while(pending)
    set(progress FALSE)
    foreach(name IN LISTS pending)
      set(ready TRUE)
      foreach(dependency IN LISTS dependencies_${name})
        if(NOT dependency IN_LIST ZKC_SDK_COMPONENTS)
          set(ready FALSE)
        endif()
      endforeach()
      if(ready)
        list(APPEND ZKC_SDK_COMPONENTS ${name})
        list(REMOVE_ITEM pending ${name})
        set(progress TRUE)
      endif()
    endforeach()
    if(NOT progress)
      message(FATAL_ERROR "Cyclic SDK component dependencies: ${pending}")
    endif()
  endwhile()
  configure_package_config_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/ZkcCompilerConfig.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/ZkcCompilerConfig.cmake"
    INSTALL_DESTINATION lib/cmake/ZkcCompiler)
  install(FILES "${CMAKE_CURRENT_BINARY_DIR}/ZkcCompilerConfig.cmake"
    DESTINATION lib/cmake/ZkcCompiler)
endfunction()
