# Explicit finite build composition. An input artifact never loads these files.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/BuiltinIR.cmake")

# Validate even for standalone assembly, before any contribution is processed.
function(zkc_builtin_inventory classes_output adapters_output)
  if("${zkc_builtin_dialects}" STREQUAL "" OR "${zkc_builtin_type_adapters}" STREQUAL "")
    message(FATAL_ERROR "Missing built-in IR records")
  endif()
  set(names)
  set(owners)
  set(classes)
  foreach(record IN LISTS zkc_builtin_dialects)
    if(NOT record MATCHES "^([a-z][a-z0-9_]*)[|]([A-Za-z_][A-Za-z0-9_]*)[|](types|none)$")
      message(FATAL_ERROR "Malformed built-in dialect record: ${record}")
    endif()
    set(name "${CMAKE_MATCH_1}")
    set(owner "${CMAKE_MATCH_2}")
    if(name IN_LIST names OR owner IN_LIST owners)
      message(FATAL_ERROR "Duplicate built-in dialect record: ${record}")
    endif()
    list(APPEND names "${name}")
    list(APPEND owners "${owner}")
    list(APPEND classes "::zkc::${owner}Dialect")
  endforeach()
  set(owners)
  set(outputs Installed)
  foreach(record IN LISTS zkc_builtin_type_adapters)
    if(NOT record MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[|]([A-Za-z_][A-Za-z0-9_]*)$")
      message(FATAL_ERROR "Malformed built-in adapter record: ${record}")
    endif()
    set(owner "${CMAKE_MATCH_1}")
    set(output "${CMAKE_MATCH_2}")
    if(owner IN_LIST owners OR output IN_LIST outputs)
      message(FATAL_ERROR "Duplicate built-in adapter record: ${record}")
    endif()
    list(APPEND owners "${owner}")
    list(APPEND outputs "${output}")
  endforeach()
  set(${classes_output} "${classes}" PARENT_SCOPE)
  set(${adapters_output} "${owners};${outputs}" PARENT_SCOPE)
endfunction()

function(zkc_contribution_path path output)
  # REALPATH alone leaves nonexistent generated outputs unresolved. Resolve
  # their nearest existing parent too, including symlinked include roots.
  set(parent "${path}")
  set(suffix "")
  while(NOT EXISTS "${parent}")
    if(IS_SYMLINK "${parent}")
      message(FATAL_ERROR "Unresolved contribution path symlink: ${parent}")
    endif()
    get_filename_component(leaf "${parent}" NAME)
    get_filename_component(parent "${parent}" DIRECTORY)
    set(suffix "/${leaf}${suffix}")
  endwhile()
  get_filename_component(parent "${parent}" REALPATH)
  set(path "${parent}${suffix}")
  foreach(area include lib)
    get_filename_component(core "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../${area}" REALPATH)
    file(RELATIVE_PATH relative "${core}" "${path}")
    if(NOT IS_ABSOLUTE "${relative}" AND NOT relative MATCHES "^\\.\\.(/|$)")
      message(FATAL_ERROR "Contribution cannot own core files: ${path}")
    endif()
  endforeach()
  set(${output} "${path}" PARENT_SCOPE)
endfunction()

# This checks the visible imported link interface at component assembly time,
# not arbitrary CMake execution or the contents of an external binary. Both
# build/install wrapper branches are checked; unsupported expressions refuse.
function(zkc_check_external_link_list links visited output)
  set(item "")
  set(depth 0)
  set(previous "")
  string(LENGTH "${links}" length)
  # Split only at top-level semicolons: a wrapper can contain a list of links.
  # The final synthetic separator flushes the last item.
  foreach(index RANGE 0 ${length})
    if(index EQUAL length)
      set(character ";")
    else()
      string(SUBSTRING "${links}" ${index} 1 character)
    endif()
    if(character STREQUAL "<" AND previous STREQUAL "$")
      math(EXPR depth "${depth} + 1")
    elseif(character STREQUAL ">")
      math(EXPR depth "${depth} - 1")
      if(depth LESS 0)
        message(FATAL_ERROR "Unsupported contribution external link interface: ${links}")
      endif()
    endif()
    if(character STREQUAL ";" AND depth EQUAL 0)
      if(NOT item STREQUAL "")
        zkc_check_external_link("${item}" "${visited}" visited)
      endif()
      set(item "")
    else()
      string(APPEND item "${character}")
    endif()
    set(previous "${character}")
  endforeach()
  if(NOT depth EQUAL 0)
    message(FATAL_ERROR "Unsupported contribution external link interface: ${links}")
  endif()
  set(${output} "${visited}" PARENT_SCOPE)
endfunction()

function(zkc_check_external_link link visited output)
  if(link MATCHES "^\\$<(LINK_ONLY|BUILD_INTERFACE|INSTALL_INTERFACE):(.*)>$")
    zkc_check_external_link_list("${CMAKE_MATCH_2}" "${visited}" visited)
  elseif(link MATCHES "^\\$<\\$<CONFIG:[A-Za-z0-9_,]+>:(.*)>$")
    zkc_check_external_link_list("${CMAKE_MATCH_1}" "${visited}" visited)
  elseif(link MATCHES "^\\$<\\$<NOT:\\$<CONFIG:[A-Za-z0-9_,]+>>:(.*)>$")
    zkc_check_external_link_list("${CMAKE_MATCH_1}" "${visited}" visited)
  else()
    if(IS_ABSOLUTE "${link}")
      if(NOT EXISTS "${link}" OR IS_DIRECTORY "${link}" OR link MATCHES "\\$<")
        message(FATAL_ERROR "Invalid contribution external library file: ${link}")
      endif()
      get_filename_component(library_name "${link}" REALPATH)
      get_filename_component(library_name "${library_name}" NAME)
      if(library_name MATCHES "^(lib)?(Zkc|LLVM|MLIR)")
        message(FATAL_ERROR "Contribution external library reaches a reserved target: ${link}")
      endif()
      set(${output} "${visited}" PARENT_SCOPE)
      return()
    endif()
    if(link MATCHES "^-l([A-Za-z_][A-Za-z0-9_.+-]*)$")
      set(link "${CMAKE_MATCH_1}")
    endif()
    # Bare platform libraries (m, dl, pthread, etc.) and the common Threads
    # flag are allowed transitively. Registration itself requires a target.
    if(NOT link MATCHES "^[A-Za-z_][A-Za-z0-9_.:+-]*$" AND NOT link STREQUAL "-pthread")
      message(FATAL_ERROR "Unsupported contribution external link interface: ${link}")
    endif()
    if(link MATCHES "^(Zkc|LLVM|MLIR)")
      message(FATAL_ERROR "Contribution external library reaches a reserved target: ${link}")
    endif()
    if(TARGET "${link}")
      get_target_property(aliased "${link}" ALIASED_TARGET)
      if(aliased)
        set(link "${aliased}")
      endif()
      if(link MATCHES "^(Zkc|LLVM|MLIR)")
        message(FATAL_ERROR "Contribution external library reaches a reserved target: ${link}")
      endif()
      get_target_property(imported "${link}" IMPORTED)
      if(NOT imported)
        message(FATAL_ERROR "Contribution external library must be IMPORTED: ${link}; register owned sources with IR_SOURCES or TRANSFORM_SOURCES")
      endif()
      if(NOT link IN_LIST visited)
        list(APPEND visited "${link}")
        # Imported target aliases must not hide an explicitly named core
        # binary in their visible location metadata. This is not a binary audit.
        get_target_property(configurations "${link}" IMPORTED_CONFIGURATIONS)
        set(locations IMPORTED_LOCATION IMPORTED_IMPLIB)
        foreach(configuration IN LISTS configurations)
          string(TOUPPER "${configuration}" configuration)
          list(APPEND locations "IMPORTED_LOCATION_${configuration}" "IMPORTED_IMPLIB_${configuration}")
        endforeach()
        foreach(property IN LISTS locations)
          get_target_property(location "${link}" "${property}")
          if(location AND NOT location MATCHES "\\$<")
            if(EXISTS "${location}")
              get_filename_component(location "${location}" REALPATH)
            endif()
            get_filename_component(location "${location}" NAME)
            if(location MATCHES "^(lib)?(Zkc|LLVM|MLIR)")
              message(FATAL_ERROR "Contribution imported location reaches a reserved library: ${link}: ${location}")
            endif()
          endif()
        endforeach()
        get_target_property(interface "${link}" INTERFACE_LINK_LIBRARIES)
        if(NOT interface STREQUAL "interface-NOTFOUND")
          zkc_check_external_link_list("${interface}" "${visited}" visited)
        endif()
      endif()
    elseif(link MATCHES "::")
      message(FATAL_ERROR "Contribution external library target is not visible: ${link}")
    endif()
  endif()
  set(${output} "${visited}" PARENT_SCOPE)
endfunction()

function(zkc_validate_contribution_libraries)
  set(visited)
  foreach(link IN LISTS ZKC_CONTRIBUTION_LIBRARIES ZKC_CONTRIBUTION_TRANSFORM_LIBRARIES ZKC_CONTRIBUTION_PUBLIC_LIBRARIES ZKC_CONTRIBUTION_PUBLIC_TRANSFORM_LIBRARIES)
    if(NOT TARGET "${link}")
      message(FATAL_ERROR "Contribution external library must name an IMPORTED target: ${link}")
    endif()
    zkc_check_external_link("${link}" "${visited}" visited)
  endforeach()
endfunction()

# Keep link visibility identical for the compiler and installed-package probes.
function(zkc_link_contribution_libraries)
  zkc_validate_contribution_libraries()
  target_link_libraries(ZkcIR PRIVATE ${ZKC_CONTRIBUTION_LIBRARIES})
  target_link_libraries(ZkcIR PUBLIC ${ZKC_CONTRIBUTION_PUBLIC_LIBRARIES})
  target_link_libraries(ZkcTransforms PRIVATE ${ZKC_CONTRIBUTION_TRANSFORM_LIBRARIES})
  target_link_libraries(ZkcTransforms PUBLIC ${ZKC_CONTRIBUTION_PUBLIC_TRANSFORM_LIBRARIES})
endfunction()

function(zkc_add_contribution)
  # PUBLIC_HEADERS names generated .h.inc outputs under an include root;
  # GENERATED_SOURCES names uninstalled .cpp.inc outputs. Both are registered
  # before generation. Existing .h/.td files are inventoried automatically.
  # Public headers belong to IR unless listed in TRANSFORM_HEADERS. HEADERS is
  # the narrower set included by the central dialect registry.
  # External libraries are assigned to IR by LINK_LIBRARIES, or to Transforms
  # by TRANSFORM_LINK_LIBRARIES. Components.cmake validates imported targets
  # and their visible link interfaces after defining all core targets.
  cmake_parse_arguments(PARSE_ARGV 0 contribution "" "NAME;DECLARATIONS;BINDINGS"
    "DEPENDS;FIND_DEPENDENCIES;PUBLIC_LINK_LIBRARIES;PUBLIC_TRANSFORM_LINK_LIBRARIES;IR_SOURCES;TRANSFORM_SOURCES;LINK_LIBRARIES;TRANSFORM_LINK_LIBRARIES;INCLUDE_DIRECTORIES;PUBLIC_HEADERS;PRIVATE_HEADERS;GENERATED_SOURCES;TRANSFORM_HEADERS;HEADERS;DIALECT_CLASSES;ADAPTER_OWNERS;GENERATION_TARGETS")
  if(DEFINED contribution_UNPARSED_ARGUMENTS OR DEFINED contribution_KEYWORDS_MISSING_VALUES OR
     NOT contribution_NAME MATCHES "^[A-Za-z0-9_.-]+$" OR
     contribution_NAME STREQUAL "base")
    message(FATAL_ERROR "Invalid zkc contribution arguments")
  endif()
  get_property(names GLOBAL PROPERTY ZKC_CONTRIBUTION_NAMES)
  if(contribution_NAME IN_LIST names)
    message(FATAL_ERROR "Duplicate zkc contribution: ${contribution_NAME}")
  endif()
  foreach(kind DECLARATIONS BINDINGS)
    if(NOT contribution_${kind})
      message(FATAL_ERROR "Contribution ${contribution_NAME} requires ${kind}")
    endif()
    get_filename_component(path "${contribution_${kind}}" ABSOLUTE
      BASE_DIR "${CMAKE_CURRENT_LIST_DIR}")
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "Missing ${kind} fragment: ${path}")
    endif()
    zkc_contribution_path("${path}" path)
    set_property(GLOBAL PROPERTY "ZKC_CONTRIBUTION_${contribution_NAME}_${kind}" "${path}")
  endforeach()
  foreach(kind IR_SOURCES TRANSFORM_SOURCES INCLUDE_DIRECTORIES PUBLIC_HEADERS PRIVATE_HEADERS GENERATED_SOURCES TRANSFORM_HEADERS)
    set(paths)
    foreach(path IN LISTS contribution_${kind})
      get_filename_component(path "${path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_LIST_DIR}")
      if(NOT kind MATCHES "^(PUBLIC_HEADERS|GENERATED_SOURCES|TRANSFORM_HEADERS)$" AND NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing contribution ${kind}: ${path}")
      endif()
      zkc_contribution_path("${path}" path)
      if(path MATCHES "[|;\\\"\n\r]" OR path MATCHES "\\$<")
        message(FATAL_ERROR "Unsupported contribution path: ${path}")
      endif()
      list(APPEND paths "${path}")
    endforeach()
    set_property(GLOBAL PROPERTY "ZKC_CONTRIBUTION_${contribution_NAME}_${kind}" "${paths}")
  endforeach()
  foreach(kind DEPENDS FIND_DEPENDENCIES PUBLIC_LINK_LIBRARIES PUBLIC_TRANSFORM_LINK_LIBRARIES LINK_LIBRARIES TRANSFORM_LINK_LIBRARIES HEADERS DIALECT_CLASSES ADAPTER_OWNERS GENERATION_TARGETS)
    set_property(GLOBAL PROPERTY "ZKC_CONTRIBUTION_${contribution_NAME}_${kind}" "${contribution_${kind}}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY ZKC_CONTRIBUTION_NAMES "${contribution_NAME}")
endfunction()

function(zkc_assemble_contributions output_directory)
  zkc_builtin_inventory(builtin_classes builtin_adapters)
  get_property(pending GLOBAL PROPERTY ZKC_CONTRIBUTION_NAMES)
  list(SORT pending)
  foreach(name IN LISTS pending)
    get_property(dependencies GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_DEPENDS")
    foreach(dependency IN LISTS dependencies)
      if(NOT dependency STREQUAL "base" AND NOT dependency IN_LIST pending)
        message(FATAL_ERROR "Missing zkc contribution dependency ${dependency} for ${name}")
      endif()
    endforeach()
  endforeach()
  set(ordered)
  set(installed base)
  while(NOT "${pending}" STREQUAL "")
    set(next)
    foreach(name IN LISTS pending)
      get_property(dependencies GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_DEPENDS")
      set(ready TRUE)
      foreach(dependency IN LISTS dependencies)
        if(NOT dependency IN_LIST installed)
          set(ready FALSE)
        endif()
      endforeach()
      if(ready)
        set(next "${name}")
        break()
      endif()
    endforeach()
    if("${next}" STREQUAL "")
      message(FATAL_ERROR "Cyclic zkc contribution dependencies: ${pending}")
    endif()
    list(APPEND ordered "${next}")
    list(APPEND installed "${next}")
    list(REMOVE_ITEM pending "${next}")
  endwhile()

  set(neutral "#ifndef ZKC_INSTALLATION_DECLARATIONS\n#define ZKC_INSTALLATION_DECLARATIONS\ninclude \"zkc/Contracts/Declarations/Schema.td\"\ndefset list<ZKC_Declaration> ZkcBaseRecords = {\ninclude \"zkc/Contracts/Declarations.td\"\n}\ndef ZkcBaseContribution : ZKC_Contribution<\"base\", [], ZkcBaseRecords>;\n")
  set(native "include \"zkc/Contracts/Installation.td\"\ninclude \"zkc/Dialect/InstalledTypeBindings.td\"\n")
  set(sources)
  set(transform_sources)
  set(libraries)
  set(transform_libraries)
  set(public_libraries)
  set(public_transform_libraries)
  set(find_dependencies)
  set(public_header_files)
  set(public_header_paths)
  set(ownership "")
  set(includes)
  set(headers)
  set(classes)
  set(adapters)
  set(generation_targets)
  # New or removed source headers must update the finite install inventory on
  # the next build. Script-mode admission probes have no build regeneration.
  set(inventory_watch)
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set(inventory_watch CONFIGURE_DEPENDS)
  endif()
  # Reserve the entire core namespace, including outputs absent on a clean
  # configure. Only central generators may emit zkc/ adapter fragments.
  # The same finite inventory drives installation and dependency checks.
  foreach(name IN LISTS ordered)
    get_property(dependencies GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_DEPENDS")
    foreach(dependency IN LISTS dependencies)
      string(APPEND ownership "DEPENDENCY|${name}|ZkcIR|${dependency}|\n")
    endforeach()
    foreach(kind INCLUDE_DIRECTORIES PUBLIC_HEADERS PRIVATE_HEADERS GENERATED_SOURCES TRANSFORM_HEADERS)
      get_property(${kind} GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_${kind}")
    endforeach()
    set(entries ${PUBLIC_HEADERS} ${GENERATED_SOURCES} ${PRIVATE_HEADERS})
    foreach(directory IN LISTS INCLUDE_DIRECTORIES)
      file(GLOB_RECURSE found ${inventory_watch} FOLLOW_SYMLINKS
        "${directory}/*.h" "${directory}/*.hpp" "${directory}/*.def" "${directory}/*.td" "${directory}/*.inc")
      foreach(path IN LISTS found)
        # Generated outputs come only from the declared lists. Old files left
        # in a reused build directory must neither enter the inventory nor
        # prevent reconfiguration when an output is renamed.
        if(path MATCHES "[.](h|cpp)[.]inc$")
          continue()
        endif()
        list(APPEND entries "${path}")
      endforeach()
    endforeach()
    list(REMOVE_DUPLICATES entries)
    foreach(path IN LISTS TRANSFORM_HEADERS)
      if(NOT path IN_LIST entries OR NOT path MATCHES "[.](h|hpp|def|inc)$")
        message(FATAL_ERROR "TRANSFORM_HEADERS must name inventoried headers or generated sources: ${path}")
      endif()
    endforeach()
    foreach(path IN LISTS entries)
      if(path IN_LIST PRIVATE_HEADERS)
        if(NOT path MATCHES "[.](h|hpp|def|inc)$" OR path IN_LIST PUBLIC_HEADERS OR path IN_LIST GENERATED_SOURCES)
          message(FATAL_ERROR "PRIVATE_HEADERS must name private source headers: ${path}")
        endif()
        foreach(directory IN LISTS INCLUDE_DIRECTORIES)
          file(RELATIVE_PATH relative "${directory}" "${path}")
          if(NOT IS_ABSOLUTE "${relative}" AND NOT relative MATCHES "^\\.\\.(/|$)")
            message(FATAL_ERROR "Private contribution header is inside a public include root: ${path}")
          endif()
        endforeach()
        string(SHA256 key "${path}")
        if(DEFINED source_${key} OR DEFINED header_physical_${key})
          message(FATAL_ERROR "Multiple contribution source owners: ${path}")
        endif()
        set(source_${key} "${name}")
        set(owner ZkcIR)
        if(path IN_LIST TRANSFORM_HEADERS)
          set(owner ZkcTransforms)
        endif()
        string(APPEND ownership "PRIVATE|${name}|${owner}|${path}|\n")
        continue()
      endif()
      set(entry)
      foreach(directory IN LISTS INCLUDE_DIRECTORIES)
        file(RELATIVE_PATH relative "${directory}" "${path}")
        if(NOT IS_ABSOLUTE "${relative}" AND NOT relative MATCHES "^\\.\\.(/|$)")
          if(entry AND NOT entry STREQUAL relative)
            message(FATAL_ERROR "Ambiguous installed contribution path: ${path}")
          endif()
          set(entry "${relative}")
        endif()
      endforeach()
      if(NOT entry OR entry MATCHES "[|;\\\"\n\r]" OR entry MATCHES "\\$<")
        message(FATAL_ERROR "Contribution file must belong to one include root: ${path}")
      endif()
      # Preserve the public spelling even when it is a symlink. The physical
      # file is used for ownership and installation, with the public basename.
      zkc_contribution_path("${path}" path)
      if(entry MATCHES "^zkc(/|$)")
        message(FATAL_ERROR "Reserved core include namespace: ${entry}")
      endif()
      if(path IN_LIST PUBLIC_HEADERS AND NOT path MATCHES "[.]h[.]inc$")
        message(FATAL_ERROR "PUBLIC_HEADERS requires generated .h.inc paths: ${path}")
      endif()
      if(path IN_LIST GENERATED_SOURCES AND NOT path MATCHES "[.]cpp[.]inc$")
        message(FATAL_ERROR "GENERATED_SOURCES requires generated .cpp.inc paths: ${path}")
      endif()
      string(SHA256 key "${entry}")
      if(DEFINED installed_${key} AND NOT installed_${key} STREQUAL path)
        message(FATAL_ERROR "Conflicting installed contribution path: ${entry}")
      endif()
      if(DEFINED installed_${key})
        message(FATAL_ERROR "Multiple contribution header owners: ${entry}")
      endif()
      set(installed_${key} "${path}")
      set(owner ZkcIR)
      if(path IN_LIST TRANSFORM_HEADERS)
        set(owner ZkcTransforms)
      endif()
      set(header_owner_${key} "${owner}")
      set(header_package_${key} "${name}")
      set(kind HEADER)
      if(path IN_LIST GENERATED_SOURCES)
        set(kind GENERATED)
      else()
        list(APPEND public_header_files "${path}")
        list(APPEND public_header_paths "${entry}")
      endif()
      string(SHA256 physical_key "${path}")
      set(physical_owner "${name}|${owner}|${kind}")
      if(DEFINED source_${physical_key})
        message(FATAL_ERROR "Contribution public header aliases a private implementation: ${path}")
      endif()
      if(DEFINED header_physical_${physical_key} AND NOT header_physical_${physical_key} STREQUAL physical_owner)
        message(FATAL_ERROR "Multiple contribution header owners: ${path}")
      endif()
      set(header_physical_${physical_key} "${physical_owner}")
      string(APPEND ownership "${kind}|${name}|${owner}|${path}|${entry}\n")
    endforeach()
    foreach(kind IR_SOURCES TRANSFORM_SOURCES)
      get_property(paths GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_${kind}")
      set(owner ZkcIR)
      if(kind STREQUAL "TRANSFORM_SOURCES")
        set(owner ZkcTransforms)
      endif()
      foreach(path IN LISTS paths)
        string(SHA256 key "${path}")
        if(DEFINED source_${key})
          message(FATAL_ERROR "Multiple contribution source owners: ${path}")
        endif()
        set(source_${key} "${name}")
        string(APPEND ownership "SOURCE|${name}|${owner}|${path}|\n")
      endforeach()
    endforeach()
    foreach(kind LINK_LIBRARIES TRANSFORM_LINK_LIBRARIES PUBLIC_LINK_LIBRARIES PUBLIC_TRANSFORM_LINK_LIBRARIES)
      get_property(links GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_${kind}")
      set(owner ZkcIR)
      if(kind MATCHES "TRANSFORM_LINK_LIBRARIES$")
        set(owner ZkcTransforms)
      endif()
      foreach(link IN LISTS links)
        # Core/LLVM/MLIR layering remains governed by Components.cmake.
        # These are registration names only. Components.cmake later requires
        # imported targets and checks their visible transitive link interfaces.
        if(NOT link MATCHES "^[A-Za-z_][A-Za-z0-9_.:+-]*$" OR link MATCHES "^(Zkc|LLVM|MLIR)")
          message(FATAL_ERROR "Invalid contribution external library: ${link}")
        endif()
        string(APPEND ownership "LIBRARY|${name}|${owner}|${link}|\n")
      endforeach()
    endforeach()
  endforeach()
  set(index 0)
  foreach(name IN LISTS ordered)
    foreach(kind DECLARATIONS BINDINGS DEPENDS FIND_DEPENDENCIES PUBLIC_LINK_LIBRARIES PUBLIC_TRANSFORM_LINK_LIBRARIES IR_SOURCES TRANSFORM_SOURCES LINK_LIBRARIES TRANSFORM_LINK_LIBRARIES INCLUDE_DIRECTORIES HEADERS DIALECT_CLASSES ADAPTER_OWNERS GENERATION_TARGETS)
      get_property(${kind} GLOBAL PROPERTY "ZKC_CONTRIBUTION_${name}_${kind}")
    endforeach()
    set(dependencies "[\"base\"")
    foreach(dependency IN LISTS DEPENDS)
      if(NOT dependency STREQUAL "base")
        string(APPEND dependencies ", \"${dependency}\"")
      endif()
    endforeach()
    string(APPEND dependencies "]")
    foreach(path IN ITEMS "${DECLARATIONS}" "${BINDINGS}")
      if(path MATCHES "[\"\\\\\n\r]")
        message(FATAL_ERROR "Unsupported TableGen include path: ${path}")
      endif()
    endforeach()
    # Aggregates are installed data. Keep include paths relative to an explicit
    # installed include root, never to a checkout or build directory.
    foreach(kind DECLARATIONS BINDINGS)
      set(installed_path)
      foreach(directory IN LISTS INCLUDE_DIRECTORIES)
        file(RELATIVE_PATH relative "${directory}" "${${kind}}")
        if(NOT IS_ABSOLUTE "${relative}" AND NOT relative MATCHES "^\\.\\.(/|$)")
          set(installed_path "${relative}")
          break()
        endif()
      endforeach()
      if(NOT installed_path)
        message(FATAL_ERROR "Contribution ${kind} must belong to an INCLUDE_DIRECTORIES root: ${${kind}}")
      endif()
      string(SHA256 key "${installed_path}")
      if(NOT installed_path MATCHES "[.]td$" OR NOT header_package_${key} STREQUAL name)
        message(FATAL_ERROR "Contribution ${kind} must name an owned .td fragment: ${installed_path}")
      endif()
      set(${kind} "${installed_path}")
    endforeach()
    string(APPEND neutral "defset list<ZKC_Declaration> ZkcContributionRecords${index} = {\ninclude \"${DECLARATIONS}\"\n}\ndef ZkcContribution${index} : ZKC_Contribution<\"${name}\", ${dependencies}, ZkcContributionRecords${index}>;\n")
    string(APPEND native "include \"${BINDINGS}\"\n")
    list(APPEND sources ${IR_SOURCES})
    list(APPEND transform_sources ${TRANSFORM_SOURCES})
    foreach(package IN LISTS FIND_DEPENDENCIES)
      if(NOT package MATCHES "^[A-Za-z_][A-Za-z0-9_.+-]*$" OR package MATCHES "^(Zkc|LLVM|MLIR)")
        message(FATAL_ERROR "Invalid contribution dependency package: ${package}")
      endif()
      list(APPEND find_dependencies "${package}")
    endforeach()
    list(APPEND public_libraries ${PUBLIC_LINK_LIBRARIES})
    list(APPEND public_transform_libraries ${PUBLIC_TRANSFORM_LINK_LIBRARIES})
    list(APPEND libraries ${LINK_LIBRARIES})
    list(APPEND transform_libraries ${TRANSFORM_LINK_LIBRARIES})
    list(APPEND includes ${INCLUDE_DIRECTORIES})
    foreach(header IN LISTS HEADERS)
      if(header MATCHES "[\"\\\\\n\r]" OR IS_ABSOLUTE "${header}" OR header MATCHES "(^|/)\\.\\.(/|$)")
        message(FATAL_ERROR "Contribution header must be an installed include path: ${header}")
      endif()
      string(SHA256 key "${header}")
      if(NOT DEFINED installed_${key} OR NOT header_owner_${key} STREQUAL "ZkcIR" OR NOT header_package_${key} STREQUAL name OR NOT header MATCHES "[.](h|hpp|h[.]inc)$")
        message(FATAL_ERROR "Contribution HEADERS must name an owned IR header: ${header}")
      endif()
      string(APPEND headers "#include \"${header}\"\n")
    endforeach()
    foreach(dialect IN LISTS DIALECT_CLASSES)
      if(NOT dialect MATCHES "^::[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)+$" OR dialect IN_LIST classes OR dialect IN_LIST builtin_classes)
        message(FATAL_ERROR "Invalid or duplicate contribution dialect class: ${dialect}")
      endif()
      list(APPEND classes "${dialect}")
    endforeach()
    foreach(adapter IN LISTS ADAPTER_OWNERS)
      if(NOT adapter MATCHES "^[A-Za-z_][A-Za-z0-9_]*$" OR adapter IN_LIST adapters OR adapter IN_LIST builtin_adapters)
        message(FATAL_ERROR "Invalid or duplicate contribution adapter owner: ${adapter}")
      endif()
      list(APPEND adapters "${adapter}")
    endforeach()
    list(APPEND generation_targets ${GENERATION_TARGETS})
    math(EXPR index "${index} + 1")
  endforeach()
  string(APPEND neutral "#endif\n")
  file(MAKE_DIRECTORY "${output_directory}/zkc/Contracts" "${output_directory}/zkc/Dialect")
  file(CONFIGURE OUTPUT "${output_directory}/zkc/Contracts/Installation.td" CONTENT "${neutral}" @ONLY)
  file(CONFIGURE OUTPUT "${output_directory}/zkc/Dialect/Installation.td" CONTENT "${native}" @ONLY)
  file(CONFIGURE OUTPUT "${output_directory}/zkc/Dialect/ContributionHeaders.h.inc" CONTENT "${headers}" @ONLY)
  set(registry "")
  foreach(dialect IN LISTS classes)
    string(APPEND registry ", ${dialect}")
  endforeach()
  file(CONFIGURE OUTPUT "${output_directory}/zkc/Dialect/ContributionDialects.inc" CONTENT "${registry}\n" @ONLY)
  file(CONFIGURE OUTPUT "${output_directory}/../contribution-dependencies.txt" CONTENT "${ownership}" @ONLY)
  list(REMOVE_DUPLICATES find_dependencies)
  list(SORT find_dependencies)
  set(dependency_calls "")
  foreach(package IN LISTS find_dependencies)
    string(APPEND dependency_calls "find_dependency(${package})\n")
  endforeach()
  set(ZKC_CONTRIBUTION_FIND_DEPENDENCIES "${dependency_calls}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_PUBLIC_LIBRARIES "${public_libraries}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_PUBLIC_TRANSFORM_LIBRARIES "${public_transform_libraries}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_PUBLIC_HEADER_FILES "${public_header_files}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_PUBLIC_HEADER_PATHS "${public_header_paths}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_TRANSFORM_LIBRARIES "${transform_libraries}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_SOURCES "${sources}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_TRANSFORM_SOURCES "${transform_sources}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_LIBRARIES "${libraries}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_INCLUDES "${includes}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_ADAPTER_OWNERS "${adapters}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTION_GENERATION_TARGETS "${generation_targets}" PARENT_SCOPE)
  set(ZKC_CONTRIBUTIONS "${ordered}" PARENT_SCOPE)
endfunction()
