use serde_json::{Value as Json, json};
use zkc_tools::artifact::primitive::{parse_request, respond};

fn scalar(n: u64) -> Json {
    let mut bytes = b"ZKCV\x01\x01".to_vec();
    bytes.extend(n.to_le_bytes());
    bytes.extend([0; 24]);
    json!(["field:bls12-381.fr", zkc_test_support::hex(&bytes)])
}
fn group(point: zkc_arkworks::GroupPoint) -> Json {
    let mut bytes = b"ZKCV\x01\x09".to_vec();
    bytes.extend(point.to_bytes().unwrap());
    json!(["group:bls12-381.g1", zkc_test_support::hex(&bytes)])
}
fn operation(name: &str, attrs: Json, values: Json) -> Json {
    json!([
        "zkc.public-primitive/1",
        [],
        name,
        if name == "validate" {
            json!([])
        } else {
            json!(["bls12-381.g1"])
        },
        attrs,
        values
    ])
}

#[test]
fn full_request_service_matches_independent_transcript_known_answer() {
    let fixture: Json = serde_json::from_str(
        &std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../tests/fixtures/transcript-kat.json"
        ))
        .expect("frozen transcript KAT fixture must be present"),
    )
    .unwrap();
    // Replay the frozen, independently generated bytes through the current
    // raw Merlin service. The old origin bytes are evidence, not parsed source.
    let request = json!([
        "zkc.transcript-request/3",
        "merlin3.bls12-381.fr64be/1",
        zkc_test_support::hex(b"zkc.artifact/1"),
        [
            [
                "append",
                zkc_test_support::hex(b"binding"),
                fixture["root_hex"]
            ],
            [
                "append",
                zkc_test_support::hex(b"origin"),
                fixture["message_origin_hex"]
            ],
            [
                "append",
                zkc_test_support::hex(b"value"),
                fixture["public_wire_hex"]
            ],
            [
                "append",
                zkc_test_support::hex(b"origin"),
                fixture["challenge_origin_hex"]
            ],
            ["challenge", zkc_test_support::hex(b"challenge"), "64"]
        ]
    ]);
    let answer = respond(&request).unwrap();
    assert_eq!(answer, json!(["ok", fixture["challenge_raw_hex"]]));
    let raw = answer[1]
        .as_str()
        .unwrap()
        .as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|p| u8::from_str_radix(std::str::from_utf8(p).unwrap(), 16).unwrap())
        .collect::<Vec<_>>();
    let scalar = zkc_arkworks::scalar_from_wide_be(&raw.try_into().unwrap());
    assert_eq!(
        zkc_test_support::hex(&zkc_arkworks::encode_scalar(&scalar).unwrap()),
        fixture["challenge_fr_le_hex"]
    );
    let mut changed = request.clone();
    changed[3][0][2] = json!("00");
    assert_ne!(respond(&changed).unwrap(), answer);
    changed = request.clone();
    changed[3].as_array_mut().unwrap().reverse();
    assert_eq!(respond(&changed), Err("primitive-history-last"));
    changed = request.clone();
    changed[3]
        .as_array_mut()
        .unwrap()
        .insert(4, request[3][4].clone());
    assert_ne!(respond(&changed).unwrap(), answer);
    assert_eq!(
        respond(&json!(["zkc.hash/1", "sha256", "616263"])).unwrap(),
        json!("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
    );
}

#[test]
fn service_checks_real_public_equations_and_refuses_private_operations() {
    use zkc_arkworks::{GroupPoint, Scalar};
    let base = GroupPoint::generator();
    let request = operation("curve.scale", json!([]), json!([group(base), scalar(17)]));
    assert_eq!(
        respond(&request).unwrap(),
        json!(["ok", group(base.scale(Scalar::from(17)))])
    );
    let false_equation = operation(
        "curve.equal",
        json!([]),
        json!([group(base), group(base.scale(Scalar::from(2)))]),
    );
    assert_eq!(
        respond(&false_equation).unwrap(),
        json!(["ok", ["bool", "5a4b4356010500"]])
    );
    for name in [
        "curve.commit",
        "curve.response",
        "random.draw",
        "pcs.open",
        "verify_protocol",
    ] {
        assert_eq!(
            respond(&operation(name, json!([]), json!([]))).unwrap()[0],
            "error"
        );
    }
    let mut wrong_domain = request;
    wrong_domain[3] = json!(["reference.additive.bls12-381.fr/1"]);
    assert_eq!(respond(&wrong_domain).unwrap()[0], "error");
    let mut noncanonical = group(base);
    noncanonical[1] = json!(format!("{}00", noncanonical[1].as_str().unwrap()));
    assert_eq!(
        respond(&operation("validate", json!([]), json!([noncanonical]))).unwrap()[0],
        "error"
    );
    assert_eq!(
        respond(&operation("curve.at", json!(["00"]), json!([]))).unwrap()[0],
        "error"
    );
    assert!(parse_request(b"[[[").is_err());
    assert!(respond(&json!(["zkc.hash/1", "sha256", "AB"])).is_err());
}

#[test]
fn public_pcs_service_uses_expected_key_and_complete_operands() {
    use zkc_arkworks::{Bounds, Keys, Scalar, Table, encode_scalar};
    let bounds = Bounds::new(4, 16, 1 << 20, 1024);
    let keys = Keys::setup_for_development(2, &bounds).unwrap();
    let table = Table::from_logical(&[2u64, 3, 5, 7].map(Scalar::from), &bounds).unwrap();
    let committed = keys.prover_key().commit(&table).unwrap();
    let point = [11u64, 13].map(Scalar::from);
    let (value, proof) = committed.open(&point).unwrap();
    let envelope = |kind, tag, payload: &[u8]| {
        let mut bytes = b"ZKCV\x01".to_vec();
        bytes.push(tag);
        bytes.extend(payload);
        json!([kind, zkc_test_support::hex(&bytes)])
    };
    let key = keys.verifier_key().to_bytes(&bounds).unwrap();
    let mut point_bytes = 2u32.to_le_bytes().to_vec();
    for r in point {
        point_bytes.extend(encode_scalar(&r).unwrap());
    }
    let request = json!([
        "zkc.public-primitive/1",
        [[
            "vk",
            "verifier_key:multilinear.kzg.bls12-381/1",
            zkc_test_support::hex(&key)
        ]],
        "pcs.check",
        ["multilinear.kzg.bls12-381/1"],
        [],
        [
            [
                "verifier_key:multilinear.kzg.bls12-381/1",
                zkc_test_support::hex(&key)
            ],
            envelope(
                "commitment:multilinear.kzg.bls12-381/1",
                6,
                &committed.commitment().to_bytes(&bounds).unwrap()
            ),
            envelope("point:bls12-381.fr", 3, &point_bytes),
            envelope("field:bls12-381.fr", 1, &encode_scalar(&value).unwrap()),
            envelope(
                "proof:multilinear.kzg.bls12-381/1",
                7,
                &proof.to_bytes(&bounds).unwrap()
            )
        ]
    ]);
    assert_eq!(
        respond(&request).unwrap(),
        json!(["ok", ["bool", "5a4b4356010501"]])
    );
    let mut false_value = request.clone();
    false_value[5][3] = envelope(
        "field:bls12-381.fr",
        1,
        &encode_scalar(&(value + Scalar::from(1))).unwrap(),
    );
    assert_eq!(
        respond(&false_value).unwrap(),
        json!(["ok", ["bool", "5a4b4356010500"]])
    );
    let foreign = Keys::setup_for_development(2, &bounds).unwrap();
    // /2 preserves nominal identities and allows multiple authorized keys,
    // while the actual operand and each receive still select exactly one.
    let nominal = |kind: &str| match kind {
        "field" | "point" => format!("{kind}:bls12-381.fr"),
        _ => format!("{kind}:multilinear.kzg.bls12-381/1"),
    };
    let foreign_key = zkc_test_support::hex(&foreign.verifier_key().to_bytes(&bounds).unwrap());
    let explicit = json!([
        "zkc.public-primitive/1",
        [
            ["a", nominal("verifier_key"), zkc_test_support::hex(&key)],
            ["b", nominal("verifier_key"), foreign_key]
        ],
        "pcs.check",
        ["multilinear.kzg.bls12-381/1"],
        [],
        request[5]
    ]);
    assert_eq!(
        respond(&explicit).unwrap(),
        json!(["ok", ["bool", "5a4b4356010501"]])
    );
    let mut mismatched_operand = explicit.clone();
    mismatched_operand[5][0][1] = json!(foreign_key);
    assert_eq!(
        respond(&mismatched_operand).unwrap(),
        json!(["error", "primitive-pcs-check"])
    );
    let selected_validation = json!([
        "zkc.public-primitive/1",
        [explicit[1][1]],
        "validate",
        [],
        [],
        [explicit[5][1]]
    ]);
    assert_eq!(
        respond(&selected_validation).unwrap(),
        json!(["error", "primitive-key-identity"])
    );
    let mut bare_key = explicit;
    bare_key[1][0][1] = json!("verifier_key");
    assert_eq!(
        respond(&bare_key).unwrap(),
        json!(["error", "primitive-key-type"])
    );
    let mut foreign_config = request.clone();
    foreign_config[1][0][2] = json!(zkc_test_support::hex(
        &foreign.verifier_key().to_bytes(&bounds).unwrap()
    ));
    assert_eq!(respond(&foreign_config).unwrap()[0], "error");
    let mut trailing = request;
    let bytes = trailing[5][4][1].as_str().unwrap().to_owned();
    trailing[5][4][1] = json!(format!("{bytes}00"));
    assert_eq!(respond(&trailing).unwrap()[0], "error");
}

#[test]
fn profile_tagged_primitive_requests_have_no_compatibility_route() {
    // A profile-shaped request has the explicit form's arity, so under the
    // current tag it is an explicit request whose operation is not a string:
    // answered with that error, never evaluated through a profile.
    assert_eq!(
        respond(&json!([
            "zkc.public-primitive/1",
            "arkworks.bls12-381/1",
            ["zkc.public-configuration/1", []],
            "curve.generator",
            [],
            []
        ])),
        Ok(json!(["error", "primitive-string"]))
    );
    for request in [
        json!([
            "zkc.public-primitive/2",
            "arkworks.bls12-381/1",
            ["zkc.public-configuration/2", []],
            "curve.generator",
            [],
            []
        ]),
        json!([
            "zkc.transcript-request/1",
            "arkworks.multilinear.bls12-381/1",
            "",
            []
        ]),
    ] {
        assert_eq!(respond(&request), Err("primitive-request"));
    }
}
