//! Source-authored local host configuration, actual native compiler output, and
//! real Lean checking. Setup policy is independent of names generated by MLIR.

use serde_json::{Value as Json, json};
use std::{path::PathBuf, process::Command};

struct Host {
    directory: zkc_test_support::Evidence,
    checker: PathBuf,
}
impl Host {
    /// A source from the corpus by name, or any other by its path from the
    /// repository root: one case here compiles a maintained example instead.
    fn compile(source: &str) -> Self {
        let directory = zkc_test_support::evidence(module_path!());
        let compiler = zkc_test_support::compiler();
        let input = match source.contains('/') {
            true => zkc_test_support::root().join(source),
            false => zkc_test_support::source(source),
        };
        for (command, file) in [
            ("protocol-source", "source.json"),
            ("protocol-compile", "candidate.json"),
        ] {
            let result = Command::new(&compiler)
                .arg(command)
                .arg(&input)
                .output()
                .unwrap();
            assert!(
                result.status.success(),
                "{}",
                String::from_utf8_lossy(&result.stderr)
            );
            std::fs::write(directory.path().join(file), result.stdout).unwrap();
        }
        Self {
            directory,
            checker: zkc_test_support::checker("interactive-protocol"),
        }
    }
    fn replace_source(&self, source: &Json) {
        let path = self.directory.path();
        std::fs::write(
            path.join("source.json"),
            serde_json::to_vec(source).unwrap(),
        )
        .unwrap();
        let result = Command::new(zkc_test_support::compiler())
            .arg("protocol-compile")
            .arg(path.join("source.json"))
            .output()
            .unwrap();
        assert!(
            result.status.success(),
            "{}",
            String::from_utf8_lossy(&result.stderr)
        );
        std::fs::write(path.join("candidate.json"), result.stdout).unwrap();
    }
    fn run(&self, input: &Json) -> Result<Json, String> {
        let path = self.directory.path();
        std::fs::write(path.join("inputs.json"), serde_json::to_vec(input).unwrap()).unwrap();
        let result = Command::new(env!("CARGO_BIN_EXE_zkc"))
            .arg("run-protocol")
            .arg(path.join("source.json"))
            .arg(path.join("candidate.json"))
            .arg(path.join("inputs.json"))
            .arg(&self.checker)
            .output()
            .unwrap();
        if result.status.success() {
            Ok(serde_json::from_slice(&result.stdout).unwrap())
        } else {
            Err(format!(
                "{}{}",
                String::from_utf8_lossy(&result.stdout),
                String::from_utf8_lossy(&result.stderr)
            ))
        }
    }
}

#[test]
fn openings_borrow_the_original_across_scratch_calculation() {
    let host = Host::compile("generic-opening-reuse.pir");
    let input: Json = serde_json::from_str(include_str!(
        "../../../tests/fixtures/generic-opening-reuse.inputs.json"
    ))
    .unwrap();
    let report = host.run(&input).unwrap();
    let values = &report["outcome"][1]["P"];
    assert_eq!(report["outcome"][0], "returned");
    // Logical table order fixes the high half first: f(x,y)=4x+y+4xy.
    assert_eq!(values[0], json!(["field", "35"]));
    assert_eq!(values[1], json!(["field", "167"]));
    assert_eq!(values[2], json!(["bool", true]));
    assert_eq!(values[3], json!(["bool", true]));
    assert_eq!(
        values[4],
        json!([
            "wire",
            "table",
            format!(
                "5a4b43560102010000002c{}59{}",
                "00".repeat(31),
                "00".repeat(31)
            )
        ])
    );
    assert_eq!(report["wire"]["messages"], 0);
}

#[test]
fn two_setups_are_selected_by_original_ports_and_receiving_sites() {
    let host = Host::compile("generic-openings.pir");
    let input: Json = serde_json::from_str(include_str!(
        "../../../tests/fixtures/generic-openings.inputs.json"
    ))
    .unwrap();
    let report = host.run(&input).unwrap();
    assert_eq!(
        report["outcome"],
        json!(["returned", {"P": [], "V": [["bool", true], ["bool", true]]}])
    );
    assert_eq!(report["wire"]["messages"], 8);
    assert_eq!(report["assurance"][0], "generic-structural-correspondence");
    assert!(report["profile"].is_null());

    let mut missing = input.clone();
    missing[5].as_array_mut().unwrap().pop();
    assert!(
        host.run(&missing)
            .unwrap_err()
            .contains("host-receive-coverage")
    );
    let mut unknown = input.clone();
    unknown[5][0][2] = json!("unknown");
    assert!(
        host.run(&unknown)
            .unwrap_err()
            .contains("host-receive-site-or-duplicate")
    );
    let mut unknown_setup = input.clone();
    unknown_setup[5][0][3] = json!("peer-supplied");
    assert!(
        host.run(&unknown_setup)
            .unwrap_err()
            .contains("host-receive-setup")
    );
    let mut generated_name = input.clone();
    generated_name[4][0][3][0][0] = json!("v0");
    assert!(
        host.run(&generated_name)
            .unwrap_err()
            .contains("host-constraint-port")
    );

    // A registered key of the wrong setup is still unacceptable at this receive.
    // The decoder must not fall back to another key whose header matches bytes.
    let mut wrong_setup = input.clone();
    wrong_setup[5][0][3] = json!("large");
    let wrong = host.run(&wrong_setup).unwrap();
    assert_eq!(wrong["outcome"][0], "failed");
    assert!(
        wrong["outcome"][1]
            .as_str()
            .unwrap()
            .starts_with("refused:")
    );
    assert_eq!(wrong["wire"]["messages"], 3);
    assert_eq!(wrong["cancelled_roles"], json!(["P", "V"]));
    for role in ["P", "V"] {
        assert_eq!(wrong["usage"][role]["live_value_bytes"], 0);
    }

    // Equal ranks must still retain distinct setup identities.
    let mut equal_rank = input.clone();
    equal_rank[3][1][2] = json!("2");
    for role in equal_rank[4].as_array_mut().unwrap() {
        for constraint in role[3].as_array_mut().unwrap() {
            if constraint[1] == "3" {
                constraint[1] = json!("2");
            }
        }
        for port in role[2].as_array_mut().unwrap() {
            if port[0] == "b" {
                port[1][1].as_array_mut().unwrap().truncate(4);
            }
            if port[0] == "rb" {
                port[1][1].as_array_mut().unwrap().truncate(2);
            }
        }
    }
    assert_eq!(host.run(&equal_rank).unwrap()["outcome"][0], "returned");
    equal_rank[5][0][3] = json!("large");
    let mismatched = host.run(&equal_rank).unwrap();
    assert_eq!(mismatched["outcome"][0], "failed");
    assert!(
        mismatched["outcome"][1]
            .as_str()
            .unwrap()
            .starts_with("refused:")
    );
    assert_eq!(mismatched["wire"]["messages"], 3);
}

#[test]
fn setup_policy_follows_the_child_instance_through_repeated_calls() {
    let host = Host::compile("generic-openings.pir");
    let mut source: Json =
        serde_json::from_slice(&std::fs::read(host.directory.path().join("source.json")).unwrap())
            .unwrap();
    source[1].as_array_mut().unwrap().push(json!([
        "generic_function",
        "Assert",
        [],
        [],
        [["a", "bool"], ["b", "bool"]],
        [],
        [
            ["op", "both", "bool.and", [], [], ["a", "b"], ["ok"]],
            ["op", "require", "control.require", [], [], ["ok"], []],
            ["return", []]
        ]
    ]));
    source[2]
        .as_array_mut()
        .unwrap()
        .push(json!(["configure", "BothAccepted", "Assert", [], []]));
    let ports = source[3][3][0][4].clone();
    let names = ports
        .as_array()
        .unwrap()
        .iter()
        .map(|p| p[0].clone())
        .collect::<Vec<_>>();
    source[3][3].as_array_mut().unwrap().push(json!([
        "protocol",
        "RepeatOpenings",
        ["P", "V"],
        [],
        ports,
        [],
        [["child", "TwoOpenings", []]],
        [
            [
                "loop",
                "repeat",
                ["constant", "2"],
                [],
                names,
                [
                    ["call", "prove", "child", names, ["a_ok", "b_ok"]],
                    ["local", "accept", "V", "BothAccepted", ["a_ok", "b_ok"], []],
                    ["yield", []]
                ],
                []
            ],
            ["return", []]
        ]
    ]));
    source[3][4].as_array_mut().unwrap().push(json!([
        "instance",
        "outer",
        "RepeatOpenings",
        [],
        [["child", "concrete"]],
        [["P", "P"], ["V", "V"]]
    ]));
    source[3][5] = json!([["entry", "main", "outer"]]);
    host.replace_source(&source);
    let input: Json = serde_json::from_str(include_str!(
        "../../../tests/fixtures/generic-openings.inputs.json"
    ))
    .unwrap();
    let report = host.run(&input).unwrap();
    assert_eq!(report["outcome"], json!(["returned", {"P": [], "V": []}]));
    assert_eq!(report["wire"]["messages"], 16);
    for role in ["P", "V"] {
        assert_eq!(report["usage"][role]["iterations"], 2);
    }
    let mut wrong_instance = input.clone();
    wrong_instance[5][0][0] = json!("outer");
    assert!(
        host.run(&wrong_instance)
            .unwrap_err()
            .contains("host-receive-site-or-duplicate")
    );

    let mut wrong_setup = input.clone();
    wrong_setup[5][0][3] = json!("large");
    let failed = host.run(&wrong_setup).unwrap();
    assert_eq!(failed["outcome"][0], "failed");
    for cancellation in failed["cancellations"].as_array().unwrap() {
        assert_eq!(
            cancellation["origin"],
            json!([
                "zkc.origin/2",
                "two-independent-openings",
                "main",
                "concrete",
                [["loop", "repeat", "0"], ["call", "prove", "concrete"]]
            ])
        );
        assert_eq!(cancellation["kind"], "cancelled");
        assert_eq!(cancellation["cleanup_errors"], json!([]));
    }

    // Receive-policy coverage is structural, even when the public loop is empty.
    source[3][3][1][7][0][2][1] = json!("0");
    host.replace_source(&source);
    assert_eq!(host.run(&input).unwrap()["wire"]["messages"], 0);
    let mut missing = input.clone();
    missing[5] = json!([]);
    assert!(
        host.run(&missing)
            .unwrap_err()
            .contains("host-receive-coverage")
    );
}

#[test]
fn stopped_generic_host_preserves_consumed_service_state() {
    let host = Host::compile("generic-stops.pir");
    let mut input = json!([
        "zkc.run/2",
        "main",
        "stop-test",
        [],
        [[
            "P",
            [["rng", "coins", "1", "entry"]],
            [
                ["rng", ["host", "coins"]],
                ["table", ["table", ["0", "1", "4", "9"]]],
                ["allowed", ["bool", false]]
            ],
            [["table", "2", null]]
        ]],
        []
    ]);
    let stopped = host.run(&input).unwrap();
    assert_eq!(stopped["outcome"][0], "stopped");
    assert!(stopped["outcome"].to_string().contains("rejected:require"));
    assert_eq!(stopped["stop"]["detail"], "rejected:require");
    assert_eq!(
        stopped["stop"]["origin"],
        json!(["zkc.origin/2", "stop-test", "main", "concrete", []])
    );
    assert_eq!(stopped["stop"]["cleanup_errors"], json!([]));
    assert_eq!(
        &stopped["resources"][0].as_array().unwrap()[..5],
        &[json!("P"), json!("coins"), json!(1), json!(1), json!(0)]
    );
    assert_eq!(stopped["usage"]["P"]["live_value_bytes"], 0);
    input[4][0][2][2][1][1] = json!(true);
    let success = host.run(&input).unwrap();
    assert_eq!(success["outcome"][0], "returned");
    assert_eq!(success["resources"], stopped["resources"]);
}

#[test]
fn bls_shorthand_uses_explicit_host_contract() {
    let host = Host::compile("examples/protocols/two-factor.pir");
    let input = serde_json::from_str(include_str!(
        "../../../examples/protocols/two-factor.inputs.json"
    ))
    .unwrap();
    let report = host.run(&input).unwrap();
    assert_eq!(report["outcome"][0], "returned");
    assert_eq!(report["assurance"][0], "generic-structural-correspondence");
}
