import Zkc.Protocols.BackendProfiles.Admission

set_option autoImplicit false

namespace Zkc.Protocols.BackendProfiles.Certificates
open Lean Zkc.Protocols.BackendProfiles

def scalarAnchor : Anchor := ⟨"n1.quadratic.0.horner", .scalar, 4, [(4,(.apply "field.mul" (.input 2) (.input 3))),(5,(.apply "field.add" (.input 1) (.input 4))),(6,(.apply "field.mul" (.input 5) (.input 3))),(7,(.apply "field.add" (.input 0) (.input 6)))], [7]⟩
def scalarJson : Json := (.arr #[(.str "n1.quadratic.0.horner"),(.str "scalar"),(.num ⟨4,0⟩),(.arr #[(.arr #[(.num ⟨4,0⟩),(.arr #[(.str "apply"),(.str "field.mul"),(.arr #[(.str "input"),(.num ⟨2,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨5,0⟩),(.arr #[(.str "apply"),(.str "field.add"),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "input"),(.num ⟨4,0⟩)])])]),(.arr #[(.num ⟨6,0⟩),(.arr #[(.str "apply"),(.str "field.mul"),(.arr #[(.str "input"),(.num ⟨5,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨7,0⟩),(.arr #[(.str "apply"),(.str "field.add"),(.arr #[(.str "input"),(.num ⟨0,0⟩)]),(.arr #[(.str "input"),(.num ⟨6,0⟩)])])])]),(.arr #[(.num ⟨7,0⟩)]),(.arr #[(.arr #[(.num ⟨4,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "mulmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨2,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨5,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "addmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "input"),(.num ⟨4,0⟩)])])]),(.arr #[(.num ⟨6,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "mulmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨5,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨7,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "addmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨0,0⟩)]),(.arr #[(.str "input"),(.num ⟨6,0⟩)])])])]),(.arr #[(.num ⟨7,0⟩)])])
def scalarRequest : Request := ⟨.scalar, 4, [(4,(.apply "field.mul" (.input 2) (.input 3))),(5,(.apply "field.add" (.input 1) (.input 4))),(6,(.apply "field.mul" (.input 5) (.input 3))),(7,(.apply "field.add" (.input 0) (.input 6)))], [7], [(4,(.apply (.mulmod 2305843009213697249) (.input 2) (.input 3))),(5,(.apply (.addmod 2305843009213697249) (.input 1) (.input 4))),(6,(.apply (.mulmod 2305843009213697249) (.input 5) (.input 3))),(7,(.apply (.addmod 2305843009213697249) (.input 0) (.input 6)))], [7]⟩
theorem scalar_admitted : validate scalarAnchor scalarJson "n1.quadratic.0.horner" scalarRequest = .accepted := by decide
def scalarAdmitted : Admitted scalarAnchor scalarJson := ⟨"n1.quadratic.0.horner", scalarRequest, scalar_admitted⟩
def friAnchor : Anchor := ⟨"fri/walk/1", .fri, 3, [(3,(.apply "digest.of_words" (.input 2) (.literal (.unit)))),(4,(.choose (.apply "word.odd" (.input 1) (.literal (.unit))) (.apply "p3.node" (.input 3) (.input 0)) (.apply "p3.node" (.input 0) (.input 3)))),(5,(.apply "word.shr" (.input 1) (.literal (.shift 1))))], [4]⟩
def friJson : Json := (.arr #[(.str "fri/walk/1"),(.str "fri"),(.num ⟨3,0⟩),(.arr #[(.arr #[(.num ⟨3,0⟩),(.arr #[(.str "apply"),(.str "digest.of_words"),(.arr #[(.str "input"),(.num ⟨2,0⟩)]),(.arr #[(.str "literal"),(.str "unit"),(.arr #[])])])]),(.arr #[(.num ⟨4,0⟩),(.arr #[(.str "choose"),(.arr #[(.str "apply"),(.str "word.odd"),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "literal"),(.str "unit"),(.arr #[])])]),(.arr #[(.str "apply"),(.str "p3.node"),(.arr #[(.str "input"),(.num ⟨3,0⟩)]),(.arr #[(.str "input"),(.num ⟨0,0⟩)])]),(.arr #[(.str "apply"),(.str "p3.node"),(.arr #[(.str "input"),(.num ⟨0,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])])]),(.arr #[(.num ⟨5,0⟩),(.arr #[(.str "apply"),(.str "word.shr"),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "literal"),(.str "shift:u6"),(.arr #[(.num ⟨1,0⟩)])])])])]),(.arr #[(.num ⟨4,0⟩)]),(.arr #[(.arr #[(.num ⟨3,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "ofWords"),(.str "p3:3da346791c813433b201299afc3d10bf42f8a078:r26")]),(.arr #[(.str "input"),(.num ⟨2,0⟩)]),(.arr #[(.str "literal"),(.str "unit"),(.arr #[])])])]),(.arr #[(.num ⟨4,0⟩),(.arr #[(.str "choose"),(.arr #[(.str "apply"),(.arr #[(.str "odd"),(.num ⟨64,0⟩)]),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "literal"),(.str "unit"),(.arr #[])])]),(.arr #[(.str "apply"),(.arr #[(.str "node"),(.str "p3:3da346791c813433b201299afc3d10bf42f8a078:r26")]),(.arr #[(.str "input"),(.num ⟨3,0⟩)]),(.arr #[(.str "input"),(.num ⟨0,0⟩)])]),(.arr #[(.str "apply"),(.arr #[(.str "node"),(.str "p3:3da346791c813433b201299afc3d10bf42f8a078:r26")]),(.arr #[(.str "input"),(.num ⟨0,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])])]),(.arr #[(.num ⟨5,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "shift"),(.num ⟨64,0⟩)]),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "literal"),(.str "shift:u6"),(.arr #[(.num ⟨1,0⟩)])])])])]),(.arr #[(.num ⟨4,0⟩)])])
def friRequest : Request := ⟨.fri, 3, [(3,(.apply "digest.of_words" (.input 2) (.literal (.unit)))),(4,(.choose (.apply "word.odd" (.input 1) (.literal (.unit))) (.apply "p3.node" (.input 3) (.input 0)) (.apply "p3.node" (.input 0) (.input 3)))),(5,(.apply "word.shr" (.input 1) (.literal (.shift 1))))], [4], [(3,(.apply (.ofWords "p3:3da346791c813433b201299afc3d10bf42f8a078:r26") (.input 2) (.literal (.unit)))),(4,(.choose (.apply (.odd 64) (.input 1) (.literal (.unit))) (.apply (.node "p3:3da346791c813433b201299afc3d10bf42f8a078:r26") (.input 3) (.input 0)) (.apply (.node "p3:3da346791c813433b201299afc3d10bf42f8a078:r26") (.input 0) (.input 3)))),(5,(.apply (.shift 64) (.input 1) (.literal (.shift 1))))], [4]⟩
theorem fri_admitted : validate friAnchor friJson "fri/walk/1" friRequest = .accepted := by decide
def friAdmitted : Admitted friAnchor friJson := ⟨"fri/walk/1", friRequest, fri_admitted⟩
def aliasAnchor : Anchor := ⟨"sc-admitted-alias", .scalar, 4, [(4,(.input 0)),(5,(.apply "field.mul" (.input 2) (.input 3))),(6,(.apply "field.add" (.input 1) (.input 5))),(7,(.apply "field.mul" (.input 6) (.input 3))),(8,(.apply "field.add" (.input 4) (.input 7)))], [8]⟩
def aliasJson : Json := (.arr #[(.str "sc-admitted-alias"),(.str "scalar"),(.num ⟨4,0⟩),(.arr #[(.arr #[(.num ⟨4,0⟩),(.arr #[(.str "input"),(.num ⟨0,0⟩)])]),(.arr #[(.num ⟨5,0⟩),(.arr #[(.str "apply"),(.str "field.mul"),(.arr #[(.str "input"),(.num ⟨2,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨6,0⟩),(.arr #[(.str "apply"),(.str "field.add"),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "input"),(.num ⟨5,0⟩)])])]),(.arr #[(.num ⟨7,0⟩),(.arr #[(.str "apply"),(.str "field.mul"),(.arr #[(.str "input"),(.num ⟨6,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨8,0⟩),(.arr #[(.str "apply"),(.str "field.add"),(.arr #[(.str "input"),(.num ⟨4,0⟩)]),(.arr #[(.str "input"),(.num ⟨7,0⟩)])])])]),(.arr #[(.num ⟨8,0⟩)]),(.arr #[(.arr #[(.num ⟨4,0⟩),(.arr #[(.str "input"),(.num ⟨0,0⟩)])]),(.arr #[(.num ⟨5,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "mulmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨2,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨6,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "addmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨1,0⟩)]),(.arr #[(.str "input"),(.num ⟨5,0⟩)])])]),(.arr #[(.num ⟨7,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "mulmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨6,0⟩)]),(.arr #[(.str "input"),(.num ⟨3,0⟩)])])]),(.arr #[(.num ⟨8,0⟩),(.arr #[(.str "apply"),(.arr #[(.str "addmod"),(.num ⟨2305843009213697249,0⟩)]),(.arr #[(.str "input"),(.num ⟨4,0⟩)]),(.arr #[(.str "input"),(.num ⟨7,0⟩)])])])]),(.arr #[(.num ⟨8,0⟩)])])
def aliasRequest : Request := ⟨.scalar, 4, [(4,(.input 0)),(5,(.apply "field.mul" (.input 2) (.input 3))),(6,(.apply "field.add" (.input 1) (.input 5))),(7,(.apply "field.mul" (.input 6) (.input 3))),(8,(.apply "field.add" (.input 4) (.input 7)))], [8], [(4,(.input 0)),(5,(.apply (.mulmod 2305843009213697249) (.input 2) (.input 3))),(6,(.apply (.addmod 2305843009213697249) (.input 1) (.input 5))),(7,(.apply (.mulmod 2305843009213697249) (.input 6) (.input 3))),(8,(.apply (.addmod 2305843009213697249) (.input 4) (.input 7)))], [8]⟩
theorem alias_admitted : validate aliasAnchor aliasJson "sc-admitted-alias" aliasRequest = .accepted := by decide
def aliasAdmitted : Admitted aliasAnchor aliasJson := ⟨"sc-admitted-alias", aliasRequest, alias_admitted⟩

theorem alias_readback_checked : check aliasRequest = .accepted := by decide

end Zkc.Protocols.BackendProfiles.Certificates
