cmake_minimum_required(VERSION 3.20)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(ZkcVectorService LANGUAGES C CXX)
  find_package(ZkcCompiler REQUIRED CONFIG)
  list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}" "${LLVM_CMAKE_DIR}")
  include(TableGen)
  include(AddLLVM)
  include(AddMLIR)
  get_target_property(zkc_includes Zkc::Compiler INTERFACE_INCLUDE_DIRECTORIES)
  add_library(ZkcCompiler ALIAS Zkc::Compiler)
else()
  set(zkc_includes ${PROJECT_SOURCE_DIR}/include)
endif()

set(service_tablegen_includes ${zkc_includes} ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
set(LLVM_TARGET_DEFINITIONS Service.td)
mlir_tablegen(ServiceDialect.h.inc -gen-dialect-decls -dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceDialect.cpp.inc -gen-dialect-defs -dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceTypes.h.inc -gen-typedef-decls -typedefs-dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceTypes.cpp.inc -gen-typedef-defs -typedefs-dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceOps.h.inc -gen-op-decls EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceOps.cpp.inc -gen-op-defs EXTRA_INCLUDES ${service_tablegen_includes})
add_public_tablegen_target(ZkcServiceGen)
add_library(ZkcServiceExample Service.cpp)
add_dependencies(ZkcServiceExample ZkcServiceGen)
target_include_directories(ZkcServiceExample PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(ZkcServiceExample SYSTEM PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
target_compile_options(ZkcServiceExample PRIVATE -Wall -Wextra -Werror)
target_link_libraries(ZkcServiceExample PUBLIC ZkcCompiler)
add_executable(zkc-service-compile compile.cpp)
target_link_libraries(zkc-service-compile PRIVATE ZkcServiceExample)
add_executable(zkc-service-opt opt.cpp)
target_link_libraries(zkc-service-opt PRIVATE ZkcServiceExample MLIRMlirOptMain)
