cmake_minimum_required(VERSION 3.20)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(ZkcVectorService LANGUAGES C CXX)
endif()
if(NOT TARGET ZkcCompiler)
  if(NOT TARGET Zkc::Compiler)
    find_package(ZkcCompiler REQUIRED CONFIG)
  endif()
  list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}" "${LLVM_CMAKE_DIR}")
  if(NOT IS_ABSOLUTE "${MLIR_TABLEGEN_EXE}")
    find_program(ZKC_MLIR_TABLEGEN_EXE NAMES mlir-tblgen
      HINTS "${MLIR_TOOLS_DIR}" "${LLVM_TOOLS_BINARY_DIR}" REQUIRED)
    set(MLIR_TABLEGEN_EXE "${ZKC_MLIR_TABLEGEN_EXE}")
  endif()
  include(TableGen)
  include(AddLLVM)
  include(AddMLIR)
  get_target_property(zkc_includes Zkc::IR INTERFACE_INCLUDE_DIRECTORIES)
else()
  set(zkc_includes ${PROJECT_SOURCE_DIR}/include)
endif()

set(service_tablegen_includes ${zkc_includes} ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
set(LLVM_TARGET_DEFINITIONS Service.td)
mlir_tablegen(ServiceDialect.h.inc -gen-dialect-decls -dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceDialect.cpp.inc -gen-dialect-defs -dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceTypes.h.inc -gen-typedef-decls -typedefs-dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceTypes.cpp.inc -gen-typedef-defs -typedefs-dialect=service EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceOps.h.inc -gen-op-decls EXTRA_INCLUDES ${service_tablegen_includes})
mlir_tablegen(ServiceOps.cpp.inc -gen-op-defs EXTRA_INCLUDES ${service_tablegen_includes})
add_public_tablegen_target(ZkcServiceGen)
add_library(ZkcServiceExample Service.cpp)
add_dependencies(ZkcServiceExample ZkcServiceGen)
target_include_directories(ZkcServiceExample PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(ZkcServiceExample SYSTEM PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
target_compile_options(ZkcServiceExample PRIVATE -Wall -Wextra -Werror)
target_link_libraries(ZkcServiceExample PUBLIC Zkc::IR)
add_executable(zkc-service-compile compile.cpp)
target_link_libraries(zkc-service-compile PRIVATE ZkcServiceExample Zkc::Driver)
add_executable(zkc-service-opt opt.cpp)
target_link_libraries(zkc-service-opt PRIVATE ZkcServiceExample Zkc::CompilerCore MLIRMlirOptMain)
