add_subdirectory(Artifact)
add_subdirectory(Compiler)
add_subdirectory(Dialect/Oir)
add_subdirectory(Dialect/Pir)
add_subdirectory(Encoding)
add_subdirectory(Dialect/Oir/Views)
add_subdirectory(Family)
add_subdirectory(Interpreter)
add_subdirectory(Registry)
add_subdirectory(Relation)
add_subdirectory(Semantics)
add_subdirectory(Soundness)
add_subdirectory(Tools)
