#!/usr/bin/env python3
"""Cross direct-library proofs with injected native artifacts and original-source Lean.

All output is public development evidence. No setup is regenerated by this test.
Compiler/host are subprocess comparators, never dependencies of the Rust baseline.
"""
import argparse
import copy
import hashlib
import json
from pathlib import Path
import platform
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "support"))

from run_reference import run_reference  # noqa: E402
from journal import Journal, TIMEOUT, positive_timeout  # noqa: E402


def write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + '\n')


def logical(v):
    if isinstance(v, str):
        b = v.encode()
        return b'\0' + struct.pack('<Q', len(b)) + b
    assert isinstance(v, list)
    return b'\1' + struct.pack('<Q', len(v)) + b''.join(map(logical, v))


def root_digest(source, descriptor, inputs):
    """The binding root, encoded here rather than taken from what produced it.

    Both identity policies share this tag and the descriptor inside names the
    policy; this is the whole-source shape an exact descriptor produces. The public records go in as the
    inputs carry them, three fields each.
    """
    public = [[r[0], r[1], r[2]] for r in inputs[2]]
    return hashlib.sha256(logical(['zkc.artifact-binding/1', source, descriptor,
                                  inputs[1], public, inputs[4]])).digest()


def frames(b):
    result = []
    cursor = 40
    while cursor < len(b):
        n, = struct.unpack_from('<Q', b, cursor)
        result.append(b[cursor + 8:cursor + 8 + n])
        cursor += 8 + n
    assert cursor == len(b)
    return result


def framed(header, values):
    return header + b''.join(struct.pack('<Q', len(v)) + v for v in values)


def change_scalar(b):
    assert b[:6] == b'ZKCV\1\1'
    p = 52435875175126190479447740508185965837690552500527637822603658699938581184513
    return b[:6] + ((int.from_bytes(b[6:], 'little') + 1) % p).to_bytes(32, 'little')


def direct_frames(report):
    events = report.get('trace', report).get('events', [])
    return [(e[0], logical(e[1]).hex(), e[2]) for e in events if e[0] in ('observe', 'challenge')]


def reference_frames(observation):
    result = []
    for e in observation[2]:
        if e[0] == 'message':
            result.append(('observe', e[1], e[3]))
        elif e[0] == 'challenge':
            result.append(('challenge', e[1], e[2][1]))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ['baseline', 'fixtures', 'output', 'host', 'compiler',
                 'participant-checker', 'lean', 'primitive']:
        parser.add_argument('--' + name, type=Path, required=True)
    parser.add_argument('--timeout', type=positive_timeout, default=TIMEOUT)
    a = parser.parse_args()
    for name, value in vars(a).items():
        if isinstance(value, Path):
            setattr(a, name, value.resolve())
    a.output.mkdir(parents=True, exist_ok=False)
    receipts, checks = [], []
    journal = Journal(a.output / 'commands', timeout=a.timeout)
    binaries = {name: hashlib.sha256(getattr(a, name).read_bytes()).hexdigest()
                for name in ['baseline', 'host', 'compiler', 'participant_checker', 'lean', 'primitive']}

    def call(argv, output, success=True, cwd=None):
        run = journal.attempt(argv, cwd=cwd, keep=output.resolve())
        receipts.append({'argv': list(map(str, argv)), 'cwd': str(cwd) if cwd else None,
                         'returncode': run.returncode, 'stdout': str(output), 'stderr': run.stderr})
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(run.stdout)
        assert run.returncode >= 0 and (run.returncode == 0) == success, (argv, run.returncode, run.stdout, run.stderr)
        return json.loads(run.stdout)

    def checked(name, condition):
        assert condition, name
        checks.append(name)

    memo = {}
    for name in ['committed-two-factor', 'dleq']:
        fixture = a.fixtures / name
        output = a.output / name
        output.mkdir(parents=True, exist_ok=True)
        source, descriptor = fixture/'source.json', fixture/'descriptor.json'
        producer, validator = fixture/'producer/inputs.json', fixture/'validator/inputs.json'
        src, desc, vi = [json.loads(p.read_text()) for p in [source, descriptor, validator]]
        budget = str(3 * int(src[4][0][3][0][1]) + 6) if name != 'dleq' else '10'
        proof = output/'direct.proof'
        call([a.baseline, 'prove-development', source, descriptor, producer, proof, '1'], output/'direct-prove.json')
        direct = call([a.baseline, 'validate', source, descriptor, validator, proof, '1'], output/'direct-validate.json', cwd=fixture/'validator')
        checked(name + ': direct honest', direct['status'] == 'accepted')
        construction = output/'construction.json'
        common = output/'common.json'
        physical = output/'physical.json'
        built = call([a.compiler, 'protocol-construct', source, descriptor], construction)
        write(common, built[2])
        call([a.compiler, 'protocol-compile', common], physical)

        def host(command, inputs, candidate, out, ok=True):
            return call([a.host, command, source, descriptor, construction, physical,
                         inputs, a.compiler, a.participant_checker, candidate, budget], out, ok,
                        cwd=fixture/('producer' if command == 'produce-artifact' else 'validator'))

        native = output/'native.proof'
        host('produce-artifact', producer, native, output/'native-prove.json')
        host('validate-artifact', validator, proof, output/'native-validate-direct.json')
        host('validate-artifact', validator, native, output/'native-validate-native.json')
        native_direct = call([a.baseline, 'validate', source, descriptor, validator, native, '1'], output/'direct-validate-native.json', cwd=fixture/'validator')
        checked(name + ': native accepts direct; direct accepts native', native_direct['status'] == 'accepted')
        if name != 'dleq':
            checked(name + ': deterministic full proof byte equality', native.read_bytes() == proof.read_bytes())
        else:
            checked(name + ': OS native proof differs from public deterministic proof', native.read_bytes() != proof.read_bytes())
        for label, candidate, report in [('direct', proof, direct), ('native', native, native_direct)]:
            lean = run_reference(a.lean, a.primitive, source, descriptor, validator, candidate,
                                 output/('lean-' + label), memo=memo)
            checked(name + ': Lean accepts ' + label, lean[1][0] == 'accepted')
            checked(name + ': exact source frames and draws ' + label,
                    direct_frames(report) == reference_frames(lean))

        raw = proof.read_bytes()
        checked(name + ': independently encoded root agrees', raw[8:40] == root_digest(src, desc, vi))
        msgs = frames(raw)
        malformed = [
            ('trailing', raw + b'\0', vi),
            ('truncated', raw[:-1], vi),
            ('wrong-binding', raw[:8] + bytes([raw[8] ^ 1]) + raw[9:], vi),
            ('huge-length', raw[:40] + b'\xff'*8 + raw[48:], vi),
        ]
        m = msgs.copy()
        m[0] = b'ZKCV\1\1' + m[0][6:]
        malformed.append(('wrong-type', framed(raw[:40], m), vi))
        if name == 'dleq':
            for index, label in [(2, 'first-response'), (5, 'second-response')]:
                m = msgs.copy(); m[index] = change_scalar(m[index])
                malformed.append((label, framed(raw[:40], m), vi))
            m = msgs.copy(); m[2] = m[2][:6] + b'\xff'*32
            malformed.append(('noncanonical-scalar', framed(raw[:40], m), vi))
        else:
            m = msgs.copy(); m[0] = msgs[1]
            malformed.append(('received-root', framed(raw[:40], m), vi))
            m = msgs.copy(); m[2] = m[2][:6] + b'\xff'*32 + m[2][38:]
            malformed.append(('noncanonical-scalar', framed(raw[:40], m), vi))
            # Correct scalar ingress, but false claimed PCS opening value.
            index = len(msgs)-4
            m = msgs.copy(); m[index] = change_scalar(m[index])
            malformed.append(('opening-value', framed(raw[:40], m), vi))
            m = msgs.copy(); m[-1] = msgs[-3]  # other factor's canonical proof
            malformed.append(('second-opening-proof', framed(raw[:40], m), vi))
        modified = copy.deepcopy(vi)
        modified[1] = (b'other application').hex()
        malformed.append(('context-binding', raw, modified))
        if name != 'dleq':
            modified = copy.deepcopy(vi)
            modified[2][0][2] = change_scalar(bytes.fromhex(modified[2][0][2])).hex()
            malformed.append(('claim-rebound', raw[:8]+root_digest(src,desc,modified)+raw[40:], modified))
            modified = copy.deepcopy(vi); modified[2][1][2] = modified[2][2][2]
            malformed.append(('expected-root-rebound', raw[:8]+root_digest(src,desc,modified)+raw[40:], modified))
        else:
            # Produce against a false second image. Equation 0 is honest, then
            # original require_1 fails; this does not stop at a stale header.
            modified = copy.deepcopy(vi); modified[2][3][2] = modified[2][2][2]
            pi = json.loads(producer.read_text()); pi[2] = modified[2]
            producer_bad = output/'false-image-producer.json'; write(producer_bad,pi)
            badproof = output/'false-image.proof'
            call([a.baseline,'prove-development',source,descriptor,producer_bad,badproof,'1'],output/'false-image-prove.json')
            malformed.append(('false-second-image',badproof.read_bytes(),modified))

        for label, candidate, inputs in malformed:
            case = output/'negative'/label
            case.mkdir(parents=True, exist_ok=True)
            ip, pp = case/'inputs.json', case/'candidate.proof'
            write(ip,inputs); pp.write_bytes(candidate)
            d = call([a.baseline,'validate',source,descriptor,ip,pp,'1'],case/'direct.json',False,cwd=case)
            host('validate-artifact',ip,pp,case/'native.json',False)
            lean = run_reference(a.lean,a.primitive,source,descriptor,ip,pp,case/'lean',memo=memo)
            checked(name+': three consumers refuse '+label,d['status']=='refused' and lean[1][0] != 'accepted')
            # Direct trace contains completed transitions on reached source guards.
            # Native and Lean additionally expose all individual local primitives.
            if label in ['first-response','second-response','false-second-image','received-root',
                         'claim-rebound','expected-root-rebound','opening-value','second-opening-proof']:
                checked(name+': reached frame prefix '+label,direct_frames(d)==reference_frames(lean))
                guards = [e for e in d['events'] if e[0]=='guard']
                checked(name+': semantic guard fails '+label, bool(guards) and guards[-1][-1] is False)
                if label == 'false-second-image':
                    checked(name+': first equation succeeds before second fails',guards[-1][-3]=='require_1' and guards[-2][-1] is True)

        # Standalone V refuses witness/PK/nonce records without trying to load PK.
        private = copy.deepcopy(vi)
        private[3] = [['pk','prover_key_file','/does/not/exist','00'*32,'vk']]
        bad_input=output/'validator-private.json';write(bad_input,private)
        d=call([a.baseline,'validate',source,descriptor,bad_input,proof,'1'],output/'validator-private-result.json',False)
        checked(name+': V refuses private input without file loading',d['code']=='validator-private-or-unknown-input')
        # Freeze source/descriptor rather than silently benchmarking a new algorithm.
        changed=copy.deepcopy(src);changed[2][0][4][0][1]='changed-operation-site'
        source_bad=output/'changed-source.json';write(source_bad,changed)
        call([a.baseline,'validate',source_bad,descriptor,validator,proof,'1'],output/'changed-source-result.json',False)
        checked(name+': unsupported source identity refused',True)
        if name != 'dleq':
            bad = json.loads(producer.read_text())
            bad[3][0][3] = '00' * 32
            badp = output/'wrong-material-producer.json'; write(badp,bad)
            old = output/'retained-candidate.proof'; old.write_bytes(b'previous completed file')
            call([a.baseline,'prove-development',source,descriptor,badp,old,'1'],output/'wrong-material-result.json',False)
            checked(name+': material mismatch refuses without replacing candidate',old.read_bytes()==b'previous completed file')
            key = fixture/'producer/prover-key.bin'; key_before=key.read_bytes()
            call([a.baseline,'fixture',source,descriptor,fixture],output/'repeat-setup-result.json',False)
            checked(name+': existing fixture refuses setup replacement',key.read_bytes()==key_before)

    # Exercise source parameter edits without changing any function/site/call.
    original = a.fixtures/'committed-two-factor'
    for rank in [1, 4]:
        output = a.output/'ranks'/str(rank)
        output.mkdir(parents=True, exist_ok=True)
        src = json.loads((original/'source.json').read_text())
        src[4][0][3][0][1] = src[4][2][3][0][1] = str(rank)
        source, descriptor = output/'source.json', original/'descriptor.json'
        write(source, src)
        fixture = output/'fixture'
        if not fixture.exists():
            call([a.baseline,'fixture',source,descriptor,fixture],output/'setup.json')
        producer, validator = fixture/'producer/inputs.json', fixture/'validator/inputs.json'
        construction, common, physical = output/'construction.json', output/'common.json', output/'physical.json'
        built = call([a.compiler,'protocol-construct',source,descriptor],construction)
        write(common,built[2]);call([a.compiler,'protocol-compile',common],physical)
        direct, native = output/'direct.proof', output/'native.proof'
        call([a.baseline,'prove-development',source,descriptor,producer,direct,'1'],output/'direct-prove.json')
        report = call([a.baseline,'validate',source,descriptor,validator,direct,'1'],output/'direct-validate.json')
        call([a.host,'produce-artifact',source,descriptor,construction,physical,producer,
              a.compiler,a.participant_checker,native,str(3*rank+6)],output/'native-prove.json')
        call([a.host,'validate-artifact',source,descriptor,construction,physical,validator,
              a.compiler,a.participant_checker,direct,str(3*rank+6)],output/'native-validate-direct.json')
        checked(f'rank {rank}: direct and native deterministic proof bytes equal',direct.read_bytes()==native.read_bytes())
        lean=run_reference(a.lean,a.primitive,source,descriptor,validator,direct,output/'lean',memo=memo)
        checked(f'rank {rank}: original-source Lean accepts',lean[1][0]=='accepted')
        checked(f'rank {rank}: exact frame and challenge equality',direct_frames(report)==reference_frames(lean))

    for name,digest in binaries.items():
        checked('binary remained fixed: '+name,hashlib.sha256(getattr(a,name).read_bytes()).hexdigest()==digest)
    write(a.output/'commands.json',receipts)
    write(a.output/'summary.json',{'status':'passed','checks':len(checks),'names':checks,
                                  'binary_sha256':binaries,'environment':platform.uname()._asdict(),
                                  'scope':'fixtures/direct baseline, not whole Goal2; negative cases preserve exact public requests in Lean replies'})
    print(json.dumps({'status':'passed','checks':len(checks),'output':str(a.output)}))


if __name__=='__main__':
    main()
