#include "mlir/IR/Builders.h"
#include "zkc/Dialect/IR.h"
#include "zkc/Protocol/Domains.h"
#include "zkc/Protocol/Kernels.h"
#include "zkc/Protocol/Module.h"
#include "zkc/Target/Json.h"
#include "llvm/ADT/StringSet.h"

using namespace llvm;
using namespace mlir;
namespace zkc::protocol {
ArrayRef<Kernel> kernels() {
  static const std::vector<Kernel> table = {
      {"resource_unit.create", "pir.resource_unit_create", {}, {"resource_unit"}},
      {"resource_unit.pass", "pir.resource_unit_pass", {"resource_unit"}, {"resource_unit"}},
      {"resource_unit.consume", "pir.resource_unit_consume", {"resource_unit"}, {}},
      {"external.monero.init",
       "algebra.external_monero_init",
       {"indices"},
       {"indices"}},
      {"external.monero.hash",
       "algebra.external_monero_hash",
       {"indices"},
       {"indices"}},
      {"external.monero.update",
       "algebra.external_monero_update",
       {"indices", "indices"},
       {"indices", "indices"}},
      {"external.openvm.init", "algebra.external_openvm_init", {}, {"indices"}},
      {"external.openvm.observe",
       "algebra.external_openvm_observe",
       {"indices", "indices"},
       {"indices"}},
      {"external.openvm.sample",
       "algebra.external_openvm_sample",
       {"indices"},
       {"indices", "index"}},
      {"external.openvm.sample_ext",
       "algebra.external_openvm_sample_ext",
       {"indices"},
       {"indices", "indices"}},
      {"external.openvm.sample_bits",
       "algebra.external_openvm_sample_bits",
       {"indices", "index"},
       {"indices", "index"}},
      {"external.openvm.check_witness",
       "algebra.external_openvm_check_witness",
       {"indices", "index", "index"},
       {"indices", "bool"}},
      {"index.constant",
       "algebra.index_constant",
       {},
       {"index"},
       OperationContracts::exactDomainValue(DomainValueRule::Constant, true)},
      {"index.add", "algebra.index_add", {"index", "index"}, {"index"}},
      {"index.sub", "algebra.index_sub", {"index", "index"}, {"index"}},
      {"index.mul", "algebra.index_mul", {"index", "index"}, {"index"}},
      {"index.div",
       "algebra.index_div",
       {"index", "index"},
       {"index"},
       OperationContracts::exactDomainValue(DomainValueRule::Divide)},
      {"index.mod", "algebra.index_mod", {"index", "index"}, {"index"}},
      {"index.equal", "algebra.index_equal", {"index", "index"}, {"bool"}},
      {"index.less", "algebra.index_less", {"index", "index"}, {"bool"}},
      {"indices.empty", "algebra.indices_empty", {}, {"indices"}},
      {"indices.append",
       "algebra.indices_append",
       {"indices", "index"},
       {"indices"}},
      {"indices.at", "algebra.indices_at", {"indices", "index"}, {"index"}},
      {"indices.length", "algebra.indices_length", {"indices"}, {"index"}},
      {"vector.get", "algebra.vector_get", {"vector", "index"}, {"field"}},
      {"vector.slice",
       "algebra.vector_slice",
       {"vector", "index", "index"},
       {"vector"}},
      {"vector.length",
       "algebra.vector_length",
       {"vector"},
       {"index"},
       OperationContracts::exactDomainValue(DomainValueRule::Length)},
      {"vector.rotate",
       "algebra.vector_rotate",
       {"vector", "index"},
       {"vector"}},
      {"vector.interleave",
       "algebra.vector_interleave",
       {"vector", "vector"},
       {"vector"}},
      {"vector.prefix_product",
       "algebra.vector_prefix_product",
       {"vector"},
       {"vector"}},
      {"vector.prefix_sum",
       "algebra.vector_prefix_sum",
       {"vector"},
       {"vector"}},
      {"vector.inverse", "algebra.vector_inverse", {"vector"}, {"vector"}},
      {"vector.embed", "algebra.vector_embed", {"vector"}, {"vector"}},
      {"vector.fill", "algebra.vector_fill", {"field", "index"}, {"vector"}},
      {"vector.geometric",
       "algebra.vector_geometric",
       {"field", "index"},
       {"vector"}},
      {"field.from_index", "algebra.field_from_index", {"index"}, {"field"}},
      {"poly.coefficient_count",
       "poly.coefficient_count",
       {"polynomial"},
       {"index"}},
      {"poly.coset_evaluate",
       "poly.coset_evaluate",
       {"polynomial", "field", "index"},
       {"vector"},
       OperationContracts::onCoset({1, 2, false, 0, false})},
      {"poly.coset_interpolate",
       "poly.coset_interpolate",
       {"vector", "field"},
       {"polynomial"},
       OperationContracts::onCoset({1, 0, true, {}, false})},
      {"poly.domain_point",
       "poly.domain_point",
       {"field", "index", "index"},
       {"field"},
       OperationContracts::onCoset({0, 1, false, {}, false})},
      {"poly.domain_root", "poly.domain_root", {"index"}, {"field"}},
      {"poly.domain_points",
       "poly.domain_points",
       {"field", "index"},
       {"vector"},
       OperationContracts::onCoset({0, 1, false, 0, false})},
      {"poly.even_odd_fold",
       "poly.even_odd_fold",
       {"vector", "field", "field"},
       {"vector"},
       OperationContracts::onCoset({1, 0, true, 0, true})},
      {"poly.divide_opening",
       "poly.divide_opening",
       {"polynomial", "field", "field"},
       {"polynomial"}},
      {"poly.opening_quotient",
       "poly.opening_quotient",
       {"vector", "field", "field", "field"},
       {"vector"},
       OperationContracts::onCoset({1, 0, true, 0, false})},
      {"field.sub", "algebra.subtract", {"field", "field"}, {"field"}},
      {"field.neg", "algebra.negate", {"field"}, {"field"}},
      {"field.inverse", "algebra.inverse", {"field"}, {"field"}},
      {"field.embed", "algebra.embed", {"field"}, {"field"}},
      {"matrix.mul_vector",
       "algebra.matrix_mul_vector",
       {"matrix", "vector"},
       {"vector"}},
      {"matrix.transpose_mul_vector",
       "algebra.matrix_transpose_mul_vector",
       {"matrix", "vector"},
       {"vector"}},
      {"matrix.bilinear",
       "algebra.matrix_bilinear",
       {"matrix", "vector", "vector"},
       {"field"}},
      {"matrix.shape_check",
       "algebra.matrix_shape_check",
       {"matrix"},
       {"bool"}},
      {"matrix.identity_check",
       "algebra.matrix_identity_check",
       {"matrix"},
       {"bool"}},
      {"vector.constant", "algebra.vector_constant", {}, {"vector"}},
      {"vector.scatter_sum",
       "algebra.vector_scatter_sum",
       {"vector"},
       {"vector"}},
      {"vector.empty", "algebra.vector_empty", {}, {"vector"}},
      {"vector.append",
       "algebra.vector_append",
       {"vector", "field"},
       {"vector"}},
      {"vector.splat", "algebra.vector_splat", {"field"}, {"vector"}},
      {"vector.powers", "algebra.vector_powers", {"field"}, {"vector"}},
      {"vector.add", "algebra.vector_add", {"vector", "vector"}, {"vector"}},
      {"vector.sub", "algebra.vector_sub", {"vector", "vector"}, {"vector"}},
      {"vector.mul",
       "algebra.vector_mul",
       {"vector", "vector"},
       {"vector"},
       OperationContracts::diagonal()},
      {"vector.dot",
       "algebra.vector_dot",
       {"vector", "vector"},
       {"field"},
       OperationContracts::contraction()},
      {"vector.concat",
       "algebra.vector_concat",
       {"vector", "vector"},
       {"vector"}},
      {"vector.kronecker",
       "algebra.vector_kronecker",
       {"vector", "vector"},
       {"vector"}},
      {"vector.matvec",
       "algebra.vector_matvec",
       {"vector", "vector"},
       {"vector"}},
      {"vector.scale", "algebra.vector_scale", {"vector", "field"}, {"vector"}},
      {"vector.sum", "algebra.vector_sum", {"vector"}, {"field"}},
      {"vector.split",
       "algebra.vector_split",
       {"vector"},
       {"vector", "vector"}},
      {"vector.at", "algebra.vector_at", {"vector"}, {"field"}},
      {"vector.length_check",
       "algebra.vector_length_check",
       {"vector"},
       {"bool"}},
      {"vector.gather", "algebra.vector_gather", {"vector"}, {"vector"}},
      {"vector.from_point", "poly.point_to_vector", {"point"}, {"vector"}},
      {"vector.from_table", "poly.table_to_vector", {"table"}, {"vector"}},
      {"vector.to_point", "poly.point_from_vector", {"vector"}, {"point"}},
      {"vector.to_table", "poly.table_from_vector", {"vector"}, {"table"}},
      {"poly.equality_weights", "poly.equality_weights", {"point"}, {"vector"}},
      {"poly.from_coefficients",
       "poly.from_coefficients",
       {"vector"},
       {"polynomial"}},
      {"poly.coefficients", "poly.coefficients", {"polynomial"}, {"vector"}},
      {"poly.degree_check", "poly.degree_check", {"polynomial"}, {"bool"}},
      {"poly.univariate_evaluate",
       "poly.univariate_evaluate",
       {"polynomial", "field"},
       {"field"}},
      {"poly.univariate_boundary",
       "poly.univariate_boundary",
       {"polynomial"},
       {"field"}},
      {"random.vector",
       "pir.random_vector",
       {"rng"},
       {"vector", "rng"},
       OperationContracts::sample(RandomnessProvider::Entropy,
                                  SampleDomain::FieldVector)},
      {"curve.neg", "algebra.curve_negate", {"group"}, {"group"}},
      {"curve.nonidentity", "algebra.curve_nonidentity", {"group"}, {"bool"}},
      {"curve.msm",
       "algebra.curve_msm",
       {"vector", "groups"},
       {"group"},
       OperationContracts::contraction()},
      {"curve.scale_each",
       "algebra.curve_scale_each",
       {"vector", "groups"},
       {"groups"},
       OperationContracts::diagonal()},
      {"curve.vector_add",
       "algebra.curve_vector_add",
       {"groups", "groups"},
       {"groups"}},
      {"curve.vector_scale",
       "algebra.curve_vector_scale",
       {"groups", "field"},
       {"groups"}},
      {"curve.split", "algebra.curve_split", {"groups"}, {"groups", "groups"}},
      {"curve.concat",
       "algebra.curve_concat",
       {"groups", "groups"},
       {"groups"}},
      {"pairing.check",
       "algebra.pairing_check",
       {"groups", "groups"},
       {"bool"}},
      {"field.constant",
       "algebra.constant",
       {},
       {"field"},
       OperationContracts::exactDomainValue(DomainValueRule::Constant, true)},
      {"field.add",
       "algebra.sum",
       {"field", "field"},
       {"field"},
       OperationContracts::replay()},
      {"field.mul",
       "algebra.product",
       {"field", "field"},
       {"field"},
       OperationContracts::exactDomainValue(DomainValueRule::Multiply, true)},
      {"field.equal",
       "algebra.compare",
       {"field", "field"},
       {"bool"},
       OperationContracts::replay()},
      {"bool.and",
       "pir.and",
       {"bool", "bool"},
       {"bool"},
       OperationContracts::booleanConjunction()},
      {"bool.not", "pir.not", {"bool"}, {"bool"}, OperationContracts::replay()},
      {"bool.or",
       "pir.or",
       {"bool", "bool"},
       {"bool"},
       OperationContracts::replay()},
      {"control.require",
       "pir.require",
       {"bool"},
       {},
       OperationContracts::guard()},
      {"poly.product_sum", "poly.product_sum", {"table", "table"}, {"field"}},
      {"poly.product_round",
       "poly.product_round",
       {"table", "table"},
       {"round"}},
      {"poly.boundary",
       "poly.boundary",
       {"round"},
       {"field"},
       OperationContracts::replay()},
      {"poly.round_evaluate",
       "poly.round_evaluate",
       {"round", "field"},
       {"field"},
       OperationContracts::replay()},
      {"poly.fold", "poly.fold", {"table", "field"}, {"table"}},
      {"poly.evaluate", "poly.mle_evaluate", {"table", "point"}, {"field"}},
      {"poly.empty_point",
       "poly.empty_point",
       {},
       {"point"},
       OperationContracts::replay()},
      {"poly.append_point",
       "poly.append_point",
       {"point", "field"},
       {"point"},
       OperationContracts::replay()},
      {"oracle.commit",
       "oracle.commit",
       {"vector", "index"},
       {"commitment", "opening_state"}},
      {"oracle.open",
       "oracle.open",
       {"opening_state", "index"},
       {"vector", "proof"}},
      {"oracle.check",
       "oracle.check",
       {"commitment", "index", "index", "index", "vector", "proof"},
       {"bool"}},
      {"commitments.empty", "oracle.commitments_empty", {}, {"commitments"}},
      {"commitments.append",
       "oracle.commitments_append",
       {"commitments", "commitment"},
       {"commitments"}},
      {"commitments.at",
       "oracle.commitments_at",
       {"commitments", "index"},
       {"commitment"}},
      {"commitments.length",
       "oracle.commitments_length",
       {"commitments"},
       {"index"}},
      {"opening_states.empty",
       "oracle.opening_states_empty",
       {},
       {"opening_states"}},
      {"opening_states.append",
       "oracle.opening_states_append",
       {"opening_states", "opening_state"},
       {"opening_states"}},
      {"opening_states.at",
       "oracle.opening_states_at",
       {"opening_states", "index"},
       {"opening_state"}},
      {"opening_states.length",
       "oracle.opening_states_length",
       {"opening_states"},
       {"index"}},
      {"pcs.commit",
       "pcs.commit",
       {"prover_key", "table"},
       {"commitment", "opening_state"}},
      {"pcs.open", "pcs.open", {"opening_state", "point"}, {"field", "proof"}},
      {"pcs.check",
       "pcs.check",
       {"verifier_key", "commitment", "point", "field", "proof"},
       {"bool"}},
      {"random.index",
       "pir.random_index",
       {"rng", "index"},
       {"index", "rng"},
       OperationContracts::sample(RandomnessProvider::Entropy,
                                  SampleDomain::BoundedIndex, 1,
                                  "transcript.draw_index")},
      {"transcript.draw_index",
       "pir.transcript_draw_index",
       {"transcript", "index"},
       {"index", "transcript"},
       OperationContracts::sample(RandomnessProvider::Transcript,
                                  SampleDomain::BoundedIndex, 1)},
      {"random.draw",
       "pir.random_draw",
       {"rng"},
       {"field", "rng"},
       OperationContracts::sample(RandomnessProvider::Entropy,
                                  SampleDomain::Field, {},
                                  "transcript.challenge")},
  };
  static const std::vector<Kernel> installed = [&] {
    auto all = table;
    all.insert(all.end(),
               {{"pcs.equal",
                 "pcs.equal",
                 {"commitment", "commitment"},
                 {"bool"},
                 OperationContracts::replay()},
                {"curve.generator",
                 "algebra.curve_generator",
                 {},
                 {"group"},
                 OperationContracts::replay()},
                {"curve.add",
                 "algebra.curve_add",
                 {"group", "group"},
                 {"group"},
                 OperationContracts::replay()},
                {"curve.scale",
                 "algebra.curve_scale",
                 {"group", "field"},
                 {"group"},
                 OperationContracts::replay()},
                {"curve.equal",
                 "algebra.curve_equal",
                 {"group", "group"},
                 {"bool"},
                 OperationContracts::replay()},
                {"curve.empty",
                 "algebra.curve_empty",
                 {},
                 {"groups"},
                 OperationContracts::replay()},
                {"curve.append",
                 "algebra.curve_append",
                 {"groups", "group"},
                 {"groups"},
                 OperationContracts::replay()},
                {"curve.at",
                 "algebra.curve_at",
                 {"groups"},
                 {"group"},
                 OperationContracts::replay()},
                {"curve.get",
                 "algebra.curve_get",
                 {"groups", "index"},
                 {"group"},
                 OperationContracts::replay()},
                {"curve.length",
                 "algebra.curve_length",
                 {"groups"},
                 {"index"},
                 OperationContracts::replay()},
                {"curve.commit",
                 "algebra.curve_commit",
                 {"groups", "nonce"},
                 {"groups", "nonce"}},
                {"curve.response",
                 "algebra.curve_response",
                 {"field", "field", "nonce"},
                 {"field"}},
                {"transcript.challenge",
                 "pir.transcript_challenge",
                 {"transcript"},
                 {"field", "transcript"},
                 OperationContracts::sample(RandomnessProvider::Transcript,
                                            SampleDomain::Field)}});
    // Owned strings below have static lifetime, including their StringRefs.
    static const std::vector<std::string> kinds = {
        "bool",       "field",      "table", "point",   "round",
        "commitment", "proof",      "group", "groups",  "matrix",
        "vector",     "polynomial", "index", "indices", "commitments"};
    static const std::vector<std::string> keys = [] {
      std::vector<std::string> out;
      for (const auto &kind : kinds)
        out.push_back("transcript.observe." + kind);
      return out;
    }();
    for (size_t i = 0; i < kinds.size(); ++i)
      all.push_back({keys[i],
                     "pir.transcript_observe",
                     {"transcript", kinds[i]},
                     {"transcript"},
                     OperationContracts::transcriptObservation()});
    return all;
  }();
  return installed;
}
StringRef fieldModulus(StringRef identity) {
  const auto *domain = installedDomains().domain(identity);
  return domain && domain->sort == "Field" ? StringRef(domain->modulus)
                                           : StringRef{};
}

Error checkParameters(StringRef key, const source::Names &parameters,
                      StringRef field) {
  unsigned count = 0;
  if (key.starts_with("transcript."))
    count = 5;
  else if (key == "matrix.shape_check")
    count = 2;
  else if (key == "vector.matvec")
    count = 3;
  else if (key == "index.constant" || key == "field.constant" ||
           key == "curve.at" || key == "vector.splat" ||
           key == "vector.powers" || key == "vector.at" ||
           key == "vector.length_check" || key == "poly.degree_check" ||
           key == "random.vector" || key == "matrix.identity_check")
    count = 1;
  if (key == "vector.scatter_sum" && parameters.empty())
    return error("interactive-kernel-parameters");
  if (key != "vector.gather" && key != "vector.constant" &&
      key != "vector.scatter_sum" && parameters.size() != count)
    return error("interactive-kernel-parameters");
  if (key == "matrix.identity_check") {
    StringRef digest = parameters.front();
    if (digest.size() != 64 || !all_of(digest, [](char c) {
          return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
        }))
      return error("interactive-kernel-parameters");
    return Error::success();
  }
  if (key.starts_with("transcript.")) {
    for (const auto &p : parameters)
      if (p.empty() || p.size() > 128 || !all_of(p, [](char c) {
            return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                   (c >= '0' && c <= '9') || c == '_' || c == '.' || c == '-';
          }))
        return error("interactive-transcript-origin");
    return Error::success();
  }
  for (const auto &parameter : parameters) {
    StringRef n = parameter;
    auto code = (key == "field.constant" || key == "vector.constant")
                    ? "interactive-constant"
                : key == "curve.at" ? "interactive-index"
                                    : "interactive-kernel-parameters";
    if (n.empty() || !all_of(n, [](char c) { return c >= '0' && c <= '9'; }))
      return error("expected-natural");
    if (n.size() > 1 && n.front() == '0')
      return error("noncanonical-natural");
    if (key == "field.constant" || key == "vector.constant") {
      StringRef modulus = fieldModulus(field);
      if (modulus.empty() || n.size() > modulus.size() ||
          (n.size() == modulus.size() && n >= modulus))
        return error(code);
    } else {
      // Curve indices and vector sizes, positions and degrees share one
      // bound: no vector the runtimes provide is longer.
      static const llvm::StringSet<> extents{
          "curve.at",      "vector.splat",        "vector.powers",
          "vector.at",     "vector.length_check", "poly.degree_check",
          "random.vector", "vector.gather",       "vector.matvec"};
      uint64_t natural;
      if (n.getAsInteger(10, natural) ||
          (extents.contains(key) && natural > 1048576) ||
          (key == "matrix.shape_check" && natural > 65536))
        return error(code);
    }
  }
  if (key == "vector.matvec" && parameters[2] != "0" && parameters[2] != "1")
    return error("interactive-kernel-parameters");
  return Error::success();
}
} // namespace zkc::protocol
