"""Authored external construction uses ordinary data, calls, control and proof IO."""
import json
import re
from pathlib import Path

from cases import case, counted
from commands import Commands
from tools import compiler, optimizer, records, canonical_program, tool

OUT = records()
commands = Commands(OUT)
fixtures = Path(__file__).parent / "fixtures/mathematical"
manifest = []


def replace_once(text, old, new):
    assert text.count(old) == 1, old
    return text.replace(old, new, 1)


for suffix, options in [("", []), ("_plain", ["--no-simplify"]), ("_release", ["--release-storage"])]:
    with case(f"bounded search termination{suffix}"):
        name = 'openvm_early' + suffix
        source = (fixtures / 'authored-openvm.mlir').read_text()
        source = source.replace(' local.func @search',
            ' "local.binding"() {sym_name="not",contract="bool.not",arguments=[],implementation=""} : ()->()\n local.func @search')
        source = source.replace('"local.yield"(%next#0,%next#1,%state,%width,%choices) : (ui64,i1,!words,ui64,!words)->()',
            '''%again = "algebra.exec.bool_not"(%next#1) {binding=@not,parameters=[],site="continue"} : (i1)->i1
     "local.condition"(%again,%next#0,%next#1,%state,%width,%choices) : (i1,ui64,i1,!words,ui64,!words)->()''')
        src, pol = OUT / f'{name}.mlir', OUT / f'{name}.policy'
        src.write_text(source)
        pol.write_text(json.dumps(['zkc.native-proof-policy/5', 'main', 'P', 'V', '0', '', '', ['0', '1', '2'], []]))
        (OUT / f'{name}.deployment').write_text(commands.run([compiler, 'protocol-proof', src, pol, *options]))
        manifest.append(dict(name=name, family='openvm', early=True))

# Conditional loops keep an explicit flag through import/export. Value names
# are regenerated by import, so compare the canonical second round trip.
with case("conditional loop import and malformed terminators"):
    source = (OUT / "openvm_early.mlir").read_text()
    short = source.replace(
        '"local.condition"(%again,%next#0,%next#1,%state,%width,%choices) : (i1,ui64,i1,!words,ui64,!words)->()',
        '"local.condition"(%again) : (i1)->()')
    assert short != source
    commands.run([optimizer, "--verify-each"], stdin=short, refuses="control flow edge")
    program = json.loads((OUT / "openvm_early.deployment").read_text())[4]
    canonical = canonical_program(commands, program)
    assert '"for_while"' in canonical
    assert json.loads(canonical_program(commands, canonical)) == json.loads(canonical)
    malformed = json.loads(canonical)

    def stop_conditional_loop(value):
        if not isinstance(value, list):
            return 0
        if value and value[0] == "for_while":
            value[7] = [["stop", "halt", "abort"]]
            return 1
        return sum(stop_conditional_loop(child) for child in value)

    assert stop_conditional_loop(malformed) == 1
    commands.run([tool("program_codec")], stdin=json.dumps(malformed),
                 refuses="local-control-yield")

for family in ("monero", "openvm"):
    source = (fixtures / f"authored-{family}.mlir").read_text()
    policy = OUT / f"{family}.policy"
    policy.write_text(json.dumps(["zkc.native-proof-policy/5", "main", "P", "V", "0",
                                  "", "", ["0", "1", "2"], []]))
    for suffix, options in [("", []), ("_plain", ["--no-simplify"]),
                            ("_release", ["--release-storage"]),
                            ("_plain_release", ["--no-simplify", "--release-storage"])]:
        name = family + suffix
        with case(name):
            src = OUT / f"{name}.mlir"
            src.write_text(source)
            deployment = commands.run([compiler, "protocol-proof", src, policy, *options])
            envelope = json.loads(deployment)
            assert envelope[0] == "zkc.native-proof/5"
            assert "external." in envelope[4]
            assert "transcript.native." not in envelope[4]
            assert len(envelope[4]) < 40000
            (OUT / f"{name}.deployment").write_text(deployment)
            manifest.append(dict(name=name, family=family))

    with case(f"{family} actual source correspondence"):
        src = fixtures / f"authored-{family}.mlir"
        candidate = commands.run([compiler, "protocol-construct-proof", src, policy])
        path = OUT / f"{family}.candidate.mlir"
        path.write_text(candidate)
        commands.run([compiler, "protocol-check-proof", src, policy, path])
        operation = "monero_update" if family == "monero" else "openvm_observe"
        changed, n = re.subn(r'("crypto.exec.' + operation + r'"\()(%\w+), (%\w+)',
                             r'\1\3, \2', candidate, count=1)
        assert n == 1
        path.write_text(changed)
        commands.run([compiler, "protocol-check-proof", src, policy, path],
                     refuses="native-proof-correspondence")

    if family == "openvm":
        for suffix, options in [("", []), ("_plain", ["--no-simplify"]),
                                ("_release", ["--release-storage"])]:
            with case(f"unused repeated trial{suffix}"):
                name = "openvm_duplicate" + suffix
                line = next(line for line in source.splitlines() if '%checked:2 =' in line)
                repeated = replace_once(source, line, line.replace('%checked:2', '%unused:2').replace('site="trial"', 'site="duplicate"') + '\n' + line)
                src = OUT / f"{name}.mlir"
                src.write_text(repeated)
                (OUT / f"{name}.deployment").write_text(commands.run([compiler, "protocol-proof", src, policy, *options]))
                manifest.append(dict(name=name, family=family, duplicate=True))
        with case("deleted unused trial correspondence"):
            src = OUT / "openvm_duplicate.mlir"
            candidate = commands.run([compiler, "protocol-construct-proof", src, policy])
            path = OUT / "openvm_duplicate.candidate.mlir"
            path.write_text(candidate)
            commands.run([compiler, "protocol-check-proof", src, policy, path])
            line = next(line for line in candidate.splitlines()
                        if '"crypto.exec.openvm_check_witness"' in line and 'site = "duplicate"' in line)
            path.write_text(replace_once(candidate, line, ""))
            commands.run([compiler, "protocol-check-proof", src, policy, path],
                         refuses="native-proof-correspondence")

    # Imported snapshots are ordinary public configuration, checked by the next
    # primitive. They are deliberately not host-issued affine capabilities.
    with case(f"{family} snapshot input"):
        name = family + "_snapshot"
        if family == "monero":
            source = replace_once(source,
                '%p = "protocol.local_call"(%seed) {callee=@init,role="P",site="init_p"} : (!words)->!words', '')
            source = replace_once(source,
                '%v = "protocol.local_call"(%seed) {callee=@init,role="V",site="init_v"} : (!words)->!words', '')
            source = replace_once(source, '(%p,%context)', '(%seed,%context)')
            source = replace_once(source, '(%v,%context)', '(%seed,%context)')
        else:
            # The context port now carries an explicit snapshot. Zero-word
            # observation validates it without changing its state.
            source = replace_once(source, 'contract="external.openvm.init"', 'contract="indices.empty"')
            source = replace_once(source, '"crypto.exec.openvm_init"', '"algebra.exec.indices_empty"')
            source = replace_once(source, '(%p,%context)', '(%context,%p)')
            source = replace_once(source, '(%v,%context)', '(%context,%v)')
        src = OUT / f"{name}.mlir"
        src.write_text(source)
        (OUT / f"{name}.deployment").write_text(commands.run([compiler, "protocol-proof", src, policy]))
        manifest.append(dict(name=name, family=family, snapshot=True))

for suffix, options in [("", []), ("_plain", ["--no-simplify"]), ("_release", ["--release-storage"])]:
    with case(f"authored participant abandonment{suffix}"):
        name = "prefix_abandon" + suffix
        source = (fixtures / 'authored-prefix.mlir').read_text()
        source = source.replace('   %claim =', '''   %yes = arith.constant true
   %retry = arith.xori %prepared#1,%yes : i1
   %rng_next = "protocol.finish_if"(%retry,%prepared#1,%prepared#2) {owner="P",site="abandon"} : (i1,i1,!rng)->!rng
   %claim =''').replace('(%ok,%prepared#1,%prepared#2)', '(%ok,%prepared#1,%rng_next)')
        src, pol = OUT / f'{name}.mlir', OUT / f'{name}.policy'
        src.write_text(source)
        pol.write_text(json.dumps(['zkc.native-proof-policy/5', 'main', 'P', 'V', '0', '', '', ['0', '1'], []]))
        (OUT / f'{name}.deployment').write_text(commands.run([compiler, 'protocol-proof', src, pol, *options]))
        manifest.append(dict(name=name, family='prefix', early=True))

for suffix, options in [("", []), ("_plain", ["--no-simplify"]),
                        ("_release", ["--release-storage"])]:
    with case(f"retained prefix and guarded suffix{suffix}"):
        name = "prefix" + suffix
        policy = OUT / "prefix.policy"
        policy.write_text(json.dumps(["zkc.native-proof-policy/5", "main", "P", "V", "0",
                                      "", "", ["0", "1"], []]))
        (OUT / f"{name}.deployment").write_text(commands.run([
            compiler, "protocol-proof", fixtures / "authored-prefix.mlir", policy, *options]))
        manifest.append(dict(name=name, family="prefix"))

(OUT / "manifest.json").write_text(json.dumps(manifest))
counted()
