//! Native callable shapes, maintained independently from Rust admission.
use Type::*;
use zkc_runtime::interactive::{AttributeRule as A, Type};
pub(crate) const CONTRACTS: &[super::catalogue::Contract] = &[
    ("vector.get", &[Vector, Index], &[Field], A::None),
    ("vector.slice", &[Vector, Index, Index], &[Vector], A::None),
    ("vector.length", &[Vector], &[Index], A::None),
    ("vector.rotate", &[Vector, Index], &[Vector], A::None),
    ("vector.interleave", &[Vector, Vector], &[Vector], A::None),
    ("vector.prefix_product", &[Vector], &[Vector], A::None),
    ("vector.prefix_sum", &[Vector], &[Vector], A::None),
    ("vector.inverse", &[Vector], &[Vector], A::None),
    ("vector.embed", &[Vector], &[Vector], A::None),
    ("vector.fill", &[Field, Index], &[Vector], A::None),
    ("vector.geometric", &[Field, Index], &[Vector], A::None),
    ("field.from_index", &[Index], &[Field], A::None),
    ("poly.coefficient_count", &[Polynomial], &[Index], A::None),
    (
        "poly.coset_evaluate",
        &[Polynomial, Field, Index],
        &[Vector],
        A::None,
    ),
    (
        "poly.coset_interpolate",
        &[Vector, Field],
        &[Polynomial],
        A::None,
    ),
    (
        "poly.domain_point",
        &[Field, Index, Index],
        &[Field],
        A::None,
    ),
    ("poly.domain_root", &[Index], &[Field], A::None),
    ("poly.domain_points", &[Field, Index], &[Vector], A::None),
    (
        "poly.even_odd_fold",
        &[Vector, Field, Field],
        &[Vector],
        A::None,
    ),
    (
        "poly.divide_opening",
        &[Polynomial, Field, Field],
        &[Polynomial],
        A::None,
    ),
    (
        "poly.opening_quotient",
        &[Vector, Field, Field, Field],
        &[Vector],
        A::None,
    ),
    ("field.sub", &[Field, Field], &[Field], A::None),
    ("field.neg", &[Field], &[Field], A::None),
    ("field.inverse", &[Field], &[Field], A::None),
    ("matrix.mul_vector", &[Matrix, Vector], &[Vector], A::None),
    (
        "matrix.transpose_mul_vector",
        &[Matrix, Vector],
        &[Vector],
        A::None,
    ),
    (
        "matrix.bilinear",
        &[Matrix, Vector, Vector],
        &[Field],
        A::None,
    ),
    (
        "matrix.shape_check",
        &[Matrix],
        &[Bool],
        A::MatrixDimensions,
    ),
    (
        "matrix.identity_check",
        &[Matrix],
        &[Bool],
        A::MatrixIdentity,
    ),
    ("vector.constant", &[], &[Vector], A::FieldDecimals),
    ("vector.scatter_sum", &[Vector], &[Vector], A::ScatterShape),
    ("vector.empty", &[], &[Vector], A::None),
    ("vector.append", &[Vector, Field], &[Vector], A::None),
    ("vector.splat", &[Field], &[Vector], A::NaturalIndex),
    ("vector.powers", &[Field], &[Vector], A::NaturalIndex),
    ("vector.add", &[Vector, Vector], &[Vector], A::None),
    ("vector.sub", &[Vector, Vector], &[Vector], A::None),
    ("vector.mul", &[Vector, Vector], &[Vector], A::None),
    ("vector.scale", &[Vector, Field], &[Vector], A::None),
    ("vector.sum", &[Vector], &[Field], A::None),
    ("vector.dot", &[Vector, Vector], &[Field], A::None),
    ("vector.split", &[Vector], &[Vector, Vector], A::None),
    ("vector.concat", &[Vector, Vector], &[Vector], A::None),
    ("vector.at", &[Vector], &[Field], A::NaturalIndex),
    ("vector.length_check", &[Vector], &[Bool], A::NaturalIndex),
    ("vector.gather", &[Vector], &[Vector], A::NaturalIndices),
    ("vector.kronecker", &[Vector, Vector], &[Vector], A::None),
    (
        "vector.matvec",
        &[Vector, Vector],
        &[Vector],
        A::MatrixShape,
    ),
    ("vector.from_point", &[Point], &[Vector], A::None),
    ("vector.to_point", &[Vector], &[Point], A::None),
    ("vector.from_table", &[Table], &[Vector], A::None),
    ("vector.to_table", &[Vector], &[Table], A::None),
    ("poly.equality_weights", &[Point], &[Vector], A::None),
    ("poly.from_coefficients", &[Vector], &[Polynomial], A::None),
    ("poly.coefficients", &[Polynomial], &[Vector], A::None),
    ("poly.degree_check", &[Polynomial], &[Bool], A::NaturalIndex),
    (
        "poly.univariate_evaluate",
        &[Polynomial, Field],
        &[Field],
        A::None,
    ),
    ("poly.univariate_boundary", &[Polynomial], &[Field], A::None),
    ("random.vector", &[Rng], &[Vector, Rng], A::NaturalIndex),
    ("curve.neg", &[Group], &[Group], A::None),
    ("curve.nonidentity", &[Group], &[Bool], A::None),
    ("curve.msm", &[Vector, Groups], &[Group], A::None),
    ("curve.scale_each", &[Vector, Groups], &[Groups], A::None),
    ("curve.vector_add", &[Groups, Groups], &[Groups], A::None),
    ("curve.vector_scale", &[Groups, Field], &[Groups], A::None),
    ("curve.split", &[Groups], &[Groups, Groups], A::None),
    ("curve.concat", &[Groups, Groups], &[Groups], A::None),
];
