"""Binary FRI authored as ordinary protocol composition.

Small polynomial words are generated by independent integer arithmetic. These
checks cover execution and rejection obligations; they are not a proximity or
Fiat-Shamir soundness proof.
"""
import json
from pathlib import Path

import pytest

from octic_reference import P, ZERO, ONE, add, mul, coordinates

ROOT = Path(__file__).resolve().parents[2]
LIBRARY = ROOT / 'libraries/fri/lib.zkc'
EXAMPLE = ROOT / 'examples/projects/fri/main.zkc'
SHIFT = [3, 1, 0, 0, 0, 0, 0, 0]


def wire(values, *, scalar=False):
    return (b'ZKCV\x00' + bytes([26 if scalar else 27])
            + (b'' if scalar else len(values).to_bytes(4, 'little'))
            + b''.join(coordinates(v) for v in values)).hex()


def evaluate(coefficients, point):
    result = ZERO
    for coefficient in reversed(coefficients):
        result = add(coefficient, mul(point, result))
    return result


def word(coefficients, log_size, shift=SHIFT):
    size = 1 << log_size
    root = pow(1791270792, (1 << 24) // size, P)
    assert pow(root, size, P) == 1 and pow(root, size // 2, P) == P - 1
    return [evaluate(coefficients, mul(shift, [pow(root, i, P)] + [0] * 7))
            for i in range(size)]


def compile_entry(toolchain, journal, directory, *, log_size=5, terminal_log=0,
                  rounds=3, queries=8, flags=(), entry='Proof'):
    source = EXAMPLE.read_text().replace('LowDegree<Rows,5,0,3,8>',
                f'LowDegree<Rows,{log_size},{terminal_log},{rounds},{queries}>')
    path = directory / 'fri.zkc'
    path.write_text(source)
    package = directory / f'{entry}.entry'
    report = journal.json([toolchain.runtime, 'compile', f'--compiler={toolchain.compiler}',
                           f'--module=example={path}', f'--module=fri={LIBRARY}',
                           f'--entry=example::{entry}', f'--output={package}', *flags])
    return package, report['package_sha256']


def request(journal, name, values=None, *, shift=SHIFT, rounds=3, queries=8):
    return journal.write(name + '.json', {
        'format': 'zkc.entry-proof/0',
        'public': {'shift': wire([shift], scalar=True),
                   'round_count': rounds, 'query_count': queries},
        'inputs': {} if values is None else {'word': wire(values)},
    })


def messages(proof):
    at, result = 40, []
    while at < len(proof):
        size = int.from_bytes(proof[at:at + 8], 'little')
        result.append(proof[at + 8:at + 8 + size])
        at += 8 + size
    assert at == len(proof)
    return result


def replace_message(proof, index, payload):
    frames = messages(proof)
    frames[index] = payload
    return proof[:40] + b''.join(len(x).to_bytes(8, 'little') + x for x in frames)


@pytest.mark.parametrize('flags', [[], ['--no-simplify'], ['--release-storage']])
@pytest.mark.parametrize('profile', [(4, 0, 2, 8), (5, 0, 3, 8), (6, 1, 3, 12)])
def test_fri_polynomials_prove_and_verify(toolchain, journal, directory, flags, profile):
    log_size, terminal_log, rounds, queries = profile
    package, pin = compile_entry(toolchain, journal, directory, log_size=log_size,
                                terminal_log=terminal_log, rounds=rounds,
                                queries=queries, flags=flags)
    limit = 1 << (terminal_log + rounds)
    for name, coefficients in [('zero', []), ('constant', [ONE]),
                              ('maximum_degree', [[i + 1, i * i, 0, 0, 0, 0, 0, 1]
                                                  for i in range(limit)])]:
        producer = request(journal, name, word(coefficients, log_size), rounds=rounds, queries=queries)
        verifier = request(journal, name + '-verify', rounds=rounds, queries=queries)
        proof = directory / f'{name}.bin'
        made = journal.json([toolchain.runtime, 'prove', package, pin, producer, proof])
        assert made['status'] == 'produced'
        checked = journal.json([toolchain.runtime, 'verify', package, pin, verifier, proof])
        assert checked['status'] == 'accepted'
        assert len(messages(proof.read_bytes())) == rounds + 1 + 4 * rounds * queries


def test_fri_rejects_altered_commitments_openings_and_terminal(toolchain, journal, directory):
    package, pin = compile_entry(toolchain, journal, directory)
    producer = request(journal, 'producer', word([ONE, ONE, SHIFT], 5))
    verifier = request(journal, 'verifier')
    proof = directory / 'honest.bin'
    journal.run([toolchain.runtime, 'prove', package, pin, producer, proof])
    original = proof.read_bytes()
    frames = messages(original)

    def reject(name, changed, reason='artifact-stopped'):
        path = directory / f'{name}.bin'
        path.write_bytes(changed)
        journal.run([toolchain.runtime, 'verify', package, pin, verifier, path], refuses=reason)

    # Every round root is used. All queries are drawn before any opening;
    # changing an opening cannot change the positions being checked.
    for round_index in range(3):
        root = bytearray(frames[round_index])
        root[-1] ^= 1
        reject(f'root-{round_index}', replace_message(original, round_index, root))
        for side in (0, 1):
            row_index = 4 + 4 * round_index + 2 * side
            row = bytearray(frames[row_index])
            assert row[:6] == b'ZKCV\x00\x1b'
            old = int.from_bytes(row[10:14], 'little')
            row[10:14] = ((old + 1) % P).to_bytes(4, 'little')
            reject(f'row-{round_index}-{side}', replace_message(original, row_index, row))
            path = bytearray(frames[row_index + 1])
            path[-1] ^= 1
            reject(f'path-{round_index}-{side}', replace_message(original, row_index + 1, path))

    terminal = bytearray(frames[3])
    assert terminal[:6] == b'ZKCV\x00\x1b'
    old = int.from_bytes(terminal[10:14], 'little')
    terminal[10:14] = ((old + 1) % P).to_bytes(4, 'little')
    reject('terminal-value', replace_message(original, 3, terminal))
    # A canonical but degree-one terminal polynomial violates the constant bound.
    reject('terminal-degree', replace_message(original, 3, bytes.fromhex(wire([ONE, ONE]))))
    reject('truncated', original[:-1], 'proof-truncated')
    reject('trailing', original + b'\x00', 'proof-trailing')


def test_fri_checks_schedule_shape_and_degree(toolchain, journal, directory):
    package, pin = compile_entry(toolchain, journal, directory)
    values = word([ONE, SHIFT], 5)
    honest = request(journal, 'producer', values)
    proof = directory / 'honest.bin'
    journal.run([toolchain.runtime, 'prove', package, pin, honest, proof])
    for name, change in [('zero-rounds', {'rounds': 0}), ('fewer-rounds', {'rounds': 2}),
                         ('zero-queries', {'queries': 0}), ('fewer-queries', {'queries': 7}),
                         ('zero-shift', {'shift': ZERO})]:
        producer = request(journal, name, values, **change)
        # Proving drives only P; V owns the schedule predicate, so a malformed
        # public schedule may produce a proof but verification must refuse.
        candidate = directory / f'{name}.bin'
        completed = journal.attempt([toolchain.runtime, 'prove', package, pin, producer, candidate])
        if completed.returncode == 0:
            verifier = request(journal, name + '-verify', **change)
            journal.run([toolchain.runtime, 'verify', package, pin, verifier, candidate],
                        refuses='artifact-stopped')
        else:
            assert completed.returncode == 1
            report = json.loads(completed.stdout)
            assert report['status'] == 'refused' and report['phase'] == 'execution'
            expected = 'refused:coset-zero-shift' if name == 'zero-shift' else 'artifact-stopped'
            assert report['code'] == expected or report['code'].startswith(expected + ':')
            assert not candidate.exists()
    for name, altered in [('short', values[:-1]), ('empty', []),
                          ('degree-too-high', word([ZERO] * 8 + [ONE], 5))]:
        producer = request(journal, name, altered)
        candidate = directory / f'{name}.bin'
        completed = journal.attempt([toolchain.runtime, 'prove', package, pin, producer, candidate])
        if completed.returncode == 0:
            verifier = request(journal, name + '-verify')
            journal.run([toolchain.runtime, 'verify', package, pin, verifier, candidate],
                        refuses='artifact-stopped')
        else:
            assert completed.returncode == 1
            report = json.loads(completed.stdout)
            assert report['status'] == 'refused' and report['phase'] == 'execution'
            expected = 'refused:coset-zero-shift' if name == 'zero-shift' else 'artifact-stopped'
            assert report['code'] == expected or report['code'].startswith(expected + ':')
            assert not candidate.exists()


def test_fri_returns_exact_authenticated_query_values(toolchain, journal, directory):
    source = EXAMPLE.read_text().replace('use fri::{Vector, LowDegree};',
                                        'use fri::{Vector, Positions, LowDegree};')
    source = source.replace('-> (accepted: bool @V)',
                            '-> (accepted: bool @V, positions: Positions @V, values: Vector<E> @V)')
    source = source.replace('let (accepted, _, _, _)', 'let (accepted, _, positions, values)')
    source = source.replace('return (accepted = accepted);',
                            'return (accepted = accepted, positions = positions, values = values);')
    path = directory / 'observed.zkc'
    path.write_text(source)
    package = directory / 'observed.entry'
    report = journal.json([toolchain.runtime, 'compile', f'--compiler={toolchain.compiler}',
                           f'--module=example={path}', f'--module=fri={LIBRARY}',
                           '--entry=example::Run', f'--output={package}'])
    values = word([[i + 1, i, 0, 1, 0, 0, 0, 0] for i in range(8)], 5)
    shared = {'shift': wire([SHIFT], scalar=True), 'round_count': 3, 'query_count': 8}
    inputs = journal.write('run.json', {
        'format': 'zkc.entry-run/0', 'session': 'fri_query_binding',
        'roles': {'P': {'inputs': shared | {'word': wire(values)}},
                  'V': {'inputs': shared}},
    })
    outputs = directory / 'outputs.json'
    report = journal.json([toolchain.runtime, 'run', package, report['package_sha256'],
                           inputs, f'--results={outputs}'])
    assert report['status'] == 'executed'
    result = json.loads(outputs.read_text())['roles']['V']
    assert result['accepted'] is True
    positions = bytes.fromhex(result['positions'])
    assert positions[:6] == b'ZKCV\x00\x44'
    count = int.from_bytes(positions[6:10], 'little')
    selected = [int.from_bytes(positions[10 + 8 * i:18 + 8 * i], 'little')
                for i in range(count)]
    assert count == 8 and all(0 <= i < 32 for i in selected)
    assert result['values'] == wire([values[i] for i in selected])
