//! Execute actual native service carriers generated by compiler/test/native_services.py.
use std::{collections::BTreeMap, path::Path};
use zkc_backends::services::{ServiceReference, ServiceRegistry};
use zkc_backends::{Domain, EntryPolicy, NativeBackend, Policy, PublicInputs, Scalar, Value};
use zkc_runtime::interactive::{
    Action, ArtifactFormat, Backend, BackendError, BoundSignature, Frame, FrameExit, Invocation,
    OperationBinding, Packet, Runner, RuntimeError, StopKind, Value as RuntimeValue, ValueBudget,
    admit_supplied,
};

fn backend(role: &str, session: &str) -> NativeBackend {
    NativeBackend::new(
        Policy::default(),
        EntryPolicy::new(
            Domain::new(role, session, "main", None),
            None,
            PublicInputs::LocalOnly,
        ),
        None,
    )
    .unwrap()
}
fn field(value: u64) -> Value {
    Value::Field(Scalar::from(value))
}
fn check_field(value: &Value, expected: u64) {
    assert!(matches!(value, Value::Field(actual) if *actual == Scalar::from(expected)));
}
fn tape(registry: &ServiceRegistry, owner: &str, budget: u64, values: &[u64]) -> ServiceReference {
    registry
        .issue_test_tape(
            owner,
            budget,
            values.iter().copied().map(Scalar::from).collect(),
        )
        .unwrap()
}
fn load(
    bytes: &[u8],
    role: &str,
    session: &str,
    registry: &ServiceRegistry,
    references: &[ServiceReference],
    inputs: Vec<Value>,
) -> Result<Runner<NativeBackend>, RuntimeError> {
    let native = backend(role, session);
    let admitted = admit_supplied(bytes, &native).unwrap();
    assert_eq!(admitted.format(), ArtifactFormat::Program);
    assert!(admitted.checked_source().is_none());
    let endpoint = admitted
        .entry("main")
        .unwrap()
        .into_iter()
        .find(|p| p.role == role)
        .unwrap();
    let ports = endpoint
        .services
        .iter()
        .map(|p| p.name.clone())
        .zip(references.iter().cloned())
        .collect();
    let native = native.with_services(registry.clone(), ports).unwrap();
    Runner::new(&admitted, "main", role, session, native, inputs).map_err(|failure| failure.error)
}
fn local(runner: &mut Runner<NativeBackend>) -> Action<Value> {
    for _ in 0..32 {
        match runner.poll() {
            Action::Local(action) => runner.execute_local(&action.cut).unwrap(),
            action => return action,
        }
    }
    panic!("bounded participant did not reach an observable cut")
}
fn query(runner: &mut Runner<NativeBackend>, site: &str) {
    let Action::Query(action) = local(runner) else {
        panic!("expected query {site}")
    };
    assert_eq!(action.cut.site, site);
    assert_eq!(action.method, "draw");
    assert!(action.arguments.is_empty());
    assert_eq!(action.results.len(), 1);
    assert_eq!(action.results[0].1, field(0).physical_type());
    assert!(matches!(runner.poll(), Action::Query(repeated) if repeated.cut == action.cut));
    let mut wrong = action.cut.clone();
    wrong.site.push_str("_wrong");
    assert!(runner.execute_query(&wrong).is_err());
    runner.execute_query(&action.cut).unwrap();
    assert!(runner.execute_query(&action.cut).is_err());
}
fn observe(
    registry: &ServiceRegistry,
    root: &ServiceReference,
    draws: u64,
    budget: u64,
    poisoned: bool,
    leased: bool,
) {
    let observation = registry.observe(root).unwrap();
    assert_eq!(
        (observation.poisoned, observation.leased),
        (poisoned, leased)
    );
    let state = observation.state.unwrap();
    assert_eq!(
        (state.generation, state.draw_count, state.budget),
        (draws, draws, budget)
    );
}

// An installed legacy backend has no service admission hook, even though its
// data operations and frames are otherwise the same native implementation.
struct Legacy(NativeBackend);
impl Backend for Legacy {
    type Value = Value;
    fn binding_signature(&self, binding: &OperationBinding) -> Option<BoundSignature> {
        self.0.binding_signature(binding)
    }
    fn validate_value(&self, value: &Value) -> Result<(), BackendError> {
        self.0.validate_value(value)
    }
    fn enter_frame(&mut self, frame: &Frame, args: &[Value]) -> Result<(), BackendError> {
        self.0.enter_frame(frame, args)
    }
    fn leave_frame(
        &mut self,
        frame: &Frame,
        exit: FrameExit,
        values: &[Value],
    ) -> Result<(), BackendError> {
        self.0.leave_frame(frame, exit, values)
    }
    fn apply(
        &mut self,
        invocation: &Invocation<'_>,
        args: &[Value],
    ) -> Result<Vec<Value>, BackendError> {
        self.0.apply(invocation, args)
    }
}

// A faulty trusted adapter exercises the runner's post-consume refusal path.
struct InvalidReply(NativeBackend, bool);
impl Backend for InvalidReply {
    type Value = Value;
    fn service_signature(
        &self,
        contract: zkc_runtime::interactive::ServiceContract,
        method: &str,
    ) -> Option<(zkc_runtime::interactive::ServiceSignature, usize)> {
        self.0.service_signature(contract, method)
    }
    fn query(
        &mut self,
        invocation: &zkc_runtime::interactive::ServiceInvocation<'_>,
        args: &[Value],
    ) -> Result<Vec<Value>, BackendError> {
        self.0.query(invocation, args)?;
        // Deliberately violate the installed reply contract after a real consume.
        Ok(if self.1 {
            vec![Value::Bool(true)]
        } else {
            vec![]
        })
    }
    fn reject_service_reply(
        &mut self,
        invocation: &zkc_runtime::interactive::ServiceInvocation<'_>,
    ) {
        self.0.reject_service_reply(invocation);
    }
    fn binding_signature(&self, binding: &OperationBinding) -> Option<BoundSignature> {
        self.0.binding_signature(binding)
    }
    fn validate_value(&self, value: &Value) -> Result<(), BackendError> {
        self.0.validate_value(value)
    }
    fn enter_frame(&mut self, frame: &Frame, args: &[Value]) -> Result<(), BackendError> {
        self.0.enter_frame(frame, args)
    }
    fn leave_frame(
        &mut self,
        frame: &Frame,
        exit: FrameExit,
        values: &[Value],
    ) -> Result<(), BackendError> {
        self.0.leave_frame(frame, exit, values)
    }
    fn apply(
        &mut self,
        invocation: &Invocation<'_>,
        args: &[Value],
    ) -> Result<Vec<Value>, BackendError> {
        self.0.apply(invocation, args)
    }
}

struct ChangingSignature(NativeBackend, std::cell::Cell<bool>);
impl Backend for ChangingSignature {
    type Value = Value;
    fn service_signature(
        &self,
        contract: zkc_runtime::interactive::ServiceContract,
        method: &str,
    ) -> Option<(zkc_runtime::interactive::ServiceSignature, usize)> {
        let mut declared = self.0.service_signature(contract, method)?;
        if self.1.replace(true) {
            declared.0.outputs = vec![Value::Bool(true).physical_type()];
        }
        Some(declared)
    }
    fn query(
        &mut self,
        invocation: &zkc_runtime::interactive::ServiceInvocation<'_>,
        args: &[Value],
    ) -> Result<Vec<Value>, BackendError> {
        self.0.query(invocation, args)
    }
    fn reject_service_reply(
        &mut self,
        invocation: &zkc_runtime::interactive::ServiceInvocation<'_>,
    ) {
        self.0.reject_service_reply(invocation);
    }
    fn binding_signature(&self, binding: &OperationBinding) -> Option<BoundSignature> {
        self.0.binding_signature(binding)
    }
    fn validate_value(&self, value: &Value) -> Result<(), BackendError> {
        self.0.validate_value(value)
    }
    fn enter_frame(&mut self, frame: &Frame, args: &[Value]) -> Result<(), BackendError> {
        self.0.enter_frame(frame, args)
    }
    fn leave_frame(
        &mut self,
        frame: &Frame,
        exit: FrameExit,
        values: &[Value],
    ) -> Result<(), BackendError> {
        self.0.leave_frame(frame, exit, values)
    }
    fn apply(
        &mut self,
        invocation: &Invocation<'_>,
        args: &[Value],
    ) -> Result<Vec<Value>, BackendError> {
        self.0.apply(invocation, args)
    }
}

struct ForbiddenChecker;
impl zkc_runtime::interactive::Correspondence for ForbiddenChecker {
    fn check_with_mapping(
        &self,
        _: &[u8],
        _: &[u8],
        _: ArtifactFormat,
    ) -> Result<Option<zkc_runtime::interactive::SourceMap>, zkc_runtime::interactive::AdmissionError>
    {
        panic!("native services must not reach the old correspondence checker")
    }
    fn check(
        &self,
        _: &[u8],
        _: &[u8],
        _: ArtifactFormat,
    ) -> Result<(), zkc_runtime::interactive::AdmissionError> {
        panic!("native services must not reach the old correspondence checker")
    }
}

fn main() {
    let directory = std::env::args()
        .nth(1)
        .expect("generated native service carrier directory");
    let read =
        |name: &str| std::fs::read(Path::new(&directory).join(format!("{name}.json"))).unwrap();
    let bytes = read("services");
    let deferred = read("services_deferred");
    let single = read("service_single");
    assert!(admit_supplied(&bytes, &Legacy(backend("Alice", "legacy"))).is_err());

    let checked = zkc_runtime::interactive::admit_physical(
        b"source",
        &single,
        &backend("Alice", "checked"),
        &ForbiddenChecker,
    );
    assert!(
        matches!(checked, Err(error) if error.code == zkc_runtime::interactive::ErrorCode::Correspondence)
    );

    // Independent native admission of malformed carriers, before any root exists.
    for case in 0..14 {
        let mut artifact: serde_json::Value = serde_json::from_slice(&single).unwrap();
        let participant = &mut artifact[4][0];
        match case {
            0 => participant[8][0][1] = "random.bls12-381.fr/2".into(),
            1 => participant[8][0][2] = "1".into(),
            2 => participant[7][0][2] = "missing".into(),
            3 => participant[7][0][3] = "reset".into(),
            4 => participant[7][0][5] = serde_json::json!([participant[8][0][0]]),
            5 => {
                participant[5] = serde_json::Value::Array(
                    (0..1024)
                        .map(|i| serde_json::json!([format!("input_{i}"), "bool"]))
                        .collect(),
                );
            }
            6 => artifact[0] = "zkc.participants/1".into(),
            7 => {
                participant.as_array_mut().unwrap().pop();
                artifact[0] = "zkc.participants/1".into();
            }
            8 => participant[8]
                .as_array_mut()
                .unwrap()
                .push(serde_json::json!(["other", "random.bls12-381.fr/1", "0"])),
            9 => participant[5] = serde_json::json!([[participant[8][0][0], "bool"]]),
            10 => participant[7].as_array_mut().unwrap().insert(
                0,
                serde_json::json!([
                    "if",
                    "branch",
                    "condition",
                    [],
                    [["call", "hidden", "callee", [], []], ["yield", []]],
                    [["yield", []]],
                    []
                ]),
            ),
            11 => {
                let query = participant[7][0].clone();
                participant[7] = serde_json::json!([
                    ["loop", "loop", "1", [], [], [query, ["yield", []]], []],
                    ["return", []]
                ]);
            }
            12 => participant[4] = serde_json::json!([["n", "1"]]),
            13 => participant[7]
                .as_array_mut()
                .unwrap()
                .insert(0, serde_json::json!(["call", "call", "callee", [], []])),
            _ => unreachable!(),
        }
        let encoded = serde_json::to_vec(&artifact).unwrap();
        assert!(
            admit_supplied(&encoded, &backend("Alice", "malformed")).is_err(),
            "malformed case {case}"
        );
    }

    let mut bad_local: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    bad_local[3][0][4].as_array_mut().unwrap().insert(
        0,
        serde_json::json!(["query", "hidden", "service_0", "draw", [], ["out"]]),
    );
    assert!(
        admit_supplied(
            &serde_json::to_vec(&bad_local).unwrap(),
            &backend("Alice", "bad_local")
        )
        .is_err()
    );

    // All old artifact entry points refuse the profile before a service-free
    // observer can return or any classifier, codec, or verifier callback runs.
    for driver in 0..3 {
        let registry = ServiceRegistry::new(Policy::default());
        let mut observer = load(
            &bytes,
            "Observer",
            "old_driver",
            &registry,
            &[],
            vec![Value::Bool(true)],
        )
        .unwrap();
        use zkc_tools::artifact::{self, ArtifactFailure};
        let (unsupported, messages, written) = match driver {
            0 => {
                let report = artifact::produce(&mut observer, &[0; 32]);
                (
                    matches!(
                        report.outcome,
                        Err(ArtifactFailure::UnsupportedNativeProfile)
                    ),
                    report.messages,
                    report.bytes,
                )
            }
            1 => {
                let report = artifact::validate(&mut observer, &[], &[0; 32], 0, |_| {
                    panic!("boolean callback")
                });
                (
                    matches!(
                        report.outcome,
                        Err(ArtifactFailure::UnsupportedNativeProfile)
                    ),
                    report.messages,
                    report.bytes,
                )
            }
            _ => {
                let report = artifact::attempt::execute::<_, (), ()>(
                    &mut observer,
                    1024,
                    |_| panic!("classifier"),
                    |_| panic!("codec"),
                );
                (
                    matches!(
                        report.outcome,
                        Err(ArtifactFailure::UnsupportedNativeProfile)
                    ),
                    report.messages,
                    report.bytes,
                )
            }
        };
        assert!(unsupported);
        assert_eq!(
            (messages, written, observer.backend().active_frames()),
            (0, 0, 0)
        );
    }

    // Same generated program, two different host alias relations.
    for aliases in [true, false] {
        let registry = ServiceRegistry::new(Policy::default());
        let first = tape(&registry, "Alice", 4, &[5, 11, 17, 23]);
        let second = if aliases {
            first.clone()
        } else {
            tape(&registry, "Alice", 4, &[5, 11, 17, 23])
        };
        let mut alice = load(
            &bytes,
            "Alice",
            "alias_test",
            &registry,
            &[first.clone(), second.clone()],
            vec![field(3), Value::Bool(true)],
        )
        .unwrap();
        // A second runner with even the SAME session name is a different lease.
        assert!(
            load(
                &bytes,
                "Alice",
                "alias_test",
                &registry,
                &[first.clone(), second.clone()],
                vec![field(3), Value::Bool(true)]
            )
            .is_err()
        );
        query(&mut alice, "first_draw");
        query(&mut alice, "second_draw");
        query(&mut alice, "unused_draw");
        let Action::Send(action) = local(&mut alice) else {
            panic!("send after queries")
        };
        let expected = if aliases { 22 } else { 16 };
        check_field(&action.payload, expected);
        let packet = alice
            .take_send(&Action::Send(action).cut().unwrap())
            .unwrap();
        let mut bob = load(
            &bytes,
            "Bob",
            "alias_test",
            &registry,
            &[],
            vec![Value::Bool(false)],
        )
        .unwrap();
        let Action::Receive(receive) = local(&mut bob) else {
            panic!("Bob receive")
        };
        let encoded = alice.backend().encode_value(&packet.payload).unwrap();
        let decoded = bob
            .backend()
            .decode_typed_value(receive.ty.clone(), &encoded)
            .unwrap();
        bob.deliver(Packet {
            envelope: receive.envelope,
            ty: decoded.physical_type(),
            payload: decoded,
        })
        .unwrap();
        let Action::Returned(outputs) = local(&mut bob) else {
            panic!("Bob deferred return")
        };
        check_field(&outputs[0], expected);
        assert!(matches!(outputs[1], Value::Bool(false)));
        assert!(matches!(local(&mut alice), Action::Returned(_)));
        assert_eq!(alice.backend().active_frames(), 0);
        observe(
            &registry,
            &first,
            if aliases { 3 } else { 2 },
            if aliases { 1 } else { 2 },
            false,
            false,
        );
        if !aliases {
            observe(&registry, &second, 1, 3, false, false);
        }
        let mut observer = load(
            &bytes,
            "Observer",
            "alias_test",
            &registry,
            &[],
            vec![Value::Bool(true)],
        )
        .unwrap();
        assert!(matches!(local(&mut observer), Action::Returned(values) if values.is_empty()));
        let mut next = load(
            &single,
            "Alice",
            "next_session",
            &registry,
            std::slice::from_ref(&first),
            vec![],
        )
        .unwrap();
        query(&mut next, "draw");
        let Action::Returned(values) = local(&mut next) else {
            panic!("sequential return")
        };
        check_field(&values[0], if aliases { 23 } else { 17 });
    }

    for (budget, values, draw_count, remainder) in [(1, vec![5], 2, 0), (2, vec![], 1, 1)] {
        let registry = ServiceRegistry::new(Policy::default());
        let root = tape(&registry, "Alice", budget, &values);
        let mut owner = load(
            &bytes,
            "Alice",
            "failure",
            &registry,
            &[root.clone(), root.clone()],
            vec![field(3), Value::Bool(true)],
        )
        .unwrap();
        query(&mut owner, "first_draw");
        if draw_count == 2 {
            query(&mut owner, "second_draw");
        }
        assert!(
            matches!(local(&mut owner), Action::Stopped(stop) if matches!(stop.kind, StopKind::Backend(_)))
        );
        assert_eq!(owner.backend().active_frames(), 0);
        observe(&registry, &root, draw_count, remainder, true, false);
        assert!(
            load(
                &single,
                "Alice",
                "poisoned",
                &registry,
                std::slice::from_ref(&root),
                vec![]
            )
            .is_err()
        );
    }

    // Guard is an early stop; a returned false value does not skip queries.
    for guarded in [true, false] {
        let registry = ServiceRegistry::new(Policy::default());
        let root = tape(&registry, "Alice", 4, &[5, 11, 17, 23]);
        let mut owner = load(
            if guarded { &bytes } else { &deferred },
            "Alice",
            "guard",
            &registry,
            &[root.clone(), root.clone()],
            vec![field(3), Value::Bool(false)],
        )
        .unwrap();
        if guarded {
            assert!(
                matches!(local(&mut owner), Action::Stopped(stop) if matches!(stop.kind, StopKind::Explicit(_)))
            );
            observe(&registry, &root, 0, 4, false, false);
        } else {
            query(&mut owner, "first_draw");
            query(&mut owner, "second_draw");
            query(&mut owner, "unused_draw");
            owner.cancel();
            observe(&registry, &root, 3, 1, false, false);
        }
    }

    // Cancellation and Drop release views and leases, retaining completed draws.
    let registry = ServiceRegistry::new(Policy::default());
    let root = tape(&registry, "Alice", 4, &[5, 11, 17, 23]);
    let mut owner = load(
        &bytes,
        "Alice",
        "cancel",
        &registry,
        &[root.clone(), root.clone()],
        vec![field(3), Value::Bool(true)],
    )
    .unwrap();
    query(&mut owner, "first_draw");
    owner.cancel();
    observe(&registry, &root, 1, 3, false, false);
    let mut reused = load(
        &single,
        "Alice",
        "reuse",
        &registry,
        std::slice::from_ref(&root),
        vec![],
    )
    .unwrap();
    query(&mut reused, "draw");
    drop(reused);
    observe(&registry, &root, 2, 2, false, false);

    // Authentic authority for one field cannot satisfy another field's port.
    let wrong = registry
        .issue_random_for(
            "Alice",
            zkc_runtime::interactive::ServiceContract::RandomBn254Field,
            1,
        )
        .unwrap();
    let refused = load(
        &single,
        "Alice",
        "wrong_contract",
        &registry,
        std::slice::from_ref(&wrong),
        vec![],
    )
    .err()
    .unwrap();
    assert!(refused.to_string().contains("service-port-interface"));
    assert_eq!(
        registry.observe(&wrong).unwrap().state.unwrap().draw_count,
        0
    );
    registry.retire(&wrong).unwrap();

    // Ownership and all-or-nothing entry acquisition.
    let other = tape(&registry, "Bob", 1, &[5]);
    assert!(
        load(
            &bytes,
            "Alice",
            "owner",
            &registry,
            &[root.clone(), other],
            vec![field(3), Value::Bool(true)]
        )
        .is_err()
    );
    observe(&registry, &root, 2, 2, false, false);
    assert!(
        load(
            &bytes,
            "Alice",
            "missing",
            &registry,
            std::slice::from_ref(&root),
            vec![field(3), Value::Bool(true)]
        )
        .is_err()
    );
    let held = tape(&registry, "Alice", 1, &[5]);
    let active = load(
        &single,
        "Alice",
        "active",
        &registry,
        std::slice::from_ref(&held),
        vec![],
    )
    .unwrap();
    assert!(
        load(
            &bytes,
            "Alice",
            "partial",
            &registry,
            &[root.clone(), held],
            vec![field(3), Value::Bool(true)]
        )
        .is_err()
    );
    observe(&registry, &root, 2, 2, false, false);
    drop(active);

    // A data-entry refusal releases a tentatively acquired service lease.
    let native = backend("Alice", "authorized_session");
    let admitted = admit_supplied(&single, &native).unwrap();
    let port = admitted.entry("main").unwrap()[0].services[0].name.clone();
    let native = native
        .with_services(registry.clone(), BTreeMap::from([(port, root.clone())]))
        .unwrap();
    let failure = match Runner::new(&admitted, "main", "Alice", "wrong_session", native, vec![]) {
        Err(failure) => failure,
        Ok(_) => panic!("entry domain must fail"),
    };
    assert_eq!(failure.backend.active_frames(), 0);
    observe(&registry, &root, 2, 2, false, false);
    let retried = Runner::new(
        &admitted,
        "main",
        "Alice",
        "authorized_session",
        failure.backend,
        vec![],
    )
    .map_err(|failure| failure.error)
    .unwrap();
    drop(retried);
    observe(&registry, &root, 2, 2, false, false);

    // Failed service binding preserves legacy affine inputs and backend custody.
    let mut artifact: serde_json::Value = serde_json::from_slice(&single).unwrap();
    artifact[4][0][5] = serde_json::json!([["rng", "rng:bls12-381.fr@host.resource/1"]]);
    let artifact = serde_json::to_vec(&artifact).unwrap();
    let mut native = backend("Alice", "affine_input");
    let input = native
        .issue_test_rng(
            Domain::new("Alice", "affine_input", "main", None),
            2,
            [7; 32],
        )
        .unwrap();
    let Value::Rng(token) = &input else {
        panic!("rng")
    };
    let before = native.observe(token).unwrap();
    let admitted = admit_supplied(&artifact, &native).unwrap();
    let port = admitted.entry("main").unwrap()[0].services[0].name.clone();
    let wrong_owner = tape(&registry, "Bob", 1, &[5]);
    let native = native
        .with_services(
            registry.clone(),
            BTreeMap::from([(port.clone(), wrong_owner)]),
        )
        .unwrap();
    let failure = match Runner::new(
        &admitted,
        "main",
        "Alice",
        "affine_input",
        native,
        vec![input.clone()],
    ) {
        Err(failure) => failure,
        Ok(_) => panic!("service owner must fail"),
    };
    assert_eq!(failure.backend.active_frames(), 0);
    assert_eq!(failure.backend.observe(token).unwrap(), before);
    let native = failure
        .backend
        .with_services(registry.clone(), BTreeMap::from([(port, root.clone())]))
        .unwrap();
    let retried = Runner::new(
        &admitted,
        "main",
        "Alice",
        "affine_input",
        native,
        vec![input],
    )
    .map_err(|failure| failure.error)
    .unwrap();
    drop(retried);
    observe(&registry, &root, 2, 2, false, false);

    // Capacity refusal happens at the query cut, before the consume.
    let native = backend("Alice", "capacity");
    let admitted = admit_supplied(&single, &native).unwrap();
    let port = admitted.entry("main").unwrap()[0].services[0].name.clone();
    let native = native
        .with_services(registry.clone(), BTreeMap::from([(port, root.clone())]))
        .unwrap();
    let mut limited = Runner::new_with_value_budget(
        &admitted,
        "main",
        "Alice",
        "capacity",
        native,
        vec![],
        ValueBudget {
            live_bytes: 0,
            total_bytes: 0,
        },
    )
    .map_err(|failure| failure.error)
    .unwrap();
    query(&mut limited, "draw");
    assert!(matches!(limited.poll(), Action::Stopped(stop) if stop.kind == StopKind::Limit));
    observe(&registry, &root, 2, 2, false, false);
    let native = backend("Alice", "changing_signature");
    let admitted = admit_supplied(&single, &native).unwrap();
    let port = admitted.entry("main").unwrap()[0].services[0].name.clone();
    let native = native
        .with_services(registry.clone(), BTreeMap::from([(port, root.clone())]))
        .unwrap();
    let mut changing = Runner::new(
        &admitted,
        "main",
        "Alice",
        "changing_signature",
        ChangingSignature(native, std::cell::Cell::new(false)),
        vec![],
    )
    .map_err(|failure| failure.error)
    .unwrap();
    let Action::Query(action) = changing.poll() else {
        panic!("query")
    };
    changing.execute_query(&action.cut).unwrap();
    assert!(
        matches!(changing.poll(), Action::Stopped(stop) if matches!(stop.kind, StopKind::Backend(ref code) if code.code == "service-signature"))
    );
    observe(&registry, &root, 2, 2, false, false);

    // Invalid replies must poison every alias after the completed native draw.
    for wrong_type in [false, true] {
        let registry = ServiceRegistry::new(Policy::default());
        let root = tape(&registry, "Alice", 2, &[5, 11]);
        let native = backend("Alice", "bad_reply");
        let admitted = admit_supplied(&single, &native).unwrap();
        let port = admitted.entry("main").unwrap()[0].services[0].name.clone();
        let native = native
            .with_services(registry.clone(), BTreeMap::from([(port, root.clone())]))
            .unwrap();
        let mut runner = Runner::new(
            &admitted,
            "main",
            "Alice",
            "bad_reply",
            InvalidReply(native, wrong_type),
            vec![],
        )
        .map_err(|failure| failure.error)
        .unwrap();
        let Action::Query(action) = runner.poll() else {
            panic!("query")
        };
        runner.execute_query(&action.cut).unwrap();
        assert!(matches!(runner.poll(), Action::Stopped(_)));
        assert_eq!(runner.backend().0.active_frames(), 0);
        observe(&registry, &root, 1, 1, true, false);
        assert!(
            load(
                &single,
                "Alice",
                "retry",
                &registry,
                std::slice::from_ref(&root),
                vec![]
            )
            .is_err()
        );
    }
    println!(
        "generated native service participants: aliases, distinct roots, ordered cuts, native messages, guards, failure poisoning, lease cleanup and sequential reuse passed"
    );
}
