"""Regenerate primitive-only trusted reply tables and archived expected values.

Build the pinned external_replay example first. This generator replays each
archive and records exact hash/permutation input/output pairs. It does not
establish primitive correctness: Lean's trusted boundary is explicit.
"""
import argparse
import json
import subprocess
import hashlib
import tempfile
from pathlib import Path
root=Path(__file__).resolve().parents[2]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--replay',type=Path,required=True,help='built external_replay executable')
parser.add_argument('--output',type=Path,required=True,help='where to write the reply tables (the corpus keeps them at tests/fixtures/external-constructions.json)')
args=parser.parse_args()
replay=args.replay.resolve()
fx=root/'tests/fixtures/external-transcript'
temporary=tempfile.TemporaryDirectory(prefix='zkc-external-fixtures-')
replays=Path(temporary.name)
subprocess.run(['python3',str(Path(__file__).with_name('make_replays.py')),str(replays)],check=True)
oracles={}; traces=[]; moneros=[]
def invoke(p):return json.loads(subprocess.check_output([str(replay)],input=json.dumps(p).encode()))
def save(name,inp,out):
 k=name+':'+json.dumps(inp,separators=(',',':')); assert k not in oracles or oracles[k]==out;oracles[k]=out
hs='monero.v0.18.5.1.keccak256.reduce32'; ps='openvm.stark-backend.v2.0.1.poseidon2.babybear.0.4.3'
for path in sorted(replays.glob('*.json')):
 p=json.loads(path.read_text());out=invoke(p);name=path.name.replace('.replay.json','')
 if 'monero' in name:
  items={x['id']:list(bytes.fromhex(''.join(x['values']))) for x in p['items']};state=list(bytes.fromhex(p['initial']));groups=[];challenges=[]
  for e,c in zip(p['events'],out['checkpoints']):
   data=sum([items[k] for k in e['items']],[]);h=list(bytes.fromhex(c['value']));save(hs,data if e['op']=='hash' else state+data,h)
   if e['op']=='hash':items[e['output']]=h
   else:
    state=h
    if e['items']!=['Hv']:groups.append(data);challenges+=h
  moneros.append(dict(name=name,initial=list(bytes.fromhex(p['initial'])),commitments=items['V'],messages=sum(groups,[]),lengths=list(map(len,groups)),challenges=challenges,state=state))
 else:
  archived=json.loads((fx/(name+'.transcript.json')).read_text());st=[0]*16;a=s=0
  for e,c in zip(archived,out['checkpoints']):
   if not e['sample']:st[a]=e['value'];a+=1
   perm=(not e['sample'] and a==8) or (e['sample'] and (a!=0 or s==0))
   if perm:save(ps,st[:],c['state']['state']);st=c['state']['state'][:];a=0;s=8
   if e['sample']:s-=1
   assert c['state']==dict(state=st,absorb_index=a,sample_index=s)
  traces.append(dict(name=name,events=archived,final=[1514881876,1,2]+st+[a,s]))
# Demo oracle schedule, native permutations admitted as explicit trusted fixtures.
for bits in [0,4]:
 p=dict(version=1,profile='openvm-babybear-poseidon2-v1',items=[dict(id='obs',origin='bridge-demo',wire_index=None,kind='fields',values=[1,2,3])],unobserved=[],events=[dict(op='observe',items=['obs']),dict(op='sample'),dict(op='sample_ext'),dict(op='sample_bits',bits=bits),dict(op='check_witness',bits=bits,witness=5),dict(op='check_witness',bits=0,witness=5)])
 out=invoke(p);c=out['checkpoints'];save(ps,[1,2,3]+[0]*13,c[1]['state']['state'])
 if bits:
  st=c[3]['state']['state'][:];st[c[3]['state']['absorb_index']]=5;save(ps,st,c[4]['state']['state'])
 # Preserve primitive transition outcomes, including failed witness successor.
 traces.append(dict(name=f'demo-{bits}',checkpoints=c))
for v in json.loads((fx/'monero-hash-vectors.json').read_text())['vectors']:
 save(hs,list(bytes.fromhex(''.join(v['items']))),list(bytes.fromhex(v['scalar'])))
result=dict(version=1,trust='Hs and Poseidon2 output tables generated by pinned native primitive providers; schedule is independently computed by Lean. Archived challenge expectations remain separate upstream evidence.',sources={x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in sorted(fx.glob('*')) if x.suffix in ('.json','.proof')},oracles=[[k.split(':',1)[0],json.loads(k.split(':',1)[1]),v] for k,v in oracles.items()],monero=moneros,openvm=traces)
args.output.write_text(json.dumps(result,separators=(',',':'))+'\n')
print(len(oracles),'primitive entries',len(moneros),'Monero',len(traces)-2,'OpenVM archives')
